In [4]:
import pandas as pd

In [87]:
df=pd.read_csv(r'https://raw.githubusercontent.com/selva86/datasets/master/Smarket.csv')

In [88]:
df.head()

   Year   Lag1   Lag2   Lag3   Lag4   Lag5  Volume  Today Direction
0  2001  0.381 -0.192 -2.624 -1.055  5.010  1.1913  0.959        Up
1  2001  0.959  0.381 -0.192 -2.624 -1.055  1.2965  1.032        Up
2  2001  1.032  0.959  0.381 -0.192 -2.624  1.4112 -0.623      Down
3  2001 -0.623  1.032  0.959  0.381 -0.192  1.2760  0.614        Up
4  2001  0.614 -0.623  1.032  0.959  0.381  1.2057  0.213        Up

In [89]:
df.dtypes

Year           int64
Lag1         float64
Lag2         float64
Lag3         float64
Lag4         float64
Lag5         float64
Volume       float64
Today        float64
Direction     object
dtype: object

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Year       1250 non-null   int64
 1   Lag1       1250 non-null   float64
 2   Lag2       1250 non-null   float64
 3   Lag3       1250 non-null   float64
 4   Lag4       1250 non-null   float64
 5   Lag5       1250 non-null   float64
 6   Volume     1250 non-null   float64
 7   Today      1250 non-null   float64
 8   Direction  1250 non-null   object
dtypes: float64(7), int64(1), object(1)
memory usage: 88.0+ KB

In [91]:
df.isnull().sum()

Year         0
Lag1         0
Lag2         0
Lag3         0
Lag4         0
Lag5         0
Volume       0
Today        0
Direction    0
dtype: int64

In [92]:
df.describe()

,Year,Lag1,Lag2,Lag3,Lag4,Lag5,Volume,Today
count,1250.000000,1250.000000,1250.000000,1250.000000,1250.000000,1250.00000,1250.000000,1250.000000
mean,2003.016000,0.003834,0.003919,0.001716,0.001636,0.00561,1.478305,0.003138
std,1.409018,1.136299,1.136280,1.138703,1.138774,1.14755,0.360357,1.136334
min,2001.000000,-4.922000,-4.922000,-4.922000,-4.922000,-4.92200,0.356070,-4.922000
25%,2002.000000,-0.639500,-0.639500,-0.640000,-0.640000,-0.64000,1.257400,-0.639500
50%,2003.000000,0.039000,0.039000,0.038500,0.038500,0.03850,1.422950,0.038500
75%,2004.000000,0.596750,0.596750,0.596750,0.596750,0.59700,1.641675,0.596750
max,2005.000000,5.733000,5.733000,5.733000,5.733000,5.73300,3.152470,5.733000

In [93]:
df['Direction'].value_counts()

Up      648
Down    602
Name: Direction, dtype: int64

In [94]:
df['average_Lag']=(df['Lag1']+df['Lag2']+df['Lag3']+df['Lag4']+df['Lag5'])/5

In [95]:
df.head()

,Year,Lag1,Lag2,Lag3,Lag4,Lag5,Volume,Today,Direction,average_Lag
0,2001,0.381,-0.192,-2.624,-1.055,5.010,1.1913,0.959,Up,0.3040
1,2001,0.959,0.381,-0.192,-2.624,-1.055,1.2965,1.032,Up,-0.5062
2,2001,1.032,0.959,0.381,-0.192,-2.624,1.4112,-0.623,Down,-0.0888
3,2001,-0.623,1.032,0.959,0.381,-0.192,1.2760,0.614,Up,0.3114
4,2001,0.614,-0.623,1.032,0.959,0.381,1.2057,0.213,Up,0.4726

In [96]:
df.dtypes

Year             int64
Lag1           float64
Lag2           float64
Lag3           float64
Lag4           float64
Lag5           float64
Volume         float64
Today          float64
Direction       object
average_Lag    float64
dtype: object

In [97]:
df.head()

,Year,Lag1,Lag2,Lag3,Lag4,Lag5,Volume,Today,Direction,average_Lag
0,2001,0.381,-0.192,-2.624,-1.055,5.010,1.1913,0.959,Up,0.3040
1,2001,0.959,0.381,-0.192,-2.624,-1.055,1.2965,1.032,Up,-0.5062
2,2001,1.032,0.959,0.381,-0.192,-2.624,1.4112,-0.623,Down,-0.0888
3,2001,-0.623,1.032,0.959,0.381,-0.192,1.2760,0.614,Up,0.3114
4,2001,0.614,-0.623,1.032,0.959,0.381,1.2057,0.213,Up,0.4726

In [98]:
df[df['average_Lag']==max(df['average_Lag'])]

,Year,Lag1,Lag2,Lag3,Lag4,Lag5,Volume,Today,Direction,average_Lag
387,2002,0.425,5.408,1.688,-0.563,5.733,1.82609,0.979,Up,2.5382

In [27]:
df[df['average_Lag']==min(df['average_Lag'])]

,Year,Lag1,Lag2,Lag3,Lag4,Lag5,Volume,Today,Direction,average_Lag
173,2001,-1.903,-3.106,-1.611,-0.58,-4.922,2.3173,3.898,Up,-2.4244

In [28]:
df[df['Volume']==max(df['Volume'])]

,Year,Lag1,Lag2,Lag3,Lag4,Lag5,Volume,Today,Direction,average_Lag
1177,2005,0.829,0.046,-0.328,-0.754,-0.074,3.15247,-0.557,Down,-0.0562

In [29]:
df[df['Volume']==min(df['Volume'])]

,Year,Lag1,Lag2,Lag3,Lag4,Lag5,Volume,Today,Direction,average_Lag
743,2003,0.169,-0.181,0.282,0.393,-0.048,0.35607,1.24,Up,0.123

In [31]:
import os
import mysql.connector as conn
import csv

In [32]:
df.columns

Index(['Year', 'Lag1', 'Lag2', 'Lag3', 'Lag4', 'Lag5', 'Volume', 'Today',
       'Direction', 'average_Lag'],
      dtype='object')

In [33]:
df.columns=[x.replace(' ','_') for x in df.columns]
df.columns

Index(['Year', 'Lag1', 'Lag2', 'Lag3', 'Lag4', 'Lag5', 'Volume', 'Today',
       'Direction', 'average_Lag'],
      dtype='object')

In [43]:
df.dtypes.values

array([dtype('int64'), dtype('float64'), dtype('float64'),
       dtype('float64'), dtype('float64'), dtype('float64'),
       dtype('float64'), dtype('float64'), dtype('O'), dtype('float64')],
      dtype=object)

In [37]:
replacement={
    'int64':'bigint(50)',
    'float64':'float(50)',
    'object':'varchar(100)'
}

In [38]:
df.dtypes.replace(replacement)

Year             bigint(50)
Lag1              float(50)
Lag2              float(50)
Lag3              float(50)
Lag4              float(50)
Lag5              float(50)
Volume            float(50)
Today             float(50)
Direction      varchar(100)
average_Lag       float(50)
dtype: object

In [53]:
columns = ", ".join("{} {}".format(a,b) for (a,b) in zip(df.columns, df.dtypes.replace(replacement)))
columns

'Year bigint(50), Lag1 float(50), Lag2 float(50), Lag3 float(50), Lag4 float(50), Lag5 float(50), Volume float(50), Today float(50), Direction varchar(100), average_Lag float(50)'

In [63]:
connection=conn.connect(host='localhost',user='root',passwd='Luci1108$')
cursor=connection.cursor()
print("Successfully connected!!")

Successfully connected!!

In [64]:
cursor.execute('create database Smarket_data')

In [65]:
cursor.execute('use Smarket_data')

In [67]:
cursor.execute('create table Smarket ({})'.format(columns))

In [102]:
for i,row in df.iterrows():
    print('insert into Smarket values({},{},{},{},{},{},{},{},{},{})'.format(row[0],row[1],row[2],row[3],row[4],row[5],row[6],row[7],row[8],row[9]))

insert into Smarket values(2001,0.381,-0.192,-2.624,-1.055,5.01,1.1913,0.959,Up,0.30399999999999994)
insert into Smarket values(2001,0.959,0.381,-0.192,-2.624,-1.055,1.2965,1.032,Up,-0.5062)
insert into Smarket values(2001,1.032,0.959,0.381,-0.192,-2.624,1.4112,-0.623,Down,-0.08880000000000007)
insert into Smarket values(2001,-0.623,1.032,0.959,0.381,-0.192,1.276,0.614,Up,0.3114)
insert into Smarket values(2001,0.614,-0.623,1.032,0.959,0.381,1.2057,0.213,Up,0.4726000000000001)
insert into Smarket values(2001,0.213,0.614,-0.623,1.032,0.959,1.3491,1.392,Up,0.43899999999999995)
insert into Smarket values(2001,1.392,0.213,0.614,-0.623,1.032,1.445,-0.403,Down,0.5256000000000001)
insert into Smarket values(2001,-0.403,1.392,0.213,0.614,-0.623,1.4078,0.027,Up,0.23859999999999998)
insert into Smarket values(2001,0.027,-0.403,1.392,0.213,0.614,1.164,1.303,Up,0.3686)
insert into Smarket values(2001,1.303,0.027,-0.403,1.392,0.213,1.2326,0.287,Up,0.5064)
insert into Smarket values(2001,0.287,1.303,0.027,-0.403,1.392,1.309,-0.498,Down,0.5212)
insert into Smarket values(2001,-0.498,0.287,1.303,0.027,-0.403,1.258,-0.189,Down,0.14319999999999994)
insert into Smarket values(2001,-0.189,-0.498,0.287,1.303,0.027,1.098,0.68,Up,0.18599999999999997)
insert into Smarket values(2001,0.68,-0.189,-0.498,0.287,1.303,1.0531,0.701,Up,0.3166)
insert into Smarket values(2001,0.701,0.68,-0.189,-0.498,0.287,1.1498,-0.562,Down,0.19619999999999999)
insert into Smarket values(2001,-0.562,0.701,0.68,-0.189,-0.498,1.2953,0.546,Up,0.02639999999999998)
insert into Smarket values(2001,0.546,-0.562,0.701,0.68,-0.189,1.1188,-1.747,Down,0.2352)
insert into Smarket values(2001,-1.747,0.546,-0.562,0.701,0.68,1.0484,0.359,Up,-0.07640000000000005)
insert into Smarket values(2001,0.359,-1.747,0.546,-0.562,0.701,1.013,-0.151,Down,-0.14060000000000003)
insert into Smarket values(2001,-0.151,0.359,-1.747,0.546,-0.562,1.0596,-0.841,Down,-0.31100000000000005)
insert into Smarket values(2001,-0.841,-0.151,0.359,-1.747,0.546,1.1583,-0.623,Down,-0.36679999999999996)
insert into Smarket values(2001,-0.623,-0.841,-0.151,0.359,-1.747,1.1072,-1.334,Down,-0.6006)
insert into Smarket values(2001,-1.334,-0.623,-0.841,-0.151,0.359,1.0755,1.183,Up,-0.518)
insert into Smarket values(2001,1.183,-1.334,-0.623,-0.841,-0.151,1.0391,-0.865,Down,-0.3532)
insert into Smarket values(2001,-0.865,1.183,-1.334,-0.623,-0.841,1.0752,-0.218,Down,-0.496)
insert into Smarket values(2001,-0.218,-0.865,1.183,-1.334,-0.623,1.1503,0.812,Up,-0.3714)
insert into Smarket values(2001,0.812,-0.218,-0.865,1.183,-1.334,1.1537,-1.891,Down,-0.08439999999999999)
insert into Smarket values(2001,-1.891,0.812,-0.218,-0.865,1.183,1.2572,-1.736,Down,-0.19579999999999997)
insert into Smarket values(2001,-1.736,-1.891,0.812,-0.218,-0.865,1.1122,-1.851,Down,-0.7796)
insert into Smarket values(2001,-1.851,-1.736,-1.891,0.812,-0.218,1.2085,-0.195,Down,-0.9767999999999999)
insert into Smarket values(2001,-0.195,-1.851,-1.736,-1.891,0.812,1.3659,-0.556,Down,-0.9722)
insert into Smarket values(2001,-0.556,-0.195,-1.851,-1.736,-1.891,1.2313,1.749,Up,-1.2458)
insert into Smarket values(2001,1.749,-0.556,-0.195,-1.851,-1.736,1.1308,-0.766,Down,-0.5178)
insert into Smarket values(2001,-0.766,1.749,-0.556,-0.195,-1.851,1.1141,-1.431,Down,-0.3238)
insert into Smarket values(2001,-1.431,-0.766,1.749,-0.556,-0.195,1.2253,0.104,Up,-0.2398)
insert into Smarket values(2001,0.104,-1.431,-0.766,1.749,-0.556,1.2949,-0.568,Down,-0.18)
insert into Smarket values(2001,-0.568,0.104,-1.431,-0.766,1.749,1.294,0.586,Up,-0.18239999999999998)
insert into Smarket values(2001,0.586,-0.568,0.104,-1.431,-0.766,0.9292,0.998,Up,-0.41500000000000004)
insert into Smarket values(2001,0.998,0.586,-0.568,0.104,-1.431,1.0918,0.645,Up,-0.06219999999999999)
insert into Smarket values(2001,0.645,0.998,0.586,-0.568,0.104,1.1322,0.226,Up,0.35300000000000004)
insert into Smarket values(2001,0.226,0.645,0.998,0.586,-0.568,1.1141,-2.476,Down,0.3774)
insert into Smarket values(2001,-2.476,0.226,0.645,0.998,0.586,1.0859,-4.318,Down,-0.004200000000000004)
insert into Smarket values(2001,-4.318,-2.476,0.226,0.645,0.998,1.229,1.483,Up,-0.985)
insert into Smarket values(2001,1.483,-4.318,-2.476,0.226,0.645,1.3609,-2.584,Down,-0.8879999999999999)
insert into Smarket values(2001,-2.584,1.483,-4.318,-2.476,0.226,1.3974,0.587,Up,-1.5337999999999998)
insert into Smarket values(2001,0.587,-2.584,1.483,-4.318,-2.476,1.2595,-1.962,Down,-1.4616)
insert into Smarket values(2001,-1.962,0.587,-2.584,1.483,-4.318,1.54356,1.763,Up,-1.3588)
insert into Smarket values(2001,1.763,-1.962,0.587,-2.584,1.483,1.1262,-2.408,Down,-0.1426)
insert into Smarket values(2001,-2.408,1.763,-1.962,0.587,-2.584,1.2359,-1.792,Down,-0.9208000000000002)
insert into Smarket values(2001,-1.792,-2.408,1.763,-1.962,0.587,1.3463,-0.406,Down,-0.7624000000000001)
insert into Smarket values(2001,-0.406,-1.792,-2.408,1.763,-1.962,1.72395,1.991,Up,-0.961)
insert into Smarket values(2001,1.991,-0.406,-1.792,-2.408,1.763,1.3649,1.128,Up,-0.17040000000000005)
insert into Smarket values(2001,1.128,1.991,-0.406,-1.792,-2.408,1.114,2.557,Up,-0.29740000000000005)
insert into Smarket values(2001,2.557,1.128,1.991,-0.406,-1.792,1.3142,-2.443,Down,0.6956000000000001)
insert into Smarket values(2001,-2.443,2.557,1.128,1.991,-0.406,1.3334,-0.463,Down,0.5653999999999999)
insert into Smarket values(2001,-0.463,-2.443,2.557,1.128,1.991,1.2345,1.078,Up,0.5539999999999999)
insert into Smarket values(2001,1.078,-0.463,-2.443,2.557,1.128,1.2808,-1.246,Down,0.37139999999999995)
insert into Smarket values(2001,-1.246,1.078,-0.463,-2.443,2.557,1.2549,-3.439,Down,-0.10339999999999998)
insert into Smarket values(2001,-3.439,-1.246,1.078,-0.463,-2.443,1.3861,-0.29,Down,-1.3026)
insert into Smarket values(2001,-0.29,-3.439,-1.246,1.078,-0.463,1.42559,4.368,Up,-0.8719999999999999)
insert into Smarket values(2001,4.368,-0.29,-3.439,-1.246,1.078,1.368,-1.998,Down,0.09420000000000006)
insert into Smarket values(2001,-1.998,4.368,-0.29,-3.439,-1.246,1.2668,0.812,Up,-0.521)
insert into Smarket values(2001,0.812,-1.998,4.368,-0.29,-3.439,1.0628,2.707,Up,-0.10939999999999994)
insert into Smarket values(2001,2.707,0.812,-1.998,4.368,-0.29,1.3496,-0.213,Down,1.1198000000000001)
insert into Smarket values(2001,-0.213,2.707,0.812,-1.998,4.368,1.2903,1.51,Up,1.1352)
insert into Smarket values(2001,1.51,-0.213,2.707,0.812,-1.998,1.102,-0.323,Down,0.5635999999999999)
insert into Smarket values(2001,-0.323,1.51,-0.213,2.707,0.812,0.9139,1.028,Up,0.8986000000000001)
insert into Smarket values(2001,1.028,-0.323,1.51,-0.213,2.707,1.1096,3.889,Up,0.9418)
insert into Smarket values(2001,3.889,1.028,-0.323,1.51,-0.213,1.9189,1.254,Up,1.1782)
insert into Smarket values(2001,1.254,3.889,1.028,-0.323,1.51,1.4868,-0.854,Down,1.4715999999999998)
insert into Smarket values(2001,-0.854,1.254,3.889,1.028,-0.323,1.3387,-1.498,Down,0.9987999999999999)
insert into Smarket values(2001,-1.498,-0.854,1.254,3.889,1.028,1.0126,-1.216,Down,0.7638)
insert into Smarket values(2001,-1.216,-1.498,-0.854,1.254,3.889,1.2165,1.594,Up,0.31499999999999995)
insert into Smarket values(2001,1.594,-1.216,-1.498,-0.854,1.254,1.2036,0.47,Up,-0.14399999999999996)
insert into Smarket values(2001,0.47,1.594,-1.216,-1.498,-0.854,1.3452,1.501,Up,-0.3008)
insert into Smarket values(2001,1.501,0.47,1.594,-1.216,-1.498,1.0913,-0.287,Down,0.17020000000000005)
insert into Smarket values(2001,-0.287,1.501,0.47,1.594,-1.216,1.2668,1.359,Up,0.41240000000000004)
insert into Smarket values(2001,1.359,-0.287,1.501,0.47,1.594,1.1813,0.078,Up,0.9274000000000001)
insert into Smarket values(2001,0.078,1.359,-0.287,1.501,0.47,1.3422,-1.487,Down,0.6241999999999999)
insert into Smarket values(2001,-1.487,0.078,1.359,-0.287,1.501,1.1379,1.444,Up,0.23279999999999998)
insert into Smarket values(2001,1.444,-1.487,0.078,1.359,-0.287,1.0821,-0.245,Down,0.22139999999999999)
insert into Smarket values(2001,-0.245,1.444,-1.487,0.078,1.359,0.949,-0.183,Down,0.22979999999999995)
insert into Smarket values(2001,-0.183,-0.245,1.444,-1.487,0.078,1.0063,-0.449,Down,-0.07860000000000002)
insert into Smarket values(2001,-0.449,-0.183,-0.245,1.444,-1.487,1.1324,-0.029,Down,-0.18400000000000002)
insert into Smarket values(2001,-0.029,-0.449,-0.183,-0.245,1.444,1.0567,-0.758,Down,0.10759999999999999)
insert into Smarket values(2001,-0.758,-0.029,-0.449,-0.183,-0.245,0.9062,0.261,Up,-0.33280000000000004)
insert into Smarket values(2001,0.261,-0.758,-0.029,-0.449,-0.183,0.8582,0.042,Up,-0.23160000000000003)
insert into Smarket values(2001,0.042,0.261,-0.758,-0.029,-0.449,1.0718,2.845,Up,-0.18660000000000002)
insert into Smarket values(2001,2.845,0.042,0.261,-0.758,-0.029,1.4053,0.272,Up,0.47220000000000006)
insert into Smarket values(2001,0.272,2.845,0.042,0.261,-0.758,1.3556,0.269,Up,0.5324)
insert into Smarket values(2001,0.269,0.272,2.845,0.042,0.261,1.1308,1.615,Up,0.7378)
insert into Smarket values(2001,1.615,0.269,0.272,2.845,0.042,1.1749,-0.263,Down,1.0086)
insert into Smarket values(2001,-0.263,1.615,0.269,0.272,2.845,1.2604,-1.553,Down,0.9476000000000001)
insert into Smarket values(2001,-1.553,-0.263,1.615,0.269,0.272,1.1348,0.32,Up,0.06800000000000003)
insert into Smarket values(2001,0.32,-1.553,-0.263,1.615,0.269,1.1007,-1.182,Down,0.0776)
insert into Smarket values(2001,-1.182,0.32,-1.553,-0.263,1.615,0.8281,-0.779,Down,-0.21259999999999998)
insert into Smarket values(2001,-0.779,-1.182,0.32,-1.553,-0.263,1.026,-1.566,Down,-0.6914)
insert into Smarket values(2001,-1.566,-0.779,-1.182,0.32,-1.553,1.1586,0.62,Up,-0.952)
insert into Smarket values(2001,0.62,-1.566,-0.779,-1.182,0.32,1.2266,0.386,Up,-0.5174000000000001)
insert into Smarket values(2001,0.386,0.62,-1.566,-0.779,-1.182,1.015,0.511,Up,-0.5042)
insert into Smarket values(2001,0.511,0.386,0.62,-1.566,-0.779,0.8365,1.299,Up,-0.16560000000000002)
insert into Smarket values(2001,1.299,0.511,0.386,0.62,-1.566,1.1168,-1.055,Down,0.25000000000000006)
insert into Smarket values(2001,-1.055,1.299,0.511,0.386,0.62,1.0619,0.546,Up,0.3522)
insert into Smarket values(2001,0.546,-1.055,1.299,0.511,0.386,1.0896,-0.94,Down,0.33740000000000003)
insert into Smarket values(2001,-0.94,0.546,-1.055,1.299,0.511,0.7262,-0.836,Down,0.07220000000000001)
insert into Smarket values(2001,-0.836,-0.94,0.546,-1.055,1.299,0.8701,0.116,Up,-0.19719999999999996)
insert into Smarket values(2001,0.116,-0.836,-0.94,0.546,-1.055,1.1365,-1.135,Down,-0.4337999999999999)
insert into Smarket values(2001,-1.135,0.116,-0.836,-0.94,0.546,1.0636,-1.75,Down,-0.4497999999999999)
insert into Smarket values(2001,-1.75,-1.135,0.116,-0.836,-0.94,1.2429,-0.452,Down,-0.909)
insert into Smarket values(2001,-0.452,-1.75,-1.135,0.116,-0.836,1.63555,-0.488,Down,-0.8113999999999999)
insert into Smarket values(2001,-0.488,-0.452,-1.75,-1.135,0.116,1.1116,0.343,Up,-0.7418)
insert into Smarket values(2001,0.343,-0.488,-0.452,-1.75,-1.135,1.1849,0.871,Up,-0.6964)
insert into Smarket values(2001,0.871,0.343,-0.488,-0.452,-1.75,1.3501,1.136,Up,-0.2952)
insert into Smarket values(2001,1.136,0.871,0.343,-0.488,-0.452,1.54682,-0.945,Down,0.2819999999999999)
insert into Smarket values(2001,-0.945,1.136,0.871,0.343,-0.488,1.1892,-0.551,Down,0.18339999999999995)
insert into Smarket values(2001,-0.551,-0.945,1.136,0.871,0.343,1.0501,-0.151,Down,0.17079999999999998)
insert into Smarket values(2001,-0.151,-0.551,-0.945,1.136,0.871,1.1989,-0.468,Down,0.07199999999999998)
insert into Smarket values(2001,-0.468,-0.151,-0.551,-0.945,1.136,1.1621,1.249,Up,-0.19579999999999997)
insert into Smarket values(2001,1.249,-0.468,-0.151,-0.551,-0.945,1.3273,-0.148,Down,-0.17319999999999997)
insert into Smarket values(2001,-0.148,1.249,-0.468,-0.151,-0.551,1.83236,1.008,Up,-0.013799999999999969)
insert into Smarket values(2001,1.008,-0.148,1.249,-0.468,-0.151,1.1283,-0.184,Down,0.298)
insert into Smarket values(2001,-0.184,1.008,-0.148,1.249,-0.468,0.62211,-1.232,Down,0.29140000000000005)
insert into Smarket values(2001,-1.232,-0.184,1.008,-0.148,1.249,0.9349,-2.35,Down,0.13860000000000003)
insert into Smarket values(2001,-2.35,-1.232,-0.184,1.008,-0.148,1.0567,0.688,Up,-0.5812)
insert into Smarket values(2001,0.688,-2.35,-1.232,-0.184,1.008,1.0457,-1.44,Down,-0.41400000000000003)
insert into Smarket values(2001,-1.44,0.688,-2.35,-1.232,-0.184,1.2638,-0.113,Down,-0.9036000000000002)
insert into Smarket values(2001,-0.113,-1.44,0.688,-2.35,-1.232,1.3841,2.369,Up,-0.8894)
insert into Smarket values(2001,2.369,-0.113,-1.44,0.688,-2.35,1.394,0.624,Up,-0.16919999999999996)
insert into Smarket values(2001,0.624,2.369,-0.113,-1.44,0.688,1.1217,-1.088,Down,0.42560000000000003)
insert into Smarket values(2001,-1.088,0.624,2.369,-0.113,-1.44,1.0398,0.997,Up,0.07040000000000006)
insert into Smarket values(2001,0.997,-1.088,0.624,2.369,-0.113,1.2381,-0.554,Down,0.5578000000000001)
insert into Smarket values(2001,-0.554,0.997,-1.088,0.624,2.369,1.3163,0.605,Up,0.46959999999999996)
insert into Smarket values(2001,0.605,-0.554,0.997,-1.088,0.624,1.3435,-0.343,Down,0.11679999999999999)
insert into Smarket values(2001,-0.343,0.605,-0.554,0.997,-1.088,1.1709,-1.637,Down,-0.07660000000000004)
insert into Smarket values(2001,-1.637,-0.343,0.605,-0.554,0.997,0.9869,-1.627,Down,-0.1864)
insert into Smarket values(2001,-1.627,-1.637,-0.343,0.605,-0.554,1.1987,1.608,Up,-0.7112)
insert into Smarket values(2001,1.608,-1.627,-1.637,-0.343,0.605,1.2807,1.045,Up,-0.2788)
insert into Smarket values(2001,1.045,1.608,-1.627,-1.637,-0.343,1.2139,0.24,Up,-0.1908)
insert into Smarket values(2001,0.24,1.045,1.608,-1.627,-1.637,1.0153,-0.108,Down,-0.07420000000000004)
insert into Smarket values(2001,-0.108,0.24,1.045,1.608,-1.627,0.9091,0.557,Up,0.23160000000000003)
insert into Smarket values(2001,0.557,-0.108,0.24,1.045,1.608,1.1292,0.388,Up,0.6684)
insert into Smarket values(2001,0.388,0.557,-0.108,0.24,1.045,1.3403,0.396,Up,0.4244)
insert into Smarket values(2001,0.396,0.388,0.557,-0.108,0.24,1.2183,-0.524,Down,0.29460000000000003)
insert into Smarket values(2001,-0.524,0.396,0.388,0.557,-0.108,0.9399,-1.142,Down,0.1418)
insert into Smarket values(2001,-1.142,-0.524,0.396,0.388,0.557,0.8117,0.327,Up,-0.06499999999999999)
insert into Smarket values(2001,0.327,-1.142,-0.524,0.396,0.388,1.012,-1.733,Down,-0.11099999999999999)
insert into Smarket values(2001,-1.733,0.327,-1.142,-0.524,0.396,1.1246,-0.008,Down,-0.5352)
insert into Smarket values(2001,-0.008,-1.733,0.327,-1.142,-0.524,1.1042,0.569,Up,-0.616)
insert into Smarket values(2001,0.569,-0.008,-1.733,0.327,-1.142,0.9609,0.095,Up,-0.39740000000000003)
insert into Smarket values(2001,0.095,0.569,-0.008,-1.733,0.327,0.8376,-0.383,Down,-0.15000000000000005)
insert into Smarket values(2001,-0.383,0.095,0.569,-0.008,-1.733,0.9646,-0.734,Down,-0.29200000000000004)
insert into Smarket values(2001,-0.734,-0.383,0.095,0.569,-0.008,1.0656,0.309,Up,-0.09220000000000002)
insert into Smarket values(2001,0.309,-0.734,-0.383,0.095,0.569,1.0554,-1.666,Down,-0.028800000000000027)
insert into Smarket values(2001,-1.666,0.309,-0.734,-0.383,0.095,0.9743,0.812,Up,-0.4758)
insert into Smarket values(2001,0.812,-1.666,0.309,-0.734,-0.383,0.8971,-1.208,Down,-0.3324)
insert into Smarket values(2001,-1.208,0.812,-1.666,0.309,-0.734,1.0416,0.696,Up,-0.4974)
insert into Smarket values(2001,0.696,-1.208,0.812,-1.666,0.309,1.1108,-0.276,Down,-0.21139999999999998)
insert into Smarket values(2001,-0.276,0.696,-1.208,0.812,-1.666,0.9862,1.965,Up,-0.32839999999999997)
insert into Smarket values(2001,1.965,-0.276,0.696,-1.208,0.812,1.0436,-0.483,Down,0.3978)
insert into Smarket values(2001,-0.483,1.965,-0.276,0.696,-1.208,0.8426,-1.501,Down,0.13880000000000003)
insert into Smarket values(2001,-1.501,-0.483,1.965,-0.276,0.696,0.9871,-1.115,Down,0.08020000000000001)
insert into Smarket values(2001,-1.115,-1.501,-0.483,1.965,-0.276,0.9637,-1.7,Down,-0.2819999999999999)
insert into Smarket values(2001,-1.7,-1.115,-1.501,-0.483,1.965,1.157,0.403,Up,-0.5668)
insert into Smarket values(2001,0.403,-1.7,-1.115,-1.501,-0.483,0.9201,-0.056,Down,-0.8792)
insert into Smarket values(2001,-0.056,0.403,-1.7,-1.115,-1.501,1.1783,-0.106,Down,-0.7938)
insert into Smarket values(2001,-0.106,-0.056,0.403,-1.7,-1.115,1.3845,-2.239,Down,-0.5147999999999999)
insert into Smarket values(2001,-2.239,-0.106,-0.056,0.403,-1.7,1.3597,-1.864,Down,-0.7395999999999999)
insert into Smarket values(2001,-1.864,-2.239,-0.106,-0.056,0.403,1.4243,0.623,Up,-0.7724)
insert into Smarket values(2001,0.623,-1.864,-2.239,-0.106,-0.056,1.2766,-4.922,Down,-0.7283999999999999)
insert into Smarket values(2001,-4.922,0.623,-1.864,-2.239,-0.106,2.33083,-0.58,Down,-1.7015999999999998)
insert into Smarket values(2001,-0.58,-4.922,0.623,-1.864,-2.239,1.65041,-1.611,Down,-1.7963999999999998)
insert into Smarket values(2001,-1.611,-0.58,-4.922,0.623,-1.864,2.12055,-3.106,Down,-1.6707999999999998)
insert into Smarket values(2001,-3.106,-1.611,-0.58,-4.922,0.623,2.0048,-1.903,Down,-1.9192)
insert into Smarket values(2001,-1.903,-3.106,-1.611,-0.58,-4.922,2.3173,3.898,Up,-2.4244)
insert into Smarket values(2001,3.898,-1.903,-3.106,-1.611,-0.58,1.7466,0.879,Up,-0.6603999999999999)
insert into Smarket values(2001,0.879,3.898,-1.903,-3.106,-1.611,1.6138,-0.517,Down,-0.3685999999999999)
insert into Smarket values(2001,-0.517,0.879,3.898,-1.903,-3.106,1.5191,1.149,Up,-0.14980000000000002)
insert into Smarket values(2001,1.149,-0.517,0.879,3.898,-1.903,1.467,2.192,Up,0.7012000000000002)
insert into Smarket values(2001,2.192,1.149,-0.517,0.879,3.898,1.6315,-0.23,Down,1.5202000000000002)
insert into Smarket values(2001,-0.23,2.192,1.149,-0.517,0.879,1.1756,1.231,Up,0.6946000000000001)
insert into Smarket values(2001,1.231,-0.23,2.192,1.149,-0.517,1.2898,1.993,Up,0.7650000000000001)
insert into Smarket values(2001,1.993,1.231,-0.23,2.192,1.149,1.6506,-0.247,Down,1.267)
insert into Smarket values(2001,-0.247,1.993,1.231,-0.23,2.192,1.6091,0.164,Up,0.9878)
insert into Smarket values(2001,0.164,-0.247,1.993,1.231,-0.23,1.3017,-0.834,Down,0.5822)
insert into Smarket values(2001,-0.834,0.164,-0.247,1.993,1.231,0.979,-0.536,Down,0.4614000000000001)
insert into Smarket values(2001,-0.536,-0.834,0.164,-0.247,1.993,1.2278,2.294,Up,0.10799999999999996)
insert into Smarket values(2001,2.294,-0.536,-0.834,0.164,-0.247,1.3124,1.521,Up,0.16820000000000002)
insert into Smarket values(2001,1.521,2.294,-0.536,-0.834,0.164,1.70458,-0.527,Down,0.5218)
insert into Smarket values(2001,-0.527,1.521,2.294,-0.536,-0.834,1.3314,-0.153,Down,0.38359999999999994)
insert into Smarket values(2001,-0.153,-0.527,1.521,2.294,-0.536,1.0247,0.694,Up,0.5197999999999999)
insert into Smarket values(2001,0.694,-0.153,-0.527,1.521,2.294,1.2105,-1.863,Down,0.7657999999999999)
insert into Smarket values(2001,-1.863,0.694,-0.153,-0.527,1.521,1.4522,-0.787,Down,-0.06560000000000006)
insert into Smarket values(2001,-0.787,-1.863,0.694,-0.153,-0.527,1.2629,0.456,Up,-0.5272)
insert into Smarket values(2001,0.456,-0.787,-1.863,0.694,-0.153,1.2949,1.53,Up,-0.3306)
insert into Smarket values(2001,1.53,0.456,-0.787,-1.863,0.694,1.1057,-0.47,Down,0.005999999999999961)
insert into Smarket values(2001,-0.47,1.53,0.456,-0.787,-1.863,1.3173,0.039,Up,-0.22679999999999997)
insert into Smarket values(2001,0.039,-0.47,1.53,0.456,-0.787,1.3362,1.372,Up,0.1536)
insert into Smarket values(2001,1.372,0.039,-0.47,1.53,0.456,1.3644,0.411,Up,0.5854)
insert into Smarket values(2001,0.411,1.372,0.039,-0.47,1.53,1.2445,-2.382,Down,0.5764)
insert into Smarket values(2001,-2.382,0.411,1.372,0.039,-0.47,1.1061,-1.717,Down,-0.20599999999999996)
insert into Smarket values(2001,-1.717,-2.382,0.411,1.372,0.039,1.2974,-0.001,Down,-0.4553999999999999)
insert into Smarket values(2001,-0.001,-1.717,-2.382,0.411,1.372,1.3525,2.295,Up,-0.46339999999999987)
insert into Smarket values(2001,2.295,-0.001,-1.717,-2.382,0.411,1.3174,0.286,Up,-0.27880000000000005)

insert into Smarket values(2004,-0.416,0.262,-0.133,0.137,0.597,1.1239,0.364,Up,0.08940000000000001)
insert into Smarket values(2004,0.364,-0.416,0.262,-0.133,0.137,1.3823,0.851,Up,0.042800000000000005)
insert into Smarket values(2004,0.851,0.364,-0.416,0.262,-0.133,1.4442,-0.298,Down,0.1856)
insert into Smarket values(2004,-0.298,0.851,0.364,-0.416,0.262,1.3949,-0.545,Down,0.15259999999999999)
insert into Smarket values(2004,-0.545,-0.298,0.851,0.364,-0.416,1.8129,-0.095,Down,-0.008799999999999997)
insert into Smarket values(2004,-0.095,-0.545,-0.298,0.851,0.364,1.3546,0.251,Up,0.055400000000000005)
insert into Smarket values(2004,0.251,-0.095,-0.545,-0.298,0.851,1.375,0.408,Up,0.03279999999999998)
insert into Smarket values(2004,0.408,0.251,-0.095,-0.545,-0.298,1.4738,-1.043,Down,-0.055799999999999995)
insert into Smarket values(2004,-1.043,0.408,0.251,-0.095,-0.545,1.4957,-0.315,Down,-0.2048)
insert into Smarket values(2004,-0.315,-1.043,0.408,0.251,-0.095,1.085,-0.815,Down,-0.1588)
insert into Smarket values(2004,-0.815,-0.315,-1.043,0.408,0.251,1.2833,0.19,Up,-0.30280000000000007)
insert into Smarket values(2004,0.19,-0.815,-0.315,-1.043,0.408,1.3286,-0.824,Down,-0.315)
insert into Smarket values(2004,-0.824,0.19,-0.815,-0.315,-1.043,1.4011,0.334,Up,-0.5613999999999999)
insert into Smarket values(2004,0.334,-0.824,0.19,-0.815,-0.315,1.1863,0.138,Up,-0.2859999999999999)
insert into Smarket values(2004,0.138,0.334,-0.824,0.19,-0.815,1.1146,0.071,Up,-0.19539999999999996)
insert into Smarket values(2004,0.071,0.138,0.334,-0.824,0.19,1.1997,-0.329,Down,-0.018199999999999984)
insert into Smarket values(2004,-0.329,0.071,0.138,0.334,-0.824,1.462,-0.43,Down,-0.12199999999999997)
insert into Smarket values(2004,-0.43,-0.329,0.071,0.138,0.334,1.4087,-0.479,Down,-0.0432)
insert into Smarket values(2004,-0.479,-0.43,-0.329,0.071,0.138,1.4503,-0.044,Down,-0.20579999999999998)
insert into Smarket values(2004,-0.044,-0.479,-0.43,-0.329,0.071,1.3199,0.706,Up,-0.24220000000000003)
insert into Smarket values(2004,0.706,-0.044,-0.479,-0.43,-0.329,1.4458,-1.334,Down,-0.11520000000000001)
insert into Smarket values(2004,-1.334,0.706,-0.044,-0.479,-0.43,1.6795,0.271,Up,-0.31620000000000004)
insert into Smarket values(2004,0.271,-1.334,0.706,-0.044,-0.479,1.6808,-0.97,Down,-0.17600000000000002)
insert into Smarket values(2004,-0.97,0.271,-1.334,0.706,-0.044,1.3375,-0.196,Down,-0.2742)
insert into Smarket values(2004,-0.196,-0.97,0.271,-1.334,0.706,1.4134,0.993,Up,-0.30460000000000004)
insert into Smarket values(2004,0.993,-0.196,-0.97,0.271,-1.334,1.6108,0.054,Up,-0.24720000000000003)
insert into Smarket values(2004,0.054,0.993,-0.196,-0.97,0.271,1.5543,0.457,Up,0.030400000000000003)
insert into Smarket values(2004,0.457,0.054,0.993,-0.196,-0.97,1.5301,0.117,Up,0.06760000000000002)
insert into Smarket values(2004,0.117,0.457,0.054,0.993,-0.196,1.2982,0.445,Up,0.28500000000000003)
insert into Smarket values(2004,0.445,0.117,0.457,0.054,0.993,1.276,-0.626,Down,0.41320000000000007)
insert into Smarket values(2004,-0.626,0.445,0.117,0.457,0.054,1.3383,-0.096,Down,0.08940000000000001)
insert into Smarket values(2004,-0.096,-0.626,0.445,0.117,0.457,1.3692,-1.632,Down,0.05940000000000001)
insert into Smarket values(2004,-1.632,-0.096,-0.626,0.445,0.117,1.3974,-1.548,Down,-0.3584)
insert into Smarket values(2004,-1.548,-1.632,-0.096,-0.626,0.445,1.521,0.117,Up,-0.6914)
insert into Smarket values(2004,0.117,-1.548,-1.632,-0.096,-0.626,1.086,1.297,Up,-0.7569999999999999)
insert into Smarket values(2004,1.297,0.117,-1.548,-1.632,-0.096,1.2456,-0.301,Down,-0.3724)
insert into Smarket values(2004,-0.301,1.297,0.117,-1.548,-1.632,1.4104,-1.168,Down,-0.41340000000000005)
insert into Smarket values(2004,-1.168,-0.301,1.297,0.117,-1.548,1.4051,0.148,Up,-0.3206)
insert into Smarket values(2004,0.148,-1.168,-0.301,1.297,0.117,1.1751,1.366,Up,0.0186)
insert into Smarket values(2004,1.366,0.148,-1.168,-0.301,1.297,1.2062,0.22,Up,0.2684)
insert into Smarket values(2004,0.22,1.366,0.148,-1.168,-0.301,1.2678,1.244,Up,0.05300000000000001)
insert into Smarket values(2004,1.244,0.22,1.366,0.148,-1.168,1.2825,-0.36,Down,0.36200000000000004)
insert into Smarket values(2004,-0.36,1.244,0.22,1.366,0.148,1.2494,0.652,Up,0.5236000000000001)
insert into Smarket values(2004,0.652,-0.36,1.244,0.22,1.366,1.1999,-0.243,Down,0.6244)
insert into Smarket values(2004,-0.243,0.652,-0.36,1.244,0.22,1.0219,0.047,Up,0.30260000000000004)
insert into Smarket values(2004,0.047,-0.243,0.652,-0.36,1.244,1.0925,0.8,Up,0.268)
insert into Smarket values(2004,0.8,0.047,-0.243,0.652,-0.36,1.1922,0.012,Up,0.17920000000000005)
insert into Smarket values(2004,0.012,0.8,0.047,-0.243,0.652,1.0236,0.243,Up,0.25360000000000005)
insert into Smarket values(2004,0.243,0.012,0.8,0.047,-0.243,0.8454,-0.778,Down,0.1718)
insert into Smarket values(2004,-0.778,0.243,0.012,0.8,0.047,0.8431,0.463,Up,0.0648)
insert into Smarket values(2004,0.463,-0.778,0.243,0.012,0.8,1.1382,0.151,Up,0.148)
insert into Smarket values(2004,0.151,0.463,-0.778,0.243,0.012,1.1421,1.121,Up,0.01819999999999999)
insert into Smarket values(2004,1.121,0.151,0.463,-0.778,0.243,1.1184,-0.418,Down,0.24000000000000005)
insert into Smarket values(2004,-0.418,1.121,0.151,0.463,-0.778,0.92417,0.689,Up,0.10780000000000003)
insert into Smarket values(2004,0.689,-0.418,1.121,0.151,0.463,1.2144,-0.449,Down,0.40119999999999995)
insert into Smarket values(2004,-0.449,0.689,-0.418,1.121,0.151,1.2463,0.189,Up,0.21879999999999997)
insert into Smarket values(2004,0.189,-0.449,0.689,-0.418,1.121,1.3713,0.495,Up,0.2264)
insert into Smarket values(2004,0.495,0.189,-0.449,0.689,-0.418,1.2612,0.169,Up,0.1012)
insert into Smarket values(2004,0.169,0.495,0.189,-0.449,0.689,1.2998,0.223,Up,0.2186)
insert into Smarket values(2004,0.223,0.169,0.495,0.189,-0.449,1.2045,-0.705,Down,0.1254)
insert into Smarket values(2004,-0.705,0.223,0.169,0.495,0.189,1.256,0.279,Up,0.07420000000000002)
insert into Smarket values(2004,0.279,-0.705,0.223,0.169,0.495,1.1139,0.449,Up,0.09220000000000002)
insert into Smarket values(2004,0.449,0.279,-0.705,0.223,0.169,1.4226,-0.563,Down,0.083)
insert into Smarket values(2004,-0.563,0.449,0.279,-0.705,0.223,1.1976,0.633,Up,-0.06339999999999997)
insert into Smarket values(2004,0.633,-0.563,0.449,0.279,-0.705,1.325,-1.394,Down,0.01860000000000004)
insert into Smarket values(2004,-1.394,0.633,-0.563,0.449,0.279,1.3799,-0.467,Down,-0.11919999999999994)
insert into Smarket values(2004,-0.467,-1.394,0.633,-0.563,0.449,1.2863,0.158,Up,-0.26839999999999997)
insert into Smarket values(2004,0.158,-0.467,-1.394,0.633,-0.563,1.2554,-0.594,Down,-0.32659999999999995)
insert into Smarket values(2004,-0.594,0.158,-0.467,-1.394,0.633,1.2635,0.593,Up,-0.33279999999999993)
insert into Smarket values(2004,0.593,-0.594,0.158,-0.467,-1.394,1.3966,0.427,Up,-0.3408)
insert into Smarket values(2004,0.427,0.593,-0.594,0.158,-0.467,1.4029,-0.02,Down,0.02340000000000001)
insert into Smarket values(2004,-0.02,0.427,0.593,-0.594,0.158,1.748,1.518,Up,0.11280000000000001)
insert into Smarket values(2004,1.518,-0.02,0.427,0.593,-0.594,1.5822,0.324,Up,0.3848)
insert into Smarket values(2004,0.324,1.518,-0.02,0.427,0.593,1.534,-0.061,Down,0.5684)
insert into Smarket values(2004,-0.061,0.324,1.518,-0.02,0.427,1.4184,0.667,Up,0.43760000000000004)
insert into Smarket values(2004,0.667,-0.061,0.324,1.518,-0.02,1.4167,-0.998,Down,0.4856000000000001)
insert into Smarket values(2004,-0.998,0.667,-0.061,0.324,1.518,1.4475,-0.753,Down,0.29000000000000004)
insert into Smarket values(2004,-0.753,-0.998,0.667,-0.061,0.324,1.2916,0.201,Up,-0.16419999999999996)
insert into Smarket values(2004,0.201,-0.753,-0.998,0.667,-0.061,0.9438,-0.227,Down,-0.1888)
insert into Smarket values(2004,-0.227,0.201,-0.753,-0.998,0.667,1.3201,-0.73,Down,-0.22200000000000003)
insert into Smarket values(2004,-0.73,-0.227,0.201,-0.753,-0.998,1.5462,-0.93,Down,-0.5014)
insert into Smarket values(2004,-0.93,-0.73,-0.227,0.201,-0.753,1.4895,0.445,Up,-0.4878)
insert into Smarket values(2004,0.445,-0.93,-0.73,-0.227,0.201,1.6451,0.525,Up,-0.24820000000000003)
insert into Smarket values(2004,0.525,0.445,-0.93,-0.73,-0.227,1.3733,-0.969,Down,-0.1834)
insert into Smarket values(2004,-0.969,0.525,0.445,-0.93,-0.73,1.7375,0.039,Up,-0.3318)
insert into Smarket values(2004,0.039,-0.969,0.525,0.445,-0.93,1.6857,0.256,Up,-0.178)
insert into Smarket values(2004,0.256,0.039,-0.969,0.525,0.445,1.673,-0.972,Down,0.059200000000000016)
insert into Smarket values(2004,-0.972,0.256,0.039,-0.969,0.525,1.4696,-0.086,Down,-0.2242)
insert into Smarket values(2004,-0.086,-0.972,0.256,0.039,-0.969,1.3805,1.488,Up,-0.3464)
insert into Smarket values(2004,1.488,-0.086,-0.972,0.256,0.039,1.6854,1.288,Up,0.145)
insert into Smarket values(2004,1.288,1.488,-0.086,-0.972,0.256,1.7419,0.181,Up,0.3948)
insert into Smarket values(2004,0.181,1.288,1.488,-0.086,-0.972,1.6282,0.245,Up,0.3798)
insert into Smarket values(2004,0.245,0.181,1.288,1.488,-0.086,1.5008,0.027,Up,0.6232)
insert into Smarket values(2004,0.027,0.245,0.181,1.288,1.488,1.3959,0.004,Up,0.6458)
insert into Smarket values(2004,0.004,0.027,0.245,0.181,1.288,1.659,1.118,Up,0.34900000000000003)
insert into Smarket values(2004,1.118,0.004,0.027,0.245,0.181,1.7675,1.616,Up,0.31500000000000006)
insert into Smarket values(2004,1.616,1.118,0.004,0.027,0.245,1.7827,0.387,Up,0.6020000000000001)
insert into Smarket values(2004,0.387,1.616,1.118,0.004,0.027,1.7244,-0.11,Down,0.6304000000000001)
insert into Smarket values(2004,-0.11,0.387,1.616,1.118,0.004,1.3587,-0.07,Down,0.603)
insert into Smarket values(2004,-0.07,-0.11,0.387,1.616,1.118,1.4508,-0.101,Down,0.5882000000000001)
insert into Smarket values(2004,-0.101,-0.07,-0.11,0.387,1.616,1.5043,0.909,Up,0.3444)
insert into Smarket values(2004,0.909,-0.101,-0.07,-0.11,0.387,1.393,0.911,Up,0.203)
insert into Smarket values(2004,0.911,0.909,-0.101,-0.07,-0.11,1.5316,-0.03,Down,0.30779999999999996)
insert into Smarket values(2004,-0.03,0.911,0.909,-0.101,-0.07,1.4533,-0.708,Down,0.3238)
insert into Smarket values(2004,-0.708,-0.03,0.911,0.909,-0.101,1.3644,0.554,Up,0.1962)
insert into Smarket values(2004,0.554,-0.708,-0.03,0.911,0.909,1.6842,0.136,Up,0.32720000000000005)
insert into Smarket values(2004,0.136,0.554,-0.708,-0.03,0.911,1.4567,-1.116,Down,0.17260000000000003)
insert into Smarket values(2004,-1.116,0.136,0.554,-0.708,-0.03,1.5266,0.59,Up,-0.23279999999999998)
insert into Smarket values(2004,0.59,-1.116,0.136,0.554,-0.708,1.3927,-0.025,Down,-0.10880000000000001)
insert into Smarket values(2004,-0.025,0.59,-1.116,0.136,0.554,1.4283,0.41,Up,0.02779999999999998)
insert into Smarket values(2004,0.41,-0.025,0.59,-1.116,0.136,1.1496,0.075,Up,-0.0010000000000000453)
insert into Smarket values(2004,0.075,0.41,-0.025,0.59,-1.116,0.50458,-0.345,Down,-0.013200000000000055)
insert into Smarket values(2004,-0.345,0.075,0.41,-0.025,0.59,1.3785,-0.403,Down,0.141)
insert into Smarket values(2004,-0.403,-0.345,0.075,0.41,-0.025,1.5535,1.495,Up,-0.05760000000000002)
insert into Smarket values(2004,1.495,-0.403,-0.345,0.075,0.41,1.7728,-0.087,Down,0.2464)
insert into Smarket values(2004,-0.087,1.495,-0.403,-0.345,0.075,1.7749,0.071,Up,0.14700000000000002)
insert into Smarket values(2004,0.071,-0.087,1.495,-0.403,-0.345,1.5667,-0.077,Down,0.14620000000000002)
insert into Smarket values(2004,-0.077,0.071,-0.087,1.495,-0.403,1.3544,-1.107,Down,0.19980000000000003)
insert into Smarket values(2004,-1.107,-0.077,0.071,-0.087,1.495,1.5339,0.488,Up,0.05900000000000003)
insert into Smarket values(2004,0.488,-1.107,-0.077,0.071,-0.087,1.5252,0.544,Up,-0.1424)
insert into Smarket values(2004,0.544,0.488,-1.107,-0.077,0.071,1.6247,-0.104,Down,-0.016199999999999996)
insert into Smarket values(2004,-0.104,0.544,0.488,-1.107,-0.077,1.4437,0.899,Up,-0.05119999999999999)
insert into Smarket values(2004,0.899,-0.104,0.544,0.488,-1.107,1.4361,0.392,Up,0.144)
insert into Smarket values(2004,0.392,0.899,-0.104,0.544,0.488,1.5444,0.194,Up,0.4438)
insert into Smarket values(2004,0.194,0.392,0.899,-0.104,0.544,1.6958,-0.208,Down,0.385)
insert into Smarket values(2004,-0.208,0.194,0.392,0.899,-0.104,1.7939,-0.749,Down,0.2346)
insert into Smarket values(2004,-0.749,-0.208,0.194,0.392,0.899,2.335,0.038,Up,0.10560000000000003)
insert into Smarket values(2004,0.038,-0.749,-0.208,0.194,0.392,1.4228,0.904,Up,-0.06659999999999996)
insert into Smarket values(2004,0.904,0.038,-0.749,-0.208,0.194,1.4837,0.342,Up,0.03580000000000001)
insert into Smarket values(2004,0.342,0.904,0.038,-0.749,-0.208,1.3908,0.046,Up,0.06540000000000001)
insert into Smarket values(2004,0.046,0.342,0.904,0.038,-0.749,0.9561,-0.431,Down,0.11620000000000001)
insert into Smarket values(2004,-0.431,0.046,0.342,0.904,0.038,0.922,0.715,Up,0.17980000000000002)
insert into Smarket values(2004,0.715,-0.431,0.046,0.342,0.904,0.983,-0.007,Down,0.31520000000000004)
insert into Smarket values(2004,-0.007,0.715,-0.431,0.046,0.342,0.9259,0.008,Up,0.133)
insert into Smarket values(2004,0.008,-0.007,0.715,-0.431,0.046,0.8298,-0.134,Down,0.0662)
insert into Smarket values(2005,-0.134,0.008,-0.007,0.715,-0.431,0.7869,-0.812,Down,0.030199999999999994)
insert into Smarket values(2005,-0.812,-0.134,0.008,-0.007,0.715,1.5108,-1.167,Down,-0.04600000000000002)
insert into Smarket values(2005,-1.167,-0.812,-0.134,0.008,-0.007,1.721,-0.363,Down,-0.4224)
insert into Smarket values(2005,-0.363,-1.167,-0.812,-0.134,0.008,1.7389,0.351,Up,-0.4936)
insert into Smarket values(2005,0.351,-0.363,-1.167,-0.812,-0.134,1.5691,-0.143,Down,-0.425)
insert into Smarket values(2005,-0.143,0.351,-0.363,-1.167,-0.812,1.4779,0.342,Up,-0.42680000000000007)
insert into Smarket values(2005,0.342,-0.143,0.351,-0.363,-1.167,1.4904,-0.61,Down,-0.196)
insert into Smarket values(2005,-0.61,0.342,-0.143,0.351,-0.363,1.4888,0.398,Up,-0.08459999999999998)
insert into Smarket values(2005,0.398,-0.61,0.342,-0.143,0.351,1.5621,-0.863,Down,0.06760000000000002)
insert into Smarket values(2005,-0.863,0.398,-0.61,0.342,-0.143,1.5103,0.6,Up,-0.17519999999999997)
insert into Smarket values(2005,0.6,-0.863,0.398,-0.61,0.342,1.3354,0.967,Up,-0.02659999999999999)
insert into Smarket values(2005,0.967,0.6,-0.863,0.398,-0.61,1.5968,-0.949,Down,0.09839999999999997)
insert into Smarket values(2005,-0.949,0.967,0.6,-0.863,0.398,1.4987,-0.778,Down,0.030600000000000006)
insert into Smarket values(2005,-0.778,-0.949,0.967,0.6,-0.863,1.692,-0.641,Down,-0.20459999999999998)
insert into Smarket values(2005,-0.641,-0.778,-0.949,0.967,0.6,1.6435,-0.353,Down,-0.16019999999999995)
insert into Smarket values(2005,-0.353,-0.641,-0.778,-0.949,0.967,1.4946,0.4,Up,-0.3508)
insert into Smarket values(2005,0.4,-0.353,-0.641,-0.778,-0.949,1.6104,0.484,Up,-0.46419999999999995)
insert into Smarket values(2005,0.484,0.4,-0.353,-0.641,-0.778,1.6359,0.041,Up,-0.1776)
insert into Smarket values(2005,0.041,0.484,0.4,-0.353,-0.641,1.6006,-0.272,Down,-0.01379999999999999)
insert into Smarket values(2005,-0.272,0.041,0.484,0.4,-0.353,1.6418,0.846,Up,0.06000000000000001)
insert into Smarket values(2005,0.846,-0.272,0.041,0.484,0.4,1.6798,0.689,Up,0.2998)
insert into Smarket values(2005,0.689,0.846,-0.272,0.041,0.484,1.68198,0.318,Up,0.3576)
insert into Smarket values(2005,0.318,0.689,0.846,-0.272,0.041,1.56174,-0.277,Down,0.3243999999999999)
insert into Smarket values(2005,-0.277,0.318,0.689,0.846,-0.272,1.55446,1.104,Up,0.26080000000000003)
insert into Smarket values(2005,1.104,-0.277,0.318,0.689,0.846,1.64816,-0.109,Down,0.536)
insert into Smarket values(2005,-0.109,1.104,-0.277,0.318,0.689,1.34727,0.048,Up,0.34500000000000003)
insert into Smarket values(2005,0.048,-0.109,1.104,-0.277,0.318,1.41617,-0.858,Down,0.21680000000000002)
insert into Smarket values(2005,-0.858,0.048,-0.109,1.104,-0.277,1.51104,0.421,Up,-0.018399999999999972)
insert into Smarket values(2005,0.421,-0.858,0.048,-0.109,1.104,1.49167,0.693,Up,0.12120000000000002)
insert into Smarket values(2005,0.693,0.421,-0.858,0.048,-0.109,1.5623,0.07,Up,0.03899999999999998)
insert into Smarket values(2005,0.07,0.693,0.421,-0.858,0.048,1.29018,0.33,Up,0.07479999999999999)
insert into Smarket values(2005,0.33,0.07,0.693,0.421,-0.858,1.52708,0.018,Up,0.1312)
insert into Smarket values(2005,0.018,0.33,0.07,0.693,0.421,1.4901,-0.792,Down,0.3064)
insert into Smarket values(2005,-0.792,0.018,0.33,0.07,0.693,1.58012,0.07,Up,0.0638)
insert into Smarket values(2005,0.07,-0.792,0.018,0.33,0.07,1.5512,-1.451,Down,-0.060799999999999986)
insert into Smarket values(2005,-1.451,0.07,-0.792,0.018,0.33,1.74494,0.561,Up,-0.36500000000000005)
insert into Smarket values(2005,0.561,-1.451,0.07,-0.792,0.018,1.50109,0.789,Up,-0.31880000000000003)
insert into Smarket values(2005,0.789,0.561,-1.451,0.07,-0.792,1.51875,0.931,Up,-0.1646)
insert into Smarket values(2005,0.931,0.789,0.561,-1.451,0.07,1.52368,-0.641,Down,0.18000000000000002)
insert into Smarket values(2005,-0.641,0.931,0.789,0.561,-1.451,1.79548,0.566,Up,0.037800000000000014)
insert into Smarket values(2005,0.566,-0.641,0.931,0.789,0.561,1.70806,-0.027,Down,0.4412)
insert into Smarket values(2005,-0.027,0.566,-0.641,0.931,0.789,1.56854,0.032,Up,0.3236)
insert into Smarket values(2005,0.032,-0.027,0.566,-0.641,0.931,1.61624,0.962,Up,0.1722)
insert into Smarket values(2005,0.962,0.032,-0.027,0.566,-0.641,1.63682,0.261,Up,0.17839999999999998)
insert into Smarket values(2005,0.261,0.962,0.032,-0.027,0.566,1.48883,-0.48,Down,0.3588)
insert into Smarket values(2005,-0.48,0.261,0.962,0.032,-0.027,1.52309,-1.019,Down,0.1496)
insert into Smarket values(2005,-1.019,-0.48,0.261,0.962,0.032,1.70497,0.186,Up,-0.0488)
insert into Smarket values(2005,0.186,-1.019,-0.48,0.261,0.962,1.60402,-0.758,Down,-0.018000000000000016)
insert into Smarket values(2005,-0.758,0.186,-1.019,-0.48,0.261,1.44982,0.562,Up,-0.36199999999999993)
insert into Smarket values(2005,0.562,-0.758,0.186,-1.019,-0.48,1.43743,-0.752,Down,-0.30179999999999996)
insert into Smarket values(2005,-0.752,0.562,-0.758,0.186,-1.019,1.51353,-0.808,Down,-0.35619999999999996)
insert into Smarket values(2005,-0.808,-0.752,0.562,-0.758,0.186,1.65319,0.18,Up,-0.314)
insert into Smarket values(2005,0.18,-0.808,-0.752,0.562,-0.758,1.58193,-0.047,Down,-0.31520000000000004)
insert into Smarket values(2005,-0.047,0.18,-0.808,-0.752,0.562,2.34437,-0.493,Down,-0.173)
insert into Smarket values(2005,-0.493,-0.047,0.18,-0.808,-0.752,1.81944,-1.02,Down,-0.384)
insert into Smarket values(2005,-1.02,-0.493,-0.047,0.18,-0.808,2.11447,0.07,Up,-0.43759999999999993)
insert into Smarket values(2005,0.07,-1.02,-0.493,-0.047,0.18,2.24687,-0.095,Down,-0.262)
insert into Smarket values(2005,-0.095,0.07,-1.02,-0.493,-0.047,1.72172,0.244,Up,-0.31699999999999995)
insert into Smarket values(2005,0.244,-0.095,0.07,-1.02,-0.493,1.74622,-0.76,Down,-0.25880000000000003)
insert into Smarket values(2005,-0.76,0.244,-0.095,0.07,-1.02,2.22325,1.377,Up,-0.3122)
insert into Smarket values(2005,1.377,-0.76,0.244,-0.095,0.07,2.09711,-0.069,Down,0.16720000000000002)
insert into Smarket values(2005,-0.069,1.377,-0.76,0.244,-0.095,2.21423,-0.65,Down,0.13940000000000002)
insert into Smarket values(2005,-0.65,-0.069,1.377,-0.76,0.244,2.16869,0.273,Up,0.02839999999999998)
insert into Smarket values(2005,0.273,-0.65,-0.069,1.377,-0.76,2.07977,0.448,Up,0.03420000000000001)
insert into Smarket values(2005,0.448,0.273,-0.65,-0.069,1.377,1.8708,0.227,Up,0.2758)
insert into Smarket values(2005,0.227,0.448,0.273,-0.65,-0.069,1.7974,0.597,Up,0.04580000000000001)
insert into Smarket values(2005,0.597,0.227,0.448,0.273,-0.65,1.90062,-0.834,Down,0.179)
insert into Smarket values(2005,-0.834,0.597,0.227,0.448,0.273,1.66133,0.001,Up,0.14220000000000002)
insert into Smarket values(2005,0.001,-0.834,0.597,0.227,0.448,1.52531,0.555,Up,0.08780000000000002)
insert into Smarket values(2005,0.555,0.001,-0.834,0.597,0.227,1.97983,-1.176,Down,0.1092)

In [69]:
df.head()

,Year,Lag1,Lag2,Lag3,Lag4,Lag5,Volume,Today,Direction,average_Lag
0,2001,0.381,-0.192,-2.624,-1.055,5.010,1.1913,0.959,Up,0.3040
1,2001,0.959,0.381,-0.192,-2.624,-1.055,1.2965,1.032,Up,-0.5062
2,2001,1.032,0.959,0.381,-0.192,-2.624,1.4112,-0.623,Down,-0.0888
3,2001,-0.623,1.032,0.959,0.381,-0.192,1.2760,0.614,Up,0.3114
4,2001,0.614,-0.623,1.032,0.959,0.381,1.2057,0.213,Up,0.4726

In [75]:
len(df.columns)

10

In [127]:
for i,row in df.iterrows():
            print(tuple(row))
            
            sql = "INSERT INTO Smarket VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"
            cursor.execute(sql,list(row))
            print("Record inserted")
            
            connection.commit()

(2001, 0.381, -0.192, -2.624, -1.055, 5.01, 1.1913, 0.959, 'Up', 0.30399999999999994)
Record inserted
(2001, 0.959, 0.381, -0.192, -2.624, -1.055, 1.2965, 1.032, 'Up', -0.5062)
Record inserted
(2001, 1.032, 0.959, 0.381, -0.192, -2.624, 1.4112, -0.623, 'Down', -0.08880000000000007)
Record inserted
(2001, -0.623, 1.032, 0.959, 0.381, -0.192, 1.276, 0.614, 'Up', 0.3114)
Record inserted
(2001, 0.614, -0.623, 1.032, 0.959, 0.381, 1.2057, 0.213, 'Up', 0.4726000000000001)
Record inserted
(2001, 0.213, 0.614, -0.623, 1.032, 0.959, 1.3491, 1.392, 'Up', 0.43899999999999995)
Record inserted
(2001, 1.392, 0.213, 0.614, -0.623, 1.032, 1.445, -0.403, 'Down', 0.5256000000000001)
Record inserted
(2001, -0.403, 1.392, 0.213, 0.614, -0.623, 1.4078, 0.027, 'Up', 0.23859999999999998)
Record inserted
(2001, 0.027, -0.403, 1.392, 0.213, 0.614, 1.164, 1.303, 'Up', 0.3686)
Record inserted
(2001, 1.303, 0.027, -0.403, 1.392, 0.213, 1.2326, 0.287, 'Up', 0.5064)
Record inserted
(2001, 0.287, 1.303, 0.027, -0.403, 1.392, 1.309, -0.498, 'Down', 0.5212)
Record inserted
(2001, -0.498, 0.287, 1.303, 0.027, -0.403, 1.258, -0.189, 'Down', 0.14319999999999994)
Record inserted
(2001, -0.189, -0.498, 0.287, 1.303, 0.027, 1.098, 0.68, 'Up', 0.18599999999999997)
Record inserted
(2001, 0.68, -0.189, -0.498, 0.287, 1.303, 1.0531, 0.701, 'Up', 0.3166)
Record inserted
(2001, 0.701, 0.68, -0.189, -0.498, 0.287, 1.1498, -0.562, 'Down', 0.19619999999999999)
Record inserted
(2001, -0.562, 0.701, 0.68, -0.189, -0.498, 1.2953, 0.546, 'Up', 0.02639999999999998)
Record inserted
(2001, 0.546, -0.562, 0.701, 0.68, -0.189, 1.1188, -1.747, 'Down', 0.2352)
Record inserted
(2001, -1.747, 0.546, -0.562, 0.701, 0.68, 1.0484, 0.359, 'Up', -0.07640000000000005)
Record inserted
(2001, 0.359, -1.747, 0.546, -0.562, 0.701, 1.013, -0.151, 'Down', -0.14060000000000003)
Record inserted
(2001, -0.151, 0.359, -1.747, 0.546, -0.562, 1.0596, -0.841, 'Down', -0.31100000000000005)
Record inserted
(2001, -0.841, -0.151, 0.359, -1.747, 0.546, 1.1583, -0.623, 'Down', -0.36679999999999996)
Record inserted
(2001, -0.623, -0.841, -0.151, 0.359, -1.747, 1.1072, -1.334, 'Down', -0.6006)
Record inserted
(2001, -1.334, -0.623, -0.841, -0.151, 0.359, 1.0755, 1.183, 'Up', -0.518)
Record inserted
(2001, 1.183, -1.334, -0.623, -0.841, -0.151, 1.0391, -0.865, 'Down', -0.3532)
Record inserted
(2001, -0.865, 1.183, -1.334, -0.623, -0.841, 1.0752, -0.218, 'Down', -0.496)
Record inserted
(2001, -0.218, -0.865, 1.183, -1.334, -0.623, 1.1503, 0.812, 'Up', -0.3714)
Record inserted
(2001, 0.812, -0.218, -0.865, 1.183, -1.334, 1.1537, -1.891, 'Down', -0.08439999999999999)
Record inserted
(2001, -1.891, 0.812, -0.218, -0.865, 1.183, 1.2572, -1.736, 'Down', -0.19579999999999997)
Record inserted
(2001, -1.736, -1.891, 0.812, -0.218, -0.865, 1.1122, -1.851, 'Down', -0.7796)
Record inserted
(2001, -1.851, -1.736, -1.891, 0.812, -0.218, 1.2085, -0.195, 'Down', -0.9767999999999999)
Record inserted
(2001, -0.195, -1.851, -1.736, -1.891, 0.812, 1.3659, -0.556, 'Down', -0.9722)
Record inserted
(2001, -0.556, -0.195, -1.851, -1.736, -1.891, 1.2313, 1.749, 'Up', -1.2458)
Record inserted
(2001, 1.749, -0.556, -0.195, -1.851, -1.736, 1.1308, -0.766, 'Down', -0.5178)
Record inserted
(2001, -0.766, 1.749, -0.556, -0.195, -1.851, 1.1141, -1.431, 'Down', -0.3238)
Record inserted
(2001, -1.431, -0.766, 1.749, -0.556, -0.195, 1.2253, 0.104, 'Up', -0.2398)
Record inserted
(2001, 0.104, -1.431, -0.766, 1.749, -0.556, 1.2949, -0.568, 'Down', -0.18)
Record inserted
(2001, -0.568, 0.104, -1.431, -0.766, 1.749, 1.294, 0.586, 'Up', -0.18239999999999998)
Record inserted
(2001, 0.586, -0.568, 0.104, -1.431, -0.766, 0.9292, 0.998, 'Up', -0.41500000000000004)
Record inserted
(2001, 0.998, 0.586, -0.568, 0.104, -1.431, 1.0918, 0.645, 'Up', -0.06219999999999999)
Record inserted
(2001, 0.645, 0.998, 0.586, -0.568, 0.104, 1.1322, 0.226, 'Up', 0.35300000000000004)
Record inserted
(2001, 0.226, 0.645, 0.998, 0.586, -0.568, 1.1141, -2.476, 'Down', 0.3774)
Record inserted
(2001, -2.476, 0.226, 0.645, 0.998, 0.586, 1.0859, -4.318, 'Down', -0.004200000000000004)
Record inserted
(2001, -4.318, -2.476, 0.226, 0.645, 0.998, 1.229, 1.483, 'Up', -0.985)
Record inserted
(2001, 1.483, -4.318, -2.476, 0.226, 0.645, 1.3609, -2.584, 'Down', -0.8879999999999999)
Record inserted
(2001, -2.584, 1.483, -4.318, -2.476, 0.226, 1.3974, 0.587, 'Up', -1.5337999999999998)
Record inserted
(2001, 0.587, -2.584, 1.483, -4.318, -2.476, 1.2595, -1.962, 'Down', -1.4616)
Record inserted
(2001, -1.962, 0.587, -2.584, 1.483, -4.318, 1.54356, 1.763, 'Up', -1.3588)
Record inserted
(2001, 1.763, -1.962, 0.587, -2.584, 1.483, 1.1262, -2.408, 'Down', -0.1426)
Record inserted
(2001, -2.408, 1.763, -1.962, 0.587, -2.584, 1.2359, -1.792, 'Down', -0.9208000000000002)
Record inserted
(2001, -1.792, -2.408, 1.763, -1.962, 0.587, 1.3463, -0.406, 'Down', -0.7624000000000001)
Record inserted
(2001, -0.406, -1.792, -2.408, 1.763, -1.962, 1.72395, 1.991, 'Up', -0.961)
Record inserted
(2001, 1.991, -0.406, -1.792, -2.408, 1.763, 1.3649, 1.128, 'Up', -0.17040000000000005)
Record inserted
(2001, 1.128, 1.991, -0.406, -1.792, -2.408, 1.114, 2.557, 'Up', -0.29740000000000005)
Record inserted
(2001, 2.557, 1.128, 1.991, -0.406, -1.792, 1.3142, -2.443, 'Down', 0.6956000000000001)
Record inserted
(2001, -2.443, 2.557, 1.128, 1.991, -0.406, 1.3334, -0.463, 'Down', 0.5653999999999999)
Record inserted
(2001, -0.463, -2.443, 2.557, 1.128, 1.991, 1.2345, 1.078, 'Up', 0.5539999999999999)
Record inserted
(2001, 1.078, -0.463, -2.443, 2.557, 1.128, 1.2808, -1.246, 'Down', 0.37139999999999995)
Record inserted
(2001, -1.246, 1.078, -0.463, -2.443, 2.557, 1.2549, -3.439, 'Down', -0.10339999999999998)
Record inserted
(2001, -3.439, -1.246, 1.078, -0.463, -2.443, 1.3861, -0.29, 'Down', -1.3026)
Record inserted
(2001, -0.29, -3.439, -1.246, 1.078, -0.463, 1.42559, 4.368, 'Up', -0.8719999999999999)
Record inserted
(2001, 4.368, -0.29, -3.439, -1.246, 1.078, 1.368, -1.998, 'Down', 0.09420000000000006)
Record inserted
(2001, -1.998, 4.368, -0.29, -3.439, -1.246, 1.2668, 0.812, 'Up', -0.521)
Record inserted
(2001, 0.812, -1.998, 4.368, -0.29, -3.439, 1.0628, 2.707, 'Up', -0.10939999999999994)
Record inserted
(2001, 2.707, 0.812, -1.998, 4.368, -0.29, 1.3496, -0.213, 'Down', 1.1198000000000001)
Record inserted
(2001, -0.213, 2.707, 0.812, -1.998, 4.368, 1.2903, 1.51, 'Up', 1.1352)
Record inserted
(2001, 1.51, -0.213, 2.707, 0.812, -1.998, 1.102, -0.323, 'Down', 0.5635999999999999)
Record inserted
(2001, -0.323, 1.51, -0.213, 2.707, 0.812, 0.9139, 1.028, 'Up', 0.8986000000000001)
Record inserted
(2001, 1.028, -0.323, 1.51, -0.213, 2.707, 1.1096, 3.889, 'Up', 0.9418)
Record inserted
(2001, 3.889, 1.028, -0.323, 1.51, -0.213, 1.9189, 1.254, 'Up', 1.1782)
Record inserted
(2001, 1.254, 3.889, 1.028, -0.323, 1.51, 1.4868, -0.854, 'Down', 1.4715999999999998)
Record inserted
(2001, -0.854, 1.254, 3.889, 1.028, -0.323, 1.3387, -1.498, 'Down', 0.9987999999999999)
Record inserted
(2001, -1.498, -0.854, 1.254, 3.889, 1.028, 1.0126, -1.216, 'Down', 0.7638)
Record inserted
(2001, -1.216, -1.498, -0.854, 1.254, 3.889, 1.2165, 1.594, 'Up', 0.31499999999999995)
Record inserted
(2001, 1.594, -1.216, -1.498, -0.854, 1.254, 1.2036, 0.47, 'Up', -0.14399999999999996)
Record inserted
(2001, 0.47, 1.594, -1.216, -1.498, -0.854, 1.3452, 1.501, 'Up', -0.3008)
Record inserted
(2001, 1.501, 0.47, 1.594, -1.216, -1.498, 1.0913, -0.287, 'Down', 0.17020000000000005)
Record inserted
(2001, -0.287, 1.501, 0.47, 1.594, -1.216, 1.2668, 1.359, 'Up', 0.41240000000000004)
Record inserted
(2001, 1.359, -0.287, 1.501, 0.47, 1.594, 1.1813, 0.078, 'Up', 0.9274000000000001)
Record inserted
(2001, 0.078, 1.359, -0.287, 1.501, 0.47, 1.3422, -1.487, 'Down', 0.6241999999999999)
Record inserted
(2001, -1.487, 0.078, 1.359, -0.287, 1.501, 1.1379, 1.444, 'Up', 0.23279999999999998)
Record inserted
(2001, 1.444, -1.487, 0.078, 1.359, -0.287, 1.0821, -0.245, 'Down', 0.22139999999999999)
Record inserted
(2001, -0.245, 1.444, -1.487, 0.078, 1.359, 0.949, -0.183, 'Down', 0.22979999999999995)
Record inserted
(2001, -0.183, -0.245, 1.444, -1.487, 0.078, 1.0063, -0.449, 'Down', -0.07860000000000002)
Record inserted
(2001, -0.449, -0.183, -0.245, 1.444, -1.487, 1.1324, -0.029, 'Down', -0.18400000000000002)
Record inserted
(2001, -0.029, -0.449, -0.183, -0.245, 1.444, 1.0567, -0.758, 'Down', 0.10759999999999999)
Record inserted
(2001, -0.758, -0.029, -0.449, -0.183, -0.245, 0.9062, 0.261, 'Up', -0.33280000000000004)
Record inserted
(2001, 0.261, -0.758, -0.029, -0.449, -0.183, 0.8582, 0.042, 'Up', -0.23160000000000003)
Record inserted
(2001, 0.042, 0.261, -0.758, -0.029, -0.449, 1.0718, 2.845, 'Up', -0.18660000000000002)
Record inserted
(2001, 2.845, 0.042, 0.261, -0.758, -0.029, 1.4053, 0.272, 'Up', 0.47220000000000006)
Record inserted
(2001, 0.272, 2.845, 0.042, 0.261, -0.758, 1.3556, 0.269, 'Up', 0.5324)
Record inserted
(2001, 0.269, 0.272, 2.845, 0.042, 0.261, 1.1308, 1.615, 'Up', 0.7378)
Record inserted
(2001, 1.615, 0.269, 0.272, 2.845, 0.042, 1.1749, -0.263, 'Down', 1.0086)
Record inserted
(2001, -0.263, 1.615, 0.269, 0.272, 2.845, 1.2604, -1.553, 'Down', 0.9476000000000001)
Record inserted
(2001, -1.553, -0.263, 1.615, 0.269, 0.272, 1.1348, 0.32, 'Up', 0.06800000000000003)
Record inserted
(2001, 0.32, -1.553, -0.263, 1.615, 0.269, 1.1007, -1.182, 'Down', 0.0776)
Record inserted
(2001, -1.182, 0.32, -1.553, -0.263, 1.615, 0.8281, -0.779, 'Down', -0.21259999999999998)
Record inserted
(2001, -0.779, -1.182, 0.32, -1.553, -0.263, 1.026, -1.566, 'Down', -0.6914)
Record inserted
(2001, -1.566, -0.779, -1.182, 0.32, -1.553, 1.1586, 0.62, 'Up', -0.952)
Record inserted
(2001, 0.62, -1.566, -0.779, -1.182, 0.32, 1.2266, 0.386, 'Up', -0.5174000000000001)
Record inserted
(2001, 0.386, 0.62, -1.566, -0.779, -1.182, 1.015, 0.511, 'Up', -0.5042)
Record inserted
(2001, 0.511, 0.386, 0.62, -1.566, -0.779, 0.8365, 1.299, 'Up', -0.16560000000000002)
Record inserted
(2001, 1.299, 0.511, 0.386, 0.62, -1.566, 1.1168, -1.055, 'Down', 0.25000000000000006)
Record inserted
(2001, -1.055, 1.299, 0.511, 0.386, 0.62, 1.0619, 0.546, 'Up', 0.3522)
Record inserted
(2001, 0.546, -1.055, 1.299, 0.511, 0.386, 1.0896, -0.94, 'Down', 0.33740000000000003)
Record inserted
(2001, -0.94, 0.546, -1.055, 1.299, 0.511, 0.7262, -0.836, 'Down', 0.07220000000000001)
Record inserted
(2001, -0.836, -0.94, 0.546, -1.055, 1.299, 0.8701, 0.116, 'Up', -0.19719999999999996)
Record inserted
(2001, 0.116, -0.836, -0.94, 0.546, -1.055, 1.1365, -1.135, 'Down', -0.4337999999999999)
Record inserted

(2001, -1.135, 0.116, -0.836, -0.94, 0.546, 1.0636, -1.75, 'Down', -0.4497999999999999)
Record inserted
(2001, -1.75, -1.135, 0.116, -0.836, -0.94, 1.2429, -0.452, 'Down', -0.909)
Record inserted
(2001, -0.452, -1.75, -1.135, 0.116, -0.836, 1.63555, -0.488, 'Down', -0.8113999999999999)
Record inserted
(2001, -0.488, -0.452, -1.75, -1.135, 0.116, 1.1116, 0.343, 'Up', -0.7418)
Record inserted
(2001, 0.343, -0.488, -0.452, -1.75, -1.135, 1.1849, 0.871, 'Up', -0.6964)
Record inserted
(2001, 0.871, 0.343, -0.488, -0.452, -1.75, 1.3501, 1.136, 'Up', -0.2952)
Record inserted
(2001, 1.136, 0.871, 0.343, -0.488, -0.452, 1.54682, -0.945, 'Down', 0.2819999999999999)
Record inserted
(2001, -0.945, 1.136, 0.871, 0.343, -0.488, 1.1892, -0.551, 'Down', 0.18339999999999995)
Record inserted
(2001, -0.551, -0.945, 1.136, 0.871, 0.343, 1.0501, -0.151, 'Down', 0.17079999999999998)
Record inserted
(2001, -0.151, -0.551, -0.945, 1.136, 0.871, 1.1989, -0.468, 'Down', 0.07199999999999998)
Record inserted
(2001, -0.468, -0.151, -0.551, -0.945, 1.136, 1.1621, 1.249, 'Up', -0.19579999999999997)
Record inserted
(2001, 1.249, -0.468, -0.151, -0.551, -0.945, 1.3273, -0.148, 'Down', -0.17319999999999997)
Record inserted
(2001, -0.148, 1.249, -0.468, -0.151, -0.551, 1.83236, 1.008, 'Up', -0.013799999999999969)
Record inserted
(2001, 1.008, -0.148, 1.249, -0.468, -0.151, 1.1283, -0.184, 'Down', 0.298)
Record inserted
(2001, -0.184, 1.008, -0.148, 1.249, -0.468, 0.62211, -1.232, 'Down', 0.29140000000000005)
Record inserted
(2001, -1.232, -0.184, 1.008, -0.148, 1.249, 0.9349, -2.35, 'Down', 0.13860000000000003)
Record inserted
(2001, -2.35, -1.232, -0.184, 1.008, -0.148, 1.0567, 0.688, 'Up', -0.5812)
Record inserted
(2001, 0.688, -2.35, -1.232, -0.184, 1.008, 1.0457, -1.44, 'Down', -0.41400000000000003)
Record inserted
(2001, -1.44, 0.688, -2.35, -1.232, -0.184, 1.2638, -0.113, 'Down', -0.9036000000000002)
Record inserted
(2001, -0.113, -1.44, 0.688, -2.35, -1.232, 1.3841, 2.369, 'Up', -0.8894)
Record inserted
(2001, 2.369, -0.113, -1.44, 0.688, -2.35, 1.394, 0.624, 'Up', -0.16919999999999996)
Record inserted
(2001, 0.624, 2.369, -0.113, -1.44, 0.688, 1.1217, -1.088, 'Down', 0.42560000000000003)
Record inserted
(2001, -1.088, 0.624, 2.369, -0.113, -1.44, 1.0398, 0.997, 'Up', 0.07040000000000006)
Record inserted
(2001, 0.997, -1.088, 0.624, 2.369, -0.113, 1.2381, -0.554, 'Down', 0.5578000000000001)
Record inserted
(2001, -0.554, 0.997, -1.088, 0.624, 2.369, 1.3163, 0.605, 'Up', 0.46959999999999996)
Record inserted
(2001, 0.605, -0.554, 0.997, -1.088, 0.624, 1.3435, -0.343, 'Down', 0.11679999999999999)
Record inserted
(2001, -0.343, 0.605, -0.554, 0.997, -1.088, 1.1709, -1.637, 'Down', -0.07660000000000004)
Record inserted
(2001, -1.637, -0.343, 0.605, -0.554, 0.997, 0.9869, -1.627, 'Down', -0.1864)
Record inserted
(2001, -1.627, -1.637, -0.343, 0.605, -0.554, 1.1987, 1.608, 'Up', -0.7112)
Record inserted
(2001, 1.608, -1.627, -1.637, -0.343, 0.605, 1.2807, 1.045, 'Up', -0.2788)
Record inserted
(2001, 1.045, 1.608, -1.627, -1.637, -0.343, 1.2139, 0.24, 'Up', -0.1908)
Record inserted
(2001, 0.24, 1.045, 1.608, -1.627, -1.637, 1.0153, -0.108, 'Down', -0.07420000000000004)
Record inserted
(2001, -0.108, 0.24, 1.045, 1.608, -1.627, 0.9091, 0.557, 'Up', 0.23160000000000003)
Record inserted
(2001, 0.557, -0.108, 0.24, 1.045, 1.608, 1.1292, 0.388, 'Up', 0.6684)
Record inserted
(2001, 0.388, 0.557, -0.108, 0.24, 1.045, 1.3403, 0.396, 'Up', 0.4244)
Record inserted
(2001, 0.396, 0.388, 0.557, -0.108, 0.24, 1.2183, -0.524, 'Down', 0.29460000000000003)
Record inserted
(2001, -0.524, 0.396, 0.388, 0.557, -0.108, 0.9399, -1.142, 'Down', 0.1418)
Record inserted
(2001, -1.142, -0.524, 0.396, 0.388, 0.557, 0.8117, 0.327, 'Up', -0.06499999999999999)
Record inserted
(2001, 0.327, -1.142, -0.524, 0.396, 0.388, 1.012, -1.733, 'Down', -0.11099999999999999)
Record inserted
(2001, -1.733, 0.327, -1.142, -0.524, 0.396, 1.1246, -0.008, 'Down', -0.5352)
Record inserted
(2001, -0.008, -1.733, 0.327, -1.142, -0.524, 1.1042, 0.569, 'Up', -0.616)
Record inserted
(2001, 0.569, -0.008, -1.733, 0.327, -1.142, 0.9609, 0.095, 'Up', -0.39740000000000003)
Record inserted
(2001, 0.095, 0.569, -0.008, -1.733, 0.327, 0.8376, -0.383, 'Down', -0.15000000000000005)
Record inserted
(2001, -0.383, 0.095, 0.569, -0.008, -1.733, 0.9646, -0.734, 'Down', -0.29200000000000004)
Record inserted
(2001, -0.734, -0.383, 0.095, 0.569, -0.008, 1.0656, 0.309, 'Up', -0.09220000000000002)
Record inserted
(2001, 0.309, -0.734, -0.383, 0.095, 0.569, 1.0554, -1.666, 'Down', -0.028800000000000027)
Record inserted
(2001, -1.666, 0.309, -0.734, -0.383, 0.095, 0.9743, 0.812, 'Up', -0.4758)
Record inserted
(2001, 0.812, -1.666, 0.309, -0.734, -0.383, 0.8971, -1.208, 'Down', -0.3324)
Record inserted
(2001, -1.208, 0.812, -1.666, 0.309, -0.734, 1.0416, 0.696, 'Up', -0.4974)
Record inserted
(2001, 0.696, -1.208, 0.812, -1.666, 0.309, 1.1108, -0.276, 'Down', -0.21139999999999998)
Record inserted
(2001, -0.276, 0.696, -1.208, 0.812, -1.666, 0.9862, 1.965, 'Up', -0.32839999999999997)
Record inserted
(2001, 1.965, -0.276, 0.696, -1.208, 0.812, 1.0436, -0.483, 'Down', 0.3978)
Record inserted
(2001, -0.483, 1.965, -0.276, 0.696, -1.208, 0.8426, -1.501, 'Down', 0.13880000000000003)
Record inserted
(2001, -1.501, -0.483, 1.965, -0.276, 0.696, 0.9871, -1.115, 'Down', 0.08020000000000001)
Record inserted
(2001, -1.115, -1.501, -0.483, 1.965, -0.276, 0.9637, -1.7, 'Down', -0.2819999999999999)
Record inserted
(2001, -1.7, -1.115, -1.501, -0.483, 1.965, 1.157, 0.403, 'Up', -0.5668)
Record inserted
(2001, 0.403, -1.7, -1.115, -1.501, -0.483, 0.9201, -0.056, 'Down', -0.8792)
Record inserted
(2001, -0.056, 0.403, -1.7, -1.115, -1.501, 1.1783, -0.106, 'Down', -0.7938)
Record inserted
(2001, -0.106, -0.056, 0.403, -1.7, -1.115, 1.3845, -2.239, 'Down', -0.5147999999999999)
Record inserted
(2001, -2.239, -0.106, -0.056, 0.403, -1.7, 1.3597, -1.864, 'Down', -0.7395999999999999)
Record inserted
(2001, -1.864, -2.239, -0.106, -0.056, 0.403, 1.4243, 0.623, 'Up', -0.7724)
Record inserted
(2001, 0.623, -1.864, -2.239, -0.106, -0.056, 1.2766, -4.922, 'Down', -0.7283999999999999)
Record inserted
(2001, -4.922, 0.623, -1.864, -2.239, -0.106, 2.33083, -0.58, 'Down', -1.7015999999999998)
Record inserted
(2001, -0.58, -4.922, 0.623, -1.864, -2.239, 1.65041, -1.611, 'Down', -1.7963999999999998)
Record inserted
(2001, -1.611, -0.58, -4.922, 0.623, -1.864, 2.12055, -3.106, 'Down', -1.6707999999999998)
Record inserted
(2001, -3.106, -1.611, -0.58, -4.922, 0.623, 2.0048, -1.903, 'Down', -1.9192)
Record inserted
(2001, -1.903, -3.106, -1.611, -0.58, -4.922, 2.3173, 3.898, 'Up', -2.4244)
Record inserted
(2001, 3.898, -1.903, -3.106, -1.611, -0.58, 1.7466, 0.879, 'Up', -0.6603999999999999)
Record inserted
(2001, 0.879, 3.898, -1.903, -3.106, -1.611, 1.6138, -0.517, 'Down', -0.3685999999999999)
Record inserted
(2001, -0.517, 0.879, 3.898, -1.903, -3.106, 1.5191, 1.149, 'Up', -0.14980000000000002)
Record inserted
(2001, 1.149, -0.517, 0.879, 3.898, -1.903, 1.467, 2.192, 'Up', 0.7012000000000002)
Record inserted
(2001, 2.192, 1.149, -0.517, 0.879, 3.898, 1.6315, -0.23, 'Down', 1.5202000000000002)
Record inserted
(2001, -0.23, 2.192, 1.149, -0.517, 0.879, 1.1756, 1.231, 'Up', 0.6946000000000001)
Record inserted
(2001, 1.231, -0.23, 2.192, 1.149, -0.517, 1.2898, 1.993, 'Up', 0.7650000000000001)
Record inserted
(2001, 1.993, 1.231, -0.23, 2.192, 1.149, 1.6506, -0.247, 'Down', 1.267)
Record inserted
(2001, -0.247, 1.993, 1.231, -0.23, 2.192, 1.6091, 0.164, 'Up', 0.9878)
Record inserted
(2001, 0.164, -0.247, 1.993, 1.231, -0.23, 1.3017, -0.834, 'Down', 0.5822)
Record inserted
(2001, -0.834, 0.164, -0.247, 1.993, 1.231, 0.979, -0.536, 'Down', 0.4614000000000001)
Record inserted
(2001, -0.536, -0.834, 0.164, -0.247, 1.993, 1.2278, 2.294, 'Up', 0.10799999999999996)
Record inserted
(2001, 2.294, -0.536, -0.834, 0.164, -0.247, 1.3124, 1.521, 'Up', 0.16820000000000002)
Record inserted
(2001, 1.521, 2.294, -0.536, -0.834, 0.164, 1.70458, -0.527, 'Down', 0.5218)
Record inserted
(2001, -0.527, 1.521, 2.294, -0.536, -0.834, 1.3314, -0.153, 'Down', 0.38359999999999994)
Record inserted
(2001, -0.153, -0.527, 1.521, 2.294, -0.536, 1.0247, 0.694, 'Up', 0.5197999999999999)
Record inserted
(2001, 0.694, -0.153, -0.527, 1.521, 2.294, 1.2105, -1.863, 'Down', 0.7657999999999999)
Record inserted
(2001, -1.863, 0.694, -0.153, -0.527, 1.521, 1.4522, -0.787, 'Down', -0.06560000000000006)
Record inserted
(2001, -0.787, -1.863, 0.694, -0.153, -0.527, 1.2629, 0.456, 'Up', -0.5272)
Record inserted
(2001, 0.456, -0.787, -1.863, 0.694, -0.153, 1.2949, 1.53, 'Up', -0.3306)
Record inserted
(2001, 1.53, 0.456, -0.787, -1.863, 0.694, 1.1057, -0.47, 'Down', 0.005999999999999961)
Record inserted
(2001, -0.47, 1.53, 0.456, -0.787, -1.863, 1.3173, 0.039, 'Up', -0.22679999999999997)
Record inserted
(2001, 0.039, -0.47, 1.53, 0.456, -0.787, 1.3362, 1.372, 'Up', 0.1536)
Record inserted
(2001, 1.372, 0.039, -0.47, 1.53, 0.456, 1.3644, 0.411, 'Up', 0.5854)
Record inserted
(2001, 0.411, 1.372, 0.039, -0.47, 1.53, 1.2445, -2.382, 'Down', 0.5764)
Record inserted
(2001, -2.382, 0.411, 1.372, 0.039, -0.47, 1.1061, -1.717, 'Down', -0.20599999999999996)
Record inserted
(2001, -1.717, -2.382, 0.411, 1.372, 0.039, 1.2974, -0.001, 'Down', -0.4553999999999999)
Record inserted
(2001, -0.001, -1.717, -2.382, 0.411, 1.372, 1.3525, 2.295, 'Up', -0.46339999999999987)
Record inserted
(2001, 2.295, -0.001, -1.717, -2.382, 0.411, 1.3174, 0.286, 'Up', -0.27880000000000005)
Record inserted
(2001, 0.286, 2.295, -0.001, -1.717, -2.382, 1.1219, 1.439, 'Up', -0.3038)
Record inserted
(2001, 1.439, 0.286, 2.295, -0.001, -1.717, 1.2677, 1.453, 'Up', 0.4603999999999998)
Record inserted
(2001, 1.453, 1.439, 0.286, 2.295, -0.001, 1.356, -0.273, 'Down', 1.0944)
Record inserted
(2001, -0.273, 1.453, 1.439, 0.286, 2.295, 1.4113, 0.246, 'Up', 1.04)
Record inserted
(2001, 0.246, -0.273, 1.453, 1.439, 0.286, 1.5175, 0.158, 'Up', 0.6302000000000001)
Record inserted
(2001, 0.158, 0.246, -0.273, 1.453, 1.439, 1.0938, -0.177, 'Down', 0.6046)
Record inserted
(2001, -0.177, 0.158, 0.246, -0.273, 1.453, 0.9916, 1.856, 'Up', 0.2814)
Record inserted
(2001, 1.856, -0.177, 0.158, 0.246, -0.273, 1.3701, 0.186, 'Up', 0.362)
Record inserted
(2001, 0.186, 1.856, -0.177, 0.158, 0.246, 1.4434, 0.09, 'Up', 0.45380000000000004)
Record inserted
(2001, 0.09, 0.186, 1.856, -0.177, 0.158, 1.4545, -0.314, 'Down', 0.4226)
Record inserted
(2001, -0.314, 0.09, 0.186, 1.856, -0.177, 1.3374, 1.09, 'Up', 0.3282)
Record inserted
(2001, 1.09, -0.314, 0.09, 0.186, 1.856, 1.3168, -0.73, 'Down', 0.5816000000000001)
Record inserted
(2001, -0.73, 1.09, -0.314, 0.09, 0.186, 1.3302, -0.493, 'Down', 0.06440000000000001)
Record inserted
(2001, -0.493, -0.73, 1.09, -0.314, 0.09, 1.0293, 1.171, 'Up', -0.07139999999999995)
Record inserted
(2001, 1.171, -0.493, -0.73, 1.09, -0.314, 0.4103, 0.615, 'Up', 0.14480000000000004)

Record inserted
(2001, 0.615, 1.171, -0.493, -0.73, 1.09, 1.1298, -0.684, 'Down', 0.33060000000000006)
Record inserted
(2001, -0.684, 0.615, 1.171, -0.493, -0.73, 1.288, -1.825, 'Down', -0.02420000000000002)
Record inserted
(2001, -1.825, -0.684, 0.615, 1.171, -0.493, 1.4237, 1.035, 'Up', -0.24319999999999994)
Record inserted
(2001, 1.035, -1.825, -0.684, 0.615, 1.171, 1.3757, -0.066, 'Down', 0.06239999999999997)
Record inserted
(2001, -0.066, 1.035, -1.825, -0.684, 0.615, 1.3436, -0.838, 'Down', -0.185)
Record inserted
(2001, -0.838, -0.066, 1.035, -1.825, -0.684, 1.2029, 1.319, 'Up', -0.4756)
Record inserted
(2001, 1.319, -0.838, -0.066, 1.035, -1.825, 1.3185, 2.232, 'Up', -0.075)
Record inserted
(2001, 2.232, 1.319, -0.838, -0.066, 1.035, 1.7653, -0.278, 'Down', 0.7364)
Record inserted
(2001, -0.278, 2.232, 1.319, -0.838, -0.066, 1.4879, -0.753, 'Down', 0.47380000000000005)
Record inserted
(2001, -0.753, -0.278, 2.232, 1.319, -0.838, 1.2482, -1.587, 'Down', 0.3364)
Record inserted
(2001, -1.587, -0.753, -0.278, 2.232, 1.319, 1.2187, -0.278, 'Down', 0.18660000000000004)
Record inserted
(2001, -0.278, -1.587, -0.753, -0.278, 2.232, 1.3672, 0.027, 'Up', -0.13279999999999995)
Record inserted
(2001, 0.027, -0.278, -1.587, -0.753, -0.278, 1.4497, -1.556, 'Down', -0.5738000000000001)
Record inserted
(2001, -1.556, 0.027, -0.278, -1.587, -0.753, 1.5115, 0.331, 'Up', -0.8294)
Record inserted
(2001, 0.331, -1.556, 0.027, -0.278, -1.587, 1.3068, 1.003, 'Up', -0.6126)
Record inserted
(2001, 1.003, 0.331, -1.556, 0.027, -0.278, 1.2604, 0.755, 'Up', -0.09460000000000005)
Record inserted
(2001, 0.755, 1.003, 0.331, -1.556, 0.027, 1.354, 0.581, 'Up', 0.11199999999999999)
Record inserted
(2001, 0.581, 0.755, 1.003, 0.331, -1.556, 1.4849, -0.838, 'Down', 0.2227999999999999)
Record inserted
(2001, -0.838, 0.581, 0.755, 1.003, 0.331, 1.4905, 0.435, 'Up', 0.36639999999999995)
Record inserted
(2001, 0.435, -0.838, 0.581, 0.755, 1.003, 1.694, -0.021, 'Down', 0.3872)
Record inserted
(2001, -0.021, 0.435, -0.838, 0.581, 0.755, 0.43967, 0.412, 'Up', 0.18239999999999998)
Record inserted
(2001, 0.412, -0.021, 0.435, -0.838, 0.581, 0.7911, 0.675, 'Up', 0.11379999999999998)
Record inserted
(2001, 0.675, 0.412, -0.021, 0.435, -0.838, 0.8763, 0.336, 'Up', 0.13260000000000002)
Record inserted
(2001, 0.336, 0.675, 0.412, -0.021, 0.435, 0.9174, -1.115, 'Down', 0.36740000000000006)
Record inserted
(2002, -1.115, 0.336, 0.675, 0.412, -0.021, 0.9436, 0.574, 'Up', 0.05740000000000002)
Record inserted
(2002, 0.574, -1.115, 0.336, 0.675, 0.412, 1.171, 0.918, 'Up', 0.1764)
Record inserted
(2002, 0.918, 0.574, -1.115, 0.336, 0.675, 1.3989, 0.621, 'Up', 0.2776)
Record inserted
(2002, 0.621, 0.918, 0.574, -1.115, 0.336, 1.513, -0.65, 'Down', 0.26680000000000004)
Record inserted
(2002, -0.65, 0.621, 0.918, 0.574, -1.115, 1.3083, -0.359, 'Down', 0.06960000000000002)
Record inserted
(2002, -0.359, -0.65, 0.621, 0.918, 0.574, 1.2588, -0.48, 'Down', 0.22080000000000002)
Record inserted
(2002, -0.48, -0.359, -0.65, 0.621, 0.918, 1.452, 0.122, 'Up', 0.010000000000000031)
Record inserted
(2002, 0.122, -0.48, -0.359, -0.65, 0.621, 1.299, -0.947, 'Down', -0.1492)
Record inserted
(2002, -0.947, 0.122, -0.48, -0.359, -0.65, 1.2119, -0.628, 'Down', -0.4628)
Record inserted
(2002, -0.628, -0.947, 0.122, -0.48, -0.359, 1.2864, 0.683, 'Up', -0.4584)
Record inserted
(2002, 0.683, -0.628, -0.947, 0.122, -0.48, 1.3869, -1.625, 'Down', -0.25)
Record inserted
(2002, -1.625, 0.683, -0.628, -0.947, 0.122, 1.4825, 1.003, 'Up', -0.479)
Record inserted
(2002, 1.003, -1.625, 0.683, -0.628, -0.947, 1.3801, -0.992, 'Down', -0.3028)
Record inserted
(2002, -0.992, 1.003, -1.625, 0.683, -0.628, 1.3333, -0.733, 'Down', -0.3118)
Record inserted
(2002, -0.733, -0.992, 1.003, -1.625, 0.683, 1.3116, 0.792, 'Up', -0.3328000000000001)
Record inserted
(2002, 0.792, -0.733, -0.992, 1.003, -1.625, 1.4792, 0.352, 'Up', -0.31100000000000005)
Record inserted
(2002, 0.352, 0.792, -0.733, -0.992, 1.003, 1.5528, 0.1, 'Up', 0.0844)
Record inserted
(2002, 0.1, 0.352, 0.792, -0.733, -0.992, 1.3451, -0.019, 'Down', -0.0962)
Record inserted
(2002, -0.019, 0.1, 0.352, 0.792, -0.733, 1.1868, -2.861, 'Down', 0.09840000000000002)
Record inserted
(2002, -2.861, -0.019, 0.1, 0.352, 0.792, 1.812, 1.175, 'Up', -0.32720000000000005)
Record inserted
(2002, 1.175, -2.861, -0.019, 0.1, 0.352, 2.0196, 1.493, 'Up', -0.25060000000000004)
Record inserted
(2002, 1.493, 1.175, -2.861, -0.019, 0.1, 1.557, -0.708, 'Down', -0.02240000000000001)
Record inserted
(2002, -0.708, 1.493, 1.175, -2.861, -0.019, 1.3672, -2.474, 'Down', -0.184)
Record inserted
(2002, -2.474, -0.708, 1.493, 1.175, -2.861, 1.4376, -0.404, 'Down', -0.675)
Record inserted
(2002, -0.404, -2.474, -0.708, 1.493, 1.175, 1.7783, -0.597, 'Down', -0.18359999999999999)
Record inserted
(2002, -0.597, -0.404, -2.474, -0.708, 1.493, 1.6658, -0.308, 'Down', -0.5379999999999999)
Record inserted
(2002, -0.308, -0.597, -0.404, -2.474, -0.708, 1.4416, 1.486, 'Up', -0.8982000000000001)
Record inserted
(2002, 1.486, -0.308, -0.597, -0.404, -2.474, 1.3719, 1.434, 'Up', -0.45940000000000003)
Record inserted
(2002, 1.434, 1.486, -0.308, -0.597, -0.404, 1.1594, -0.399, 'Down', 0.32220000000000004)
Record inserted
(2002, -0.399, 1.434, 1.486, -0.308, -0.597, 1.0942, 0.994, 'Up', 0.32320000000000004)
Record inserted
(2002, 0.994, -0.399, 1.434, 1.486, -0.308, 1.2159, -0.181, 'Down', 0.6414)
Record inserted
(2002, -0.181, 0.994, -0.399, 1.434, 1.486, 1.2725, -1.102, 'Down', 0.6668)
Record inserted
(2002, -1.102, -0.181, 0.994, -0.399, 1.434, 1.3592, -1.887, 'Down', 0.14919999999999994)
Record inserted
(2002, -1.887, -1.102, -0.181, 0.994, -0.399, 1.1899, 1.351, 'Up', -0.515)
Record inserted
(2002, 1.351, -1.887, -1.102, -0.181, 0.994, 1.4389, -1.551, 'Down', -0.16500000000000004)
Record inserted
(2002, -1.551, 1.351, -1.887, -1.102, -0.181, 1.3816, 0.822, 'Up', -0.674)
Record inserted
(2002, 0.822, -1.551, 1.351, -1.887, -1.102, 1.411, 1.798, 'Up', -0.4734)
Record inserted
(2002, 1.798, 0.822, -1.551, 1.351, -1.887, 1.3674, -0.005, 'Down', 0.10659999999999999)
Record inserted
(2002, -0.005, 1.798, 0.822, -1.551, 1.351, 1.3092, 0.046, 'Up', 0.483)
Record inserted
(2002, 0.046, -0.005, 1.798, 0.822, -1.551, 1.3938, -0.285, 'Down', 0.22200000000000003)
Record inserted
(2002, -0.285, 0.046, -0.005, 1.798, 0.822, 1.3922, 2.263, 'Up', 0.47519999999999996)
Record inserted
(2002, 2.263, -0.285, 0.046, -0.005, 1.798, 1.4565, 1.949, 'Up', 0.7634000000000001)
Record inserted
(2002, 1.949, 2.263, -0.285, 0.046, -0.005, 1.5943, -0.667, 'Down', 0.7935999999999999)
Record inserted
(2002, -0.667, 1.949, 2.263, -0.285, 0.046, 1.5493, 1.451, 'Up', 0.6611999999999999)
Record inserted
(2002, 1.451, -0.667, 1.949, 2.263, -0.285, 1.5413, -0.45, 'Down', 0.9422)
Record inserted
(2002, -0.45, 1.451, -0.667, 1.949, 2.263, 1.5174, 0.585, 'Up', 0.9092)
Record inserted
(2002, 0.585, -0.45, 1.451, -0.667, 1.949, 1.412, 0.339, 'Up', 0.5736000000000001)
Record inserted
(2002, 0.339, 0.585, -0.45, 1.451, -0.667, 1.2102, -0.229, 'Down', 0.2516)
Record inserted
(2002, -0.229, 0.339, 0.585, -0.45, 1.451, 1.3044, -0.986, 'Down', 0.3392)
Record inserted
(2002, -0.986, -0.229, 0.339, 0.585, -0.45, 1.354, -0.091, 'Down', -0.14820000000000003)
Record inserted
(2002, -0.091, -0.986, -0.229, 0.339, 0.585, 1.2088, 1.138, 'Up', -0.07640000000000002)
Record inserted
(2002, 1.138, -0.091, -0.986, -0.229, 0.339, 1.4939, -0.052, 'Down', 0.034199999999999994)
Record inserted
(2002, -0.052, 1.138, -0.091, -0.986, -0.229, 1.1695, 0.407, 'Up', -0.044000000000000025)
Record inserted
(2002, 0.407, -0.052, 1.138, -0.091, -0.986, 1.255, -1.576, 'Down', 0.08319999999999998)
Record inserted
(2002, -1.576, 0.407, -0.052, 1.138, -0.091, 1.3049, 0.151, 'Up', -0.03480000000000004)
Record inserted
(2002, 0.151, -1.576, 0.407, -0.052, 1.138, 1.3392, -0.424, 'Down', 0.013599999999999968)
Record inserted
(2002, -0.424, 0.151, -1.576, 0.407, -0.052, 1.2433, -1.465, 'Down', -0.29880000000000007)
Record inserted
(2002, -1.465, -0.424, 0.151, -1.576, 0.407, 1.0579, 0.585, 'Up', -0.5814)
Record inserted
(2002, 0.585, -1.465, -0.424, 0.151, -1.576, 1.2236, 0.535, 'Up', -0.5458000000000001)
Record inserted
(2002, 0.535, 0.585, -1.465, -0.424, 0.151, 1.1801, 0.246, 'Up', -0.12359999999999997)
Record inserted
(2002, 0.246, 0.535, 0.585, -1.465, -0.424, 1.1476, -0.074, 'Down', -0.10459999999999998)
Record inserted
(2002, -0.074, 0.246, 0.535, 0.585, -1.465, 1.0509, -0.853, 'Down', -0.034600000000000006)
Record inserted
(2002, -0.853, -0.074, 0.246, 0.535, 0.585, 1.1767, -0.999, 'Down', 0.08780000000000002)
Record inserted
(2002, -0.999, -0.853, -0.074, 0.246, 0.535, 1.2197, 0.084, 'Up', -0.229)
Record inserted
(2002, 0.084, -0.999, -0.853, -0.074, 0.246, 1.2838, -0.321, 'Down', -0.31920000000000004)
Record inserted
(2002, -0.321, 0.084, -0.999, -0.853, -0.074, 1.1102, 0.228, 'Up', -0.4326)
Record inserted
(2002, 0.228, -0.321, 0.084, -0.999, -0.853, 1.0953, -0.666, 'Down', -0.3722)
Record inserted
(2002, -0.666, 0.228, -0.321, 0.084, -0.999, 1.2354, 1.133, 'Up', -0.33480000000000004)
Record inserted
(2002, 1.133, -0.666, 0.228, -0.321, 0.084, 1.4479, -2.369, 'Down', 0.09159999999999999)
Record inserted
(2002, -2.369, 1.133, -0.666, 0.228, -0.321, 1.5056, 0.663, 'Up', -0.399)
Record inserted
(2002, 0.663, -2.369, 1.133, -0.666, 0.228, 1.2821, -0.761, 'Down', -0.20220000000000007)
Record inserted
(2002, -0.761, 0.663, -2.369, 1.133, -0.666, 1.1204, 2.342, 'Up', -0.4)
Record inserted
(2002, 2.342, -0.761, 0.663, -2.369, 1.133, 1.3413, -0.204, 'Down', 0.20159999999999992)
Record inserted
(2002, -0.204, 2.342, -0.761, 0.663, -2.369, 1.3769, -0.142, 'Down', -0.06580000000000004)
Record inserted
(2002, -0.142, -0.204, 2.342, -0.761, 0.663, 1.3593, 0.062, 'Up', 0.3796)
Record inserted
(2002, 0.062, -0.142, -0.204, 2.342, -0.761, 1.185, -1.541, 'Down', 0.2594)
Record inserted
(2002, -1.541, 0.062, -0.142, -0.204, 2.342, 1.1818, -0.62, 'Down', 0.10340000000000008)
Record inserted
(2002, -0.62, -1.541, 0.062, -0.142, -0.204, 1.3885, -0.71, 'Down', -0.48900000000000005)
Record inserted
(2002, -0.71, -0.62, -1.541, 0.062, -0.142, 1.3732, -0.152, 'Down', -0.5902000000000001)
Record inserted
(2002, -0.152, -0.71, -0.62, -1.541, 0.062, 1.5174, -1.389, 'Down', -0.5922)
Record inserted
(2002, -1.389, -0.152, -0.71, -0.62, -1.541, 1.3742, -1.01, 'Down', -0.8824)
Record inserted
(2002, -1.01, -1.389, -0.152, -0.71, -0.62, 1.3147, 1.077, 'Up', -0.7762)
Record inserted
(2002, 1.077, -1.01, -1.389, -0.152, -0.71, 1.6286, 0.886, 'Up', -0.4368)
Record inserted
(2002, 0.886, 1.077, -1.01, -1.389, -0.152, 1.4514, -0.175, 'Down', -0.1176)
Record inserted
(2002, -0.175, 0.886, 1.077, -1.01, -1.389, 1.364, -1.026, 'Down', -0.1222)
Record inserted
(2002, -1.026, -0.175, 0.886, 1.077, -1.01, 1.2845, -1.934, 'Down', -0.04960000000000002)
Record inserted
(2002, -1.934, -1.026, -0.175, 0.886, 1.077, 1.1226, -0.302, 'Down', -0.23439999999999994)
Record inserted
(2002, -0.302, -1.934, -1.026, -0.175, 0.886, 1.3547, 3.75, 'Up', -0.5101999999999999)
Record inserted
(2002, 3.75, -0.302, -1.934, -1.026, -0.175, 1.502, -1.455, 'Down', 0.0626)
Record inserted

(2002, -1.455, 3.75, -0.302, -1.934, -1.026, 1.153, -1.679, 'Down', -0.19340000000000002)
Record inserted
(2002, -1.679, -1.455, 3.75, -0.302, -1.934, 1.1719, 1.855, 'Up', -0.32400000000000007)
Record inserted
(2002, 1.855, -1.679, -1.455, 3.75, -0.302, 1.0886, 2.114, 'Up', 0.4338)
Record inserted
(2002, 2.114, 1.855, -1.679, -1.455, 3.75, 1.4145, -0.566, 'Down', 0.917)
Record inserted
(2002, -0.566, 2.114, 1.855, -1.679, -1.455, 1.4202, 0.656, 'Up', 0.05379999999999998)
Record inserted
(2002, 0.656, -0.566, 2.114, 1.855, -1.679, 1.2566, 0.761, 'Up', 0.4759999999999998)
Record inserted
(2002, 0.761, 0.656, -0.566, 2.114, 1.855, 1.2744, -1.329, 'Down', 0.9640000000000001)
Record inserted
(2002, -1.329, 0.761, 0.656, -0.566, 2.114, 0.9898, -1.099, 'Down', 0.32720000000000005)
Record inserted
(2002, -1.099, -1.329, 0.761, 0.656, -0.566, 1.2005, 0.569, 'Up', -0.3153999999999999)
Record inserted
(2002, 0.569, -1.099, -1.329, 0.761, 0.656, 1.1363, 1.018, 'Up', -0.08839999999999996)
Record inserted
(2002, 1.018, 0.569, -1.099, -1.329, 0.761, 1.1929, -1.209, 'Down', -0.015999999999999993)
Record inserted
(2002, -1.209, 1.018, 0.569, -1.099, -1.329, 0.8854, -0.855, 'Down', -0.41)
Record inserted
(2002, -0.855, -1.209, 1.018, 0.569, -1.099, 0.9965, -0.641, 'Down', -0.31520000000000004)
Record inserted
(2002, -0.641, -0.855, -1.209, 1.018, 0.569, 1.0818, -0.281, 'Down', -0.22360000000000002)
Record inserted
(2002, -0.281, -0.641, -0.855, -1.209, 1.018, 1.2866, 0.233, 'Up', -0.39360000000000006)
Record inserted
(2002, 0.233, -0.281, -0.641, -0.855, -1.209, 1.2773, -2.48, 'Down', -0.5506)
Record inserted
(2002, -2.48, 0.233, -0.281, -0.641, -0.855, 1.3243, 0.001, 'Up', -0.8048)
Record inserted
(2002, 0.001, -2.48, 0.233, -0.281, -0.641, 1.4666, 0.885, 'Up', -0.6336)
Record inserted
(2002, 0.885, 0.001, -2.48, 0.233, -0.281, 1.3001, -1.976, 'Down', -0.32839999999999997)
Record inserted
(2002, -1.976, 0.885, 0.001, -2.48, 0.233, 1.6015, -0.157, 'Down', -0.6674)
Record inserted
(2002, -0.157, -1.976, 0.885, 0.001, -2.48, 1.3413, 0.312, 'Up', -0.7454000000000001)
Record inserted
(2002, 0.312, -0.157, -1.976, 0.885, 0.001, 1.2262, -1.663, 'Down', -0.187)
Record inserted
(2002, -1.663, 0.312, -0.157, -1.976, 0.885, 1.2124, 0.657, 'Up', -0.5198)
Record inserted
(2002, 0.657, -1.663, 0.312, -0.157, -1.976, 1.79572, -1.049, 'Down', -0.5654)
Record inserted
(2002, -1.049, 0.657, -1.663, 0.312, -0.157, 1.4055, -0.227, 'Down', -0.37999999999999995)
Record inserted
(2002, -0.227, -1.049, 0.657, -1.663, 0.312, 1.549, 2.869, 'Up', -0.394)
Record inserted
(2002, 2.869, -0.227, -1.049, 0.657, -1.663, 1.2366, 0.094, 'Up', 0.11740000000000009)
Record inserted
(2002, 0.094, 2.869, -0.227, -1.049, 0.657, 1.1931, -1.654, 'Down', 0.46880000000000005)
Record inserted
(2002, -1.654, 0.094, 2.869, -0.227, -1.049, 1.3361, -1.343, 'Down', 0.006600000000000073)
Record inserted
(2002, -1.343, -1.654, 0.094, 2.869, -0.227, 1.3897, -1.704, 'Down', -0.052199999999999955)
Record inserted
(2002, -1.704, -1.343, -1.654, 0.094, 2.869, 1.4972, 0.362, 'Up', -0.3475999999999998)
Record inserted
(2002, 0.362, -1.704, -1.343, -1.654, 0.094, 1.5526, -1.67, 'Down', -0.849)
Record inserted
(2002, -1.67, 0.362, -1.704, -1.343, -1.654, 1.5137, -0.267, 'Down', -1.2018)
Record inserted
(2002, -0.267, -1.67, 0.362, -1.704, -1.343, 2.01429, 1.758, 'Up', -0.9244)
Record inserted
(2002, 1.758, -0.267, -1.67, 0.362, -1.704, 1.9086, -0.083, 'Down', -0.30419999999999997)
Record inserted
(2002, -0.083, 1.758, -0.267, -1.67, 0.362, 2.117, -2.139, 'Down', 0.019999999999999997)
Record inserted
(2002, -2.139, -0.083, 1.758, -0.267, -1.67, 1.4255, -2.123, 'Down', -0.48019999999999996)
Record inserted
(2002, -2.123, -2.139, -0.083, 1.758, -0.267, 1.823, 0.622, 'Up', -0.5708000000000001)
Record inserted
(2002, 0.622, -2.123, -2.139, -0.083, 1.758, 1.5278, 3.673, 'Up', -0.39300000000000007)
Record inserted
(2002, 3.673, 0.622, -2.123, -2.139, -0.083, 0.6994, -1.218, 'Down', -0.010000000000000018)
Record inserted
(2002, -1.218, 3.673, 0.622, -2.123, -2.139, 1.1844, -2.472, 'Down', -0.23700000000000002)
Record inserted
(2002, -2.472, -1.218, 3.673, 0.622, -2.123, 1.3489, -3.396, 'Down', -0.30360000000000004)
Record inserted
(2002, -3.396, -2.472, -1.218, 3.673, 0.622, 1.8169, 0.75, 'Up', -0.5582)
Record inserted
(2002, 0.75, -3.396, -2.472, -1.218, 3.673, 2.08048, -0.645, 'Down', -0.5326000000000001)
Record inserted
(2002, -0.645, 0.75, -3.396, -2.472, -1.218, 1.6074, -0.376, 'Down', -1.3961999999999999)
Record inserted
(2002, -0.376, -0.645, 0.75, -3.396, -2.472, 2.5748, -1.851, 'Down', -1.2277999999999998)
Record inserted
(2002, -1.851, -0.376, -0.645, 0.75, -3.396, 1.8437, 0.566, 'Up', -1.1036)
Record inserted
(2002, 0.566, -1.851, -0.376, -0.645, 0.75, 2.5665, -2.702, 'Down', -0.31120000000000003)
Record inserted
(2002, -2.702, 0.566, -1.851, -0.376, -0.645, 1.7363, -3.835, 'Down', -1.0016000000000003)
Record inserted
(2002, -3.835, -2.702, 0.566, -1.851, -0.376, 2.6541, -3.291, 'Down', -1.6396000000000002)
Record inserted
(2002, -3.291, -3.835, -2.702, 0.566, -1.851, 2.24806, -2.702, 'Down', -2.2226)
Record inserted
(2002, -2.702, -3.291, -3.835, -2.702, 0.566, 2.44102, 5.733, 'Up', -2.3928)
Record inserted
(2002, 5.733, -2.702, -3.291, -3.835, -2.702, 2.77556, -0.563, 'Down', -1.3594000000000002)
Record inserted
(2002, -0.563, 5.733, -2.702, -3.291, -3.835, 2.4247, 1.688, 'Up', -0.9315999999999999)
Record inserted
(2002, 1.688, -0.563, 5.733, -2.702, -3.291, 1.7961, 5.408, 'Up', 0.17299999999999996)
Record inserted
(2002, 5.408, 1.688, -0.563, 5.733, -2.702, 1.77865, 0.425, 'Up', 1.9128)
Record inserted
(2002, 0.425, 5.408, 1.688, -0.563, 5.733, 1.82609, 0.979, 'Up', 2.5382)
Record inserted
(2002, 0.979, 0.425, 5.408, 1.688, -0.563, 2.04936, -2.957, 'Down', 1.5874000000000001)
Record inserted
(2002, -2.957, 0.979, 0.425, 5.408, 1.688, 1.6722, -2.308, 'Down', 1.1086)
Record inserted
(2002, -2.308, -2.957, 0.979, 0.425, 5.408, 1.5381, -3.43, 'Down', 0.3094000000000001)
Record inserted
(2002, -3.43, -2.308, -2.957, 0.979, 0.425, 1.4255, 2.992, 'Up', -1.4582000000000002)
Record inserted
(2002, 2.992, -3.43, -2.308, -2.957, 0.979, 1.5141, 2.001, 'Up', -0.9447999999999999)
Record inserted
(2002, 2.001, 2.992, -3.43, -2.308, -2.957, 1.4904, 3.272, 'Up', -0.7404)
Record inserted
(2002, 3.272, 2.001, 2.992, -3.43, -2.308, 1.6467, 0.351, 'Up', 0.5054000000000002)
Record inserted
(2002, 0.351, 3.272, 2.001, 2.992, -3.43, 1.2949, -0.533, 'Down', 1.0372)
Record inserted
(2002, -0.533, 0.351, 3.272, 2.001, 2.992, 1.0365, -2.168, 'Down', 1.6165999999999996)
Record inserted
(2002, -2.168, -0.533, 0.351, 3.272, 2.001, 1.2977, 4.005, 'Up', 0.5845999999999999)
Record inserted
(2002, 4.005, -2.168, -0.533, 0.351, 3.272, 1.5338, 1.156, 'Up', 0.9853999999999999)
Record inserted
(2002, 1.156, 4.005, -2.168, -0.533, 0.351, 1.5051, -0.159, 'Down', 0.5621999999999999)
Record inserted
(2002, -0.159, 1.156, 4.005, -2.168, -0.533, 1.2653, 2.361, 'Up', 0.46019999999999994)
Record inserted
(2002, 2.361, -0.159, 1.156, 4.005, -2.168, 1.2998, -1.396, 'Down', 1.0390000000000001)
Record inserted
(2002, -1.396, 2.361, -0.159, 1.156, 4.005, 1.3085, 1.273, 'Up', 1.1934)
Record inserted
(2002, 1.273, -1.396, 2.361, -0.159, 1.156, 1.3531, 1.405, 'Up', 0.647)
Record inserted
(2002, 1.405, 1.273, -1.396, 2.361, -0.159, 1.373, -2.269, 'Down', 0.6968000000000001)
Record inserted
(2002, -2.269, 1.405, 1.273, -1.396, 2.361, 1.0715, 0.754, 'Up', 0.27480000000000004)
Record inserted
(2002, 0.754, -2.269, 1.405, 1.273, -1.396, 1.0169, -1.385, 'Down', -0.046600000000000016)
Record inserted
(2002, -1.385, 0.754, -2.269, 1.405, 1.273, 1.3077, -1.813, 'Down', -0.044400000000000085)
Record inserted
(2002, -1.813, -1.385, 0.754, -2.269, 1.405, 1.1466, -0.008, 'Down', -0.6616)
Record inserted
(2002, -0.008, -1.813, -1.385, 0.754, -2.269, 1.2711, -0.188, 'Down', -0.9442)
Record inserted
(2002, -0.188, -0.008, -1.813, -1.385, 0.754, 0.9299, -4.154, 'Down', -0.528)
Record inserted
(2002, -4.154, -0.188, -0.008, -1.813, -1.385, 1.2898, 1.752, 'Up', -1.5095999999999998)
Record inserted
(2002, 1.752, -4.154, -0.188, -0.008, -1.813, 1.3721, -1.595, 'Down', -0.8822000000000001)
Record inserted
(2002, -1.595, 1.752, -4.154, -0.188, -0.008, 1.4013, 1.68, 'Up', -0.8385999999999999)
Record inserted
(2002, 1.68, -1.595, 1.752, -4.154, -0.188, 1.1845, 1.011, 'Up', -0.5010000000000001)
Record inserted
(2002, 1.011, 1.68, -1.595, 1.752, -4.154, 1.1306, 0.733, 'Up', -0.2612)
Record inserted
(2002, 0.733, 1.011, 1.68, -1.595, 1.752, 1.1864, -0.014, 'Down', 0.7162)
Record inserted
(2002, -0.014, 0.733, 1.011, 1.68, -1.595, 0.8466, -2.478, 'Down', 0.36300000000000004)
Record inserted
(2002, -2.478, -0.014, 0.733, 1.011, 1.68, 1.1916, 0.327, 'Up', 0.18639999999999998)
Record inserted
(2002, 0.327, -2.478, -0.014, 0.733, 1.011, 1.271, 0.145, 'Up', -0.08420000000000001)
Record inserted
(2002, 0.145, 0.327, -2.478, -0.014, 0.733, 1.0014, -1.973, 'Down', -0.25739999999999996)
Record inserted
(2002, -1.973, 0.145, 0.327, -2.478, -0.014, 1.4486, -0.465, 'Down', -0.7986)
Record inserted
(2002, -0.465, -1.973, 0.145, 0.327, -2.478, 1.501, -3.006, 'Down', -0.8888000000000001)
Record inserted
(2002, -3.006, -0.465, -1.973, 0.145, 0.327, 1.524, 0.245, 'Up', -0.9944000000000001)
Record inserted
(2002, 0.245, -3.006, -0.465, -1.973, 0.145, 1.7928, -1.383, 'Down', -1.0108000000000001)
Record inserted
(2002, -1.383, 0.245, -3.006, -0.465, -1.973, 1.3811, -1.728, 'Down', -1.3164)
Record inserted
(2002, -1.728, -1.383, 0.245, -3.006, -0.465, 1.67024, 2.486, 'Up', -1.2673999999999999)
Record inserted
(2002, 2.486, -1.728, -1.383, 0.245, -3.006, 1.6515, 1.821, 'Up', -0.6771999999999999)
Record inserted
(2002, 1.821, 2.486, -1.728, -1.383, 0.245, 1.65, -3.226, 'Down', 0.2882000000000001)
Record inserted
(2002, -3.226, 1.821, 2.486, -1.728, -1.383, 1.5073, -1.461, 'Down', -0.40599999999999997)
Record inserted
(2002, -1.461, -3.226, 1.821, 2.486, -1.728, 1.72187, 4.002, 'Up', -0.4216000000000001)
Record inserted
(2002, 4.002, -1.461, -3.226, 1.821, 2.486, 1.7809, -2.359, 'Down', 0.7243999999999999)
Record inserted
(2002, -2.359, 4.002, -1.461, -3.226, 1.821, 1.6689, -1.082, 'Down', -0.2446000000000001)
Record inserted
(2002, -1.082, -2.359, 4.002, -1.461, -3.226, 1.6745, -2.243, 'Down', -0.8252)
Record inserted
(2002, -2.243, -1.082, -2.359, 4.002, -1.461, 1.83593, -1.911, 'Down', -0.6286000000000002)
Record inserted
(2002, -1.911, -2.243, -1.082, -2.359, 4.002, 1.5765, 1.69, 'Up', -0.7186)
Record inserted
(2002, 1.69, -1.911, -2.243, -1.082, -2.359, 1.93843, -2.729, 'Down', -1.181)
Record inserted
(2002, -2.729, 1.69, -1.911, -2.243, -1.082, 1.88503, 3.497, 'Up', -1.255)
Record inserted
(2002, 3.497, -2.729, 1.69, -1.911, -2.243, 2.09023, 3.906, 'Up', -0.33920000000000006)
Record inserted
(2002, 3.906, 3.497, -2.729, 1.69, -1.911, 1.85413, 0.733, 'Up', 0.8906000000000003)
Record inserted
(2002, 0.733, 3.906, 3.497, -2.729, 1.69, 1.2003, 4.734, 'Up', 1.4194)
Record inserted
(2002, 4.734, 0.733, 3.906, 3.497, -2.729, 1.956, -2.411, 'Down', 2.0281999999999996)
Record inserted
(2002, -2.411, 4.734, 0.733, 3.906, 3.497, 1.585, 2.23, 'Up', 2.0918)
Record inserted
(2002, 2.23, -2.411, 4.734, 0.733, 3.906, 1.78039, 0.59, 'Up', 1.8384)
Record inserted
(2002, 0.59, 2.23, -2.411, 4.734, 0.733, 1.4231, 1.733, 'Up', 1.1751999999999998)
Record inserted
(2002, 1.733, 0.59, 2.23, -2.411, 4.734, 1.447, -1.063, 'Down', 1.3752)
Record inserted
(2002, -1.063, 1.733, 0.59, 2.23, -2.411, 1.5492, 0.672, 'Up', 0.21580000000000005)
Record inserted
(2002, 0.672, -1.063, 1.733, 0.59, 2.23, 1.5939, -1.522, 'Down', 0.8324)
Record inserted
(2002, -1.522, 0.672, -1.063, 1.733, 0.59, 1.70057, 1.717, 'Up', 0.08200000000000005)
Record inserted
(2002, 1.717, -1.522, 0.672, -1.063, 1.733, 1.3404, -0.827, 'Down', 0.30740000000000006)
Record inserted
(2002, -0.827, 1.717, -1.522, 0.672, -1.063, 1.3826, -0.908, 'Down', -0.20459999999999995)
Record inserted
(2002, -0.908, -0.827, 1.717, -1.522, 0.672, 1.5297, 0.97, 'Up', -0.17359999999999995)
Record inserted
(2002, 0.97, -0.908, -0.827, 1.717, -1.522, 1.4223, -0.556, 'Down', -0.11399999999999999)
Record inserted
(2002, -0.556, 0.97, -0.908, -0.827, 1.717, 1.6413, 1.716, 'Up', 0.07919999999999998)
Record inserted

(2002, 1.716, -0.556, 0.97, -0.908, -0.827, 1.4504, 0.82, 'Up', 0.079)
Record inserted
(2002, 0.82, 1.716, -0.556, 0.97, -0.908, 1.6459, 0.775, 'Up', 0.40840000000000004)
Record inserted
(2002, 0.775, 0.82, 1.716, -0.556, 0.97, 1.3541, 0.914, 'Up', 0.7449999999999999)
Record inserted
(2002, 0.914, 0.775, 0.82, 1.716, -0.556, 1.674, -2.285, 'Down', 0.7337999999999999)
Record inserted
(2002, -2.285, 0.914, 0.775, 0.82, 1.716, 1.4669, -0.876, 'Down', 0.388)
Record inserted
(2002, -0.876, -2.285, 0.914, 0.775, 0.82, 1.4465, -2.073, 'Down', -0.13040000000000002)
Record inserted
(2002, -2.073, -0.876, -2.285, 0.914, 0.775, 1.113, 0.772, 'Up', -0.7090000000000001)
Record inserted
(2002, 0.772, -2.073, -0.876, -2.285, 0.914, 1.3771, -0.048, 'Down', -0.7095999999999999)
Record inserted
(2002, -0.048, 0.772, -2.073, -0.876, -2.285, 1.4634, 2.463, 'Up', -0.9019999999999999)
Record inserted
(2002, 2.463, -0.048, 0.772, -2.073, -0.876, 1.519, 0.615, 'Up', 0.047600000000000066)
Record inserted
(2002, 0.615, 2.463, -0.048, 0.772, -2.073, 1.4001, -1.041, 'Down', 0.3458000000000001)
Record inserted
(2002, -1.041, 0.615, 2.463, -0.048, 0.772, 1.2826, -0.402, 'Down', 0.5522)
Record inserted
(2002, -0.402, -1.041, 0.615, 2.463, -0.048, 1.3374, 1.941, 'Up', 0.3174)
Record inserted
(2002, 1.941, -0.402, -1.041, 0.615, 2.463, 1.5173, 2.145, 'Up', 0.7152000000000001)
Record inserted
(2002, 2.145, 1.941, -0.402, -1.041, 0.615, 2.4151, -0.344, 'Down', 0.6516)
Record inserted
(2002, -0.344, 2.145, 1.941, -0.402, -1.041, 1.6268, 0.249, 'Up', 0.4598)
Record inserted
(2002, 0.249, -0.344, 2.145, 1.941, -0.402, 1.574, -2.097, 'Down', 0.7177999999999999)
Record inserted
(2002, -2.097, 0.249, -0.344, 2.145, 1.941, 1.5436, 2.799, 'Up', 0.3788000000000001)
Record inserted
(2002, 2.799, -2.097, 0.249, -0.344, 2.145, 1.3503, -0.273, 'Down', 0.5504)
Record inserted
(2002, -0.273, 2.799, -2.097, 0.249, -0.344, 0.64346, -0.19, 'Down', 0.06679999999999997)
Record inserted
(2002, -0.19, -0.273, 2.799, -2.097, 0.249, 1.612, -1.475, 'Down', 0.09759999999999998)
Record inserted
(2002, -1.475, -0.19, -0.273, 2.799, -2.097, 1.4884, -0.344, 'Down', -0.24720000000000003)
Record inserted
(2002, -0.344, -1.475, -0.19, -0.273, 2.799, 1.5889, -1.202, 'Down', 0.10339999999999998)
Record inserted
(2002, -1.202, -0.344, -1.475, -0.19, -0.273, 1.2502, 0.627, 'Up', -0.6968)
Record inserted
(2002, 0.627, -1.202, -0.344, -1.475, -0.19, 1.2411, -2.218, 'Down', -0.5168)
Record inserted
(2002, -2.218, 0.627, -1.202, -0.344, -1.475, 1.3208, 1.396, 'Up', -0.9224)
Record inserted
(2002, 1.396, -2.218, 0.627, -1.202, -0.344, 1.2866, 0.056, 'Up', -0.3482)
Record inserted
(2002, 0.056, 1.396, -2.218, 0.627, -1.202, 1.2851, -0.373, 'Down', -0.2682)
Record inserted
(2002, -0.373, 0.056, 1.396, -2.218, 0.627, 1.2553, -1.342, 'Down', -0.1024)
Record inserted
(2002, -1.342, -0.373, 0.056, 1.396, -2.218, 1.3308, 2.352, 'Up', -0.4962)
Record inserted
(2002, 2.352, -1.342, -0.373, 0.056, 1.396, 1.2716, -0.814, 'Down', 0.4177999999999999)
Record inserted
(2002, -0.814, 2.352, -1.342, -0.373, 0.056, 1.2518, -1.315, 'Down', -0.024200000000000055)
Record inserted
(2002, -1.315, -0.814, 2.352, -1.342, -0.373, 1.4462, -0.771, 'Down', -0.29840000000000005)
Record inserted
(2002, -0.771, -1.315, -0.814, 2.352, -1.342, 1.3859, 1.302, 'Up', -0.378)
Record inserted
(2002, 1.302, -0.771, -1.315, -0.814, 2.352, 1.78273, 0.181, 'Up', 0.1508)
Record inserted
(2002, 0.181, 1.302, -0.771, -1.315, -0.814, 1.1121, -0.547, 'Down', -0.2834)
Record inserted
(2002, -0.547, 0.181, 1.302, -0.771, -1.315, 0.45831, -0.315, 'Down', -0.22999999999999998)
Record inserted
(2002, -0.315, -0.547, 0.181, 1.302, -0.771, 0.7211, -1.603, 'Down', -0.030000000000000006)
Record inserted
(2002, -1.603, -0.315, -0.547, 0.181, 1.302, 0.7584, 0.456, 'Up', -0.19639999999999996)
Record inserted
(2002, 0.456, -1.603, -0.315, -0.547, 0.181, 1.0578, 0.049, 'Up', -0.3656)
Record inserted
(2003, 0.049, 0.456, -1.603, -0.315, -0.547, 1.0885, 3.32, 'Up', -0.392)
Record inserted
(2003, 3.32, 0.049, 0.456, -1.603, -0.315, 1.2292, -0.048, 'Down', 0.3813999999999999)
Record inserted
(2003, -0.048, 3.32, 0.049, 0.456, -1.603, 1.1308, 2.247, 'Up', 0.4347999999999999)
Record inserted
(2003, 2.247, -0.048, 3.32, 0.049, 0.456, 1.4359, -0.654, 'Down', 1.2048)
Record inserted
(2003, -0.654, 2.247, -0.048, 3.32, 0.049, 1.5452, -1.409, 'Down', 0.9828000000000001)
Record inserted
(2003, -1.409, -0.654, 2.247, -0.048, 3.32, 1.4676, 1.939, 'Up', 0.6911999999999999)
Record inserted
(2003, 1.939, -1.409, -0.654, 2.247, -0.048, 1.5603, 0.0, 'Up', 0.4149999999999999)
Record inserted
(2003, 0.0, 1.939, -1.409, -0.654, 2.247, 1.4854, -0.141, 'Down', 0.4246)
Record inserted
(2003, -0.141, 0.0, 1.939, -1.409, -0.654, 1.3963, 0.583, 'Up', -0.053000000000000005)
Record inserted
(2003, 0.583, -0.141, 0.0, 1.939, -1.409, 1.3794, -1.443, 'Down', 0.19440000000000004)
Record inserted
(2003, -1.443, 0.583, -0.141, 0.0, 1.939, 1.4321, -0.394, 'Down', 0.1876)
Record inserted
(2003, -0.394, -1.443, 0.583, -0.141, 0.0, 1.5346, -1.402, 'Down', -0.279)
Record inserted
(2003, -1.402, -0.394, -1.443, 0.583, -0.141, 1.3582, -1.57, 'Down', -0.5593999999999999)
Record inserted
(2003, -1.57, -1.402, -0.394, -1.443, 0.583, 1.3352, -1.043, 'Down', -0.8452)
Record inserted
(2003, -1.043, -1.57, -1.402, -0.394, -1.443, 1.5608, 1.022, 'Up', -1.1704)
Record inserted
(2003, 1.022, -1.043, -1.57, -1.402, -0.394, 1.74455, -2.923, 'Down', -0.6774)
Record inserted
(2003, -2.923, 1.022, -1.043, -1.57, -1.402, 1.5748, -1.616, 'Down', -1.1832)
Record inserted
(2003, -1.616, -2.923, 1.022, -1.043, -1.57, 1.4359, 1.305, 'Up', -1.226)
Record inserted
(2003, 1.305, -1.616, -2.923, 1.022, -1.043, 1.4591, 0.678, 'Up', -0.651)
Record inserted
(2003, 0.678, 1.305, -1.616, -2.923, 1.022, 1.5954, -2.285, 'Down', -0.3068)
Record inserted
(2003, -2.285, 0.678, 1.305, -1.616, -2.923, 1.5103, 1.313, 'Up', -0.9682000000000001)
Record inserted
(2003, 1.313, -2.285, 0.678, 1.305, -1.616, 1.57853, 0.54, 'Up', -0.12100000000000008)
Record inserted
(2003, 0.54, 1.313, -2.285, 0.678, 1.305, 1.2585, -1.409, 'Down', 0.3101999999999999)
Record inserted
(2003, -1.409, 0.54, 1.313, -2.285, 0.678, 1.4516, -0.544, 'Down', -0.23260000000000006)
Record inserted
(2003, -0.544, -1.409, 0.54, 1.313, -2.285, 1.4508, -0.645, 'Down', -0.47700000000000004)
Record inserted
(2003, -0.645, -0.544, -1.409, 0.54, 1.313, 1.4309, -1.009, 'Down', -0.14899999999999997)
Record inserted
(2003, -1.009, -0.645, -0.544, -1.409, 0.54, 1.2768, 0.757, 'Up', -0.6134000000000001)
Record inserted
(2003, 0.757, -1.009, -0.645, -0.544, -1.409, 1.2382, -0.81, 'Down', -0.57)
Record inserted
(2003, -0.81, 0.757, -1.009, -0.645, -0.544, 1.307, -1.269, 'Down', -0.4502)
Record inserted
(2003, -1.269, -0.81, 0.757, -1.009, -0.645, 1.2605, -0.16, 'Down', -0.5952)
Record inserted
(2003, -0.16, -1.269, -0.81, 0.757, -1.009, 1.4893, 2.143, 'Up', -0.4981999999999999)
Record inserted
(2003, 2.143, -0.16, -1.269, -0.81, 0.757, 1.4046, 1.95, 'Up', 0.13219999999999998)
Record inserted
(2003, 1.95, 2.143, -0.16, -1.269, -0.81, 1.2508, -0.71, 'Down', 0.3707999999999999)
Record inserted
(2003, -0.71, 1.95, 2.143, -0.16, -1.269, 1.0756, -0.95, 'Down', 0.3908)
Record inserted
(2003, -0.95, -0.71, 1.95, 2.143, -0.16, 1.1941, 1.322, 'Up', 0.45459999999999995)
Record inserted
(2003, 1.322, -0.95, -0.71, 1.95, 2.143, 1.3982, -1.838, 'Down', 0.751)
Record inserted
(2003, -1.838, 1.322, -0.95, -0.71, 1.95, 1.2292, 0.719, 'Up', -0.04520000000000004)
Record inserted
(2003, 0.719, -1.838, 1.322, -0.95, -0.71, 1.4837, -1.314, 'Down', -0.2914)
Record inserted
(2003, -1.314, 0.719, -1.838, 1.322, -0.95, 1.3744, 1.176, 'Up', -0.4122)
Record inserted
(2003, 1.176, -1.314, 0.719, -1.838, 1.322, 1.2878, 0.462, 'Up', 0.012999999999999989)
Record inserted
(2003, 0.462, 1.176, -1.314, 0.719, -1.838, 1.3733, -0.754, 'Down', -0.15900000000000009)
Record inserted
(2003, -0.754, 0.462, 1.176, -1.314, 0.719, 1.2089, -1.536, 'Down', 0.05779999999999996)
Record inserted
(2003, -1.536, -0.754, 0.462, 1.176, -1.314, 1.2566, 0.956, 'Up', -0.39320000000000005)
Record inserted
(2003, 0.956, -1.536, -0.754, 0.462, 1.176, 1.3327, -0.934, 'Down', 0.060799999999999965)
Record inserted
(2003, -0.934, 0.956, -1.536, -0.754, 0.462, 1.2992, 0.826, 'Up', -0.3612000000000001)
Record inserted
(2003, 0.826, -0.934, 0.956, -1.536, -0.754, 1.3685, -2.583, 'Down', -0.28840000000000005)
Record inserted
(2003, -2.583, 0.826, -0.934, 0.956, -1.536, 1.255, -0.836, 'Down', -0.6542000000000001)
Record inserted
(2003, -0.836, -2.583, 0.826, -0.934, 0.956, 1.4277, 0.432, 'Up', -0.5142)
Record inserted
(2003, 0.432, -0.836, -2.583, 0.826, -0.934, 1.62, 3.446, 'Up', -0.619)
Record inserted
(2003, 3.446, 0.432, -0.836, -2.583, 0.826, 1.8163, 0.165, 'Up', 0.257)
Record inserted
(2003, 0.165, 3.446, 0.432, -0.836, -2.583, 1.5419, 3.543, 'Up', 0.12480000000000002)
Record inserted
(2003, 3.543, 0.165, 3.446, 0.432, -0.836, 1.70042, 0.424, 'Up', 1.35)
Record inserted
(2003, 0.424, 3.543, 0.165, 3.446, 0.432, 1.5551, 0.874, 'Up', 1.6019999999999999)
Record inserted
(2003, 0.874, 0.424, 3.543, 0.165, 3.446, 1.4734, 0.189, 'Up', 1.6904)
Record inserted
(2003, 0.189, 0.874, 0.424, 3.543, 0.165, 1.4391, 2.298, 'Up', 1.0390000000000001)
Record inserted
(2003, 2.298, 0.189, 0.874, 0.424, 3.543, 1.88371, -3.523, 'Down', 1.4656)
Record inserted
(2003, -3.523, 2.298, 0.189, 0.874, 0.424, 1.293, 1.216, 'Up', 0.05239999999999999)
Record inserted
(2003, 1.216, -3.523, 2.298, 0.189, 0.874, 1.3334, -0.548, 'Down', 0.21079999999999993)
Record inserted
(2003, -0.548, 1.216, -3.523, 2.298, 0.189, 1.3197, -0.164, 'Down', -0.07360000000000008)
Record inserted
(2003, -0.164, -0.548, 1.216, -3.523, 2.298, 1.2329, -0.578, 'Down', -0.14420000000000002)
Record inserted
(2003, -0.578, -0.164, -0.548, 1.216, -3.523, 1.227, -1.774, 'Down', -0.7194)
Record inserted
(2003, -1.774, -0.578, -0.164, -0.548, 1.216, 1.4955, 1.214, 'Up', -0.36960000000000004)
Record inserted
(2003, 1.214, -1.774, -0.578, -0.164, -0.548, 1.4616, 2.612, 'Up', -0.37)
Record inserted
(2003, 2.612, 1.214, -1.774, -0.578, -0.164, 1.5898, -0.505, 'Down', 0.26200000000000007)
Record inserted
(2003, -0.505, 2.612, 1.214, -1.774, -0.578, 1.3395, 0.274, 'Up', 0.19380000000000003)
Record inserted
(2003, 0.274, -0.505, 2.612, 1.214, -1.774, 1.2412, 0.123, 'Up', 0.3642)
Record inserted
(2003, 0.123, 0.274, -0.505, 2.612, 1.214, 1.494, -0.186, 'Down', 0.7436)
Record inserted
(2003, -0.186, 0.123, 0.274, -0.505, 2.612, 1.2354, -1.4, 'Down', 0.4636)
Record inserted
(2003, -1.4, -0.186, 0.123, 0.274, -0.505, 1.2937, 0.646, 'Up', -0.3388)
Record inserted
(2003, 0.646, -1.4, -0.186, 0.123, 0.274, 1.2753, -0.376, 'Down', -0.10859999999999999)
Record inserted
(2003, -0.376, 0.646, -1.4, -0.186, 0.123, 1.1416, 1.95, 'Up', -0.23859999999999998)
Record inserted
(2003, 1.95, -0.376, 0.646, -1.4, -0.186, 1.131, 0.63, 'Up', 0.12679999999999997)
Record inserted
(2003, 0.63, 1.95, -0.376, 0.646, -1.4, 1.4602, -1.224, 'Down', 0.29000000000000004)
Record inserted
(2003, -1.224, 0.63, 1.95, -0.376, 0.646, 1.5876, 1.554, 'Up', 0.3252)
Record inserted
(2003, 1.554, -1.224, 0.63, 1.95, -0.376, 1.4306, -0.176, 'Down', 0.5068)
Record inserted
(2003, -0.176, 1.554, -1.224, 0.63, 1.95, 1.1187, 2.17, 'Up', 0.5468)
Record inserted
(2003, 2.17, -0.176, 1.554, -1.224, 0.63, 1.6312, 0.839, 'Up', 0.5908)
Record inserted
(2003, 0.839, 2.17, -0.176, 1.554, -1.224, 1.6672, -0.826, 'Down', 0.6325999999999998)
Record inserted
(2003, -0.826, 0.839, 2.17, -0.176, 1.554, 1.6481, -1.385, 'Down', 0.7121999999999999)
Record inserted
(2003, -1.385, -0.826, 0.839, 2.17, -0.176, 1.3358, 1.783, 'Up', 0.12440000000000002)
Record inserted
(2003, 1.783, -1.385, -0.826, 0.839, 2.17, 1.273, 0.328, 'Up', 0.5162)
Record inserted
(2003, 0.328, 1.783, -1.385, -0.826, 0.839, 1.5256, -0.1, 'Down', 0.14779999999999996)
Record inserted
(2003, -0.1, 0.328, 1.783, -1.385, -0.826, 1.78851, -0.068, 'Down', -0.039999999999999966)
Record inserted
(2003, -0.068, -0.1, 0.328, 1.783, -1.385, 1.3975, 1.504, 'Up', 0.11159999999999996)
Record inserted
(2003, 1.504, -0.068, -0.1, 0.328, 1.783, 1.5543, -0.38, 'Down', 0.6894)
Record inserted
(2003, -0.38, 1.504, -0.068, -0.1, 0.328, 1.4463, 0.846, 'Up', 0.25680000000000003)
Record inserted
(2003, 0.846, -0.38, 1.504, -0.068, -0.1, 1.6496, -0.51, 'Down', 0.36039999999999994)
Record inserted
(2003, -0.51, 0.846, -0.38, 1.504, -0.068, 1.5319, -1.006, 'Down', 0.2784)
Record inserted

(2003, -1.006, -0.51, 0.846, -0.38, 1.504, 1.3796, 1.428, 'Up', 0.09079999999999999)
Record inserted
(2003, 1.428, -1.006, -0.51, 0.846, -0.38, 1.3261, 1.253, 'Up', 0.07559999999999997)
Record inserted
(2003, 1.253, 1.428, -1.006, -0.51, 0.846, 1.3788, -0.297, 'Down', 0.4022)
Record inserted
(2003, -0.297, 1.253, 1.428, -1.006, -0.51, 1.4181, -0.32, 'Down', 0.17359999999999998)
Record inserted
(2003, -0.32, -0.297, 1.253, 1.428, -1.006, 1.4018, 0.787, 'Up', 0.2116)
Record inserted
(2003, 0.787, -0.32, -0.297, 1.253, 1.428, 1.5087, -0.25, 'Down', 0.5702)
Record inserted
(2003, -0.25, 0.787, -0.32, -0.297, 1.253, 1.5055, -2.492, 'Down', 0.2346)
Record inserted
(2003, -2.492, -0.25, 0.787, -0.32, -0.297, 1.3757, -0.113, 'Down', -0.5144)
Record inserted
(2003, -0.113, -2.492, -0.25, 0.787, -0.32, 1.5053, 0.401, 'Up', -0.47759999999999997)
Record inserted
(2003, 0.401, -0.113, -2.492, -0.25, 0.787, 1.4578, 0.915, 'Up', -0.3334)
Record inserted
(2003, 0.915, 0.401, -0.113, -2.492, -0.25, 1.4485, 0.145, 'Up', -0.30779999999999996)
Record inserted
(2003, 0.145, 0.915, 0.401, -0.113, -2.492, 1.201, 1.957, 'Up', -0.22879999999999998)
Record inserted
(2003, 1.957, 0.145, 0.915, 0.401, -0.113, 1.532, 0.183, 'Up', 0.661)
Record inserted
(2003, 0.183, 1.957, 0.145, 0.915, 0.401, 1.559, -0.376, 'Down', 0.7202)
Record inserted
(2003, -0.376, 0.183, 1.957, 0.145, 0.915, 1.6858, 1.469, 'Up', 0.5648)
Record inserted
(2003, 1.469, -0.376, 0.183, 1.957, 0.145, 1.6888, 0.354, 'Up', 0.6756)
Record inserted
(2003, 0.354, 1.469, -0.376, 0.183, 1.957, 1.6625, 0.472, 'Up', 0.7174)
Record inserted
(2003, 0.472, 0.354, 1.469, -0.376, 0.183, 1.4502, 1.511, 'Up', 0.4204)
Record inserted
(2003, 1.511, 0.472, 0.354, 1.469, -0.376, 1.6187, 0.395, 'Up', 0.686)
Record inserted
(2003, 0.395, 1.511, 0.472, 0.354, 1.469, 1.6931, -0.24, 'Down', 0.8402000000000001)
Record inserted
(2003, -0.24, 0.395, 1.511, 0.472, 0.354, 1.8372, -1.198, 'Down', 0.4984)
Record inserted
(2003, -1.198, -0.24, 0.395, 1.511, 0.472, 1.307, 0.913, 'Up', 0.188)
Record inserted
(2003, 0.913, -1.198, -0.24, 0.395, 1.511, 1.2754, 1.283, 'Up', 0.2762)
Record inserted
(2003, 1.283, 0.913, -1.198, -0.24, 0.395, 1.52, 0.103, 'Up', 0.23059999999999997)
Record inserted
(2003, 0.103, 1.283, 0.913, -1.198, -0.24, 1.5531, -0.991, 'Down', 0.1722)
Record inserted
(2003, -0.991, 0.103, 1.283, 0.913, -1.198, 1.2716, 2.238, 'Up', 0.021999999999999974)
Record inserted
(2003, 2.238, -0.991, 0.103, 1.283, 0.913, 1.3459, 0.091, 'Up', 0.7092)
Record inserted
(2003, 0.091, 2.238, -0.991, 0.103, 1.283, 1.4797, -0.155, 'Down', 0.5448000000000001)
Record inserted
(2003, -0.155, 0.091, 2.238, -0.991, 0.103, 1.4889, -1.524, 'Down', 0.2572)
Record inserted
(2003, -1.524, -0.155, 0.091, 2.238, -0.991, 1.5301, 0.1, 'Up', -0.06820000000000001)
Record inserted
(2003, 0.1, -1.524, -0.155, 0.091, 2.238, 1.698, -1.411, 'Down', 0.15)
Record inserted
(2003, -1.411, 0.1, -1.524, -0.155, 0.091, 1.3981, 0.184, 'Up', -0.5797999999999999)
Record inserted
(2003, 0.184, -1.411, 0.1, -1.524, -0.155, 1.3883, -0.827, 'Down', -0.5611999999999999)
Record inserted
(2003, -0.827, 0.184, -1.411, 0.1, -1.524, 1.4592, 1.077, 'Up', -0.6956)
Record inserted
(2003, 1.077, -0.827, 0.184, -1.411, 0.1, 1.3874, -0.974, 'Down', -0.17540000000000003)
Record inserted
(2003, -0.974, 1.077, -0.827, 0.184, -1.411, 1.2678, -0.176, 'Down', -0.3902)
Record inserted
(2003, -0.176, -0.974, 1.077, -0.827, 0.184, 1.5872, 0.802, 'Up', -0.1432)
Record inserted
(2003, 0.802, -0.176, -0.974, 1.077, -0.827, 1.4602, 1.164, 'Up', -0.01959999999999997)
Record inserted
(2003, 1.164, 0.802, -0.176, -0.974, 1.077, 1.5193, -0.81, 'Down', 0.3786)
Record inserted
(2003, -0.81, 1.164, 0.802, -0.176, -0.974, 0.7759, 1.899, 'Up', 0.001200000000000001)
Record inserted
(2003, 1.899, -0.81, 1.164, 0.802, -0.176, 1.4291, 0.34, 'Up', 0.5758)
Record inserted
(2003, 0.34, 1.899, -0.81, 1.164, 0.802, 1.5657, -0.559, 'Down', 0.679)
Record inserted
(2003, -0.559, 0.34, 1.899, -0.81, 1.164, 1.618, -1.348, 'Down', 0.40679999999999994)
Record inserted
(2003, -1.348, -0.559, 0.34, 1.899, -0.81, 1.4657, 0.955, 'Up', -0.09559999999999999)
Record inserted
(2003, 0.955, -1.348, -0.559, 0.34, 1.899, 1.2127, 0.573, 'Up', 0.25739999999999996)
Record inserted
(2003, 0.573, 0.955, -1.348, -0.559, 0.34, 1.4489, -0.343, 'Down', -0.007800000000000018)
Record inserted
(2003, -0.343, 0.573, 0.955, -1.348, -0.559, 1.5186, -0.633, 'Down', -0.14440000000000006)
Record inserted
(2003, -0.633, -0.343, 0.573, 0.955, -1.348, 1.662, -1.243, 'Down', -0.15920000000000004)
Record inserted
(2003, -1.243, -0.633, -0.343, 0.573, 0.955, 1.6614, 1.181, 'Up', -0.13820000000000007)
Record inserted
(2003, 1.181, -1.243, -0.633, -0.343, 0.573, 1.3652, -1.462, 'Down', -0.09300000000000001)
Record inserted
(2003, -1.462, 1.181, -1.243, -0.633, -0.343, 1.2542, 0.951, 'Up', -0.5)
Record inserted
(2003, 0.951, -1.462, 1.181, -1.243, -0.633, 1.4397, 0.051, 'Up', -0.2412)
Record inserted
(2003, 0.051, 0.951, -1.462, 1.181, -1.243, 1.3627, -0.709, 'Down', -0.1044)
Record inserted
(2003, -0.709, 0.051, 0.951, -1.462, 1.181, 1.559, 1.74, 'Up', 0.002400000000000002)
Record inserted
(2003, 1.74, -0.709, 0.051, 0.951, -1.462, 1.3975, -0.216, 'Down', 0.1142)
Record inserted
(2003, -0.216, 1.74, -0.709, 0.051, 0.951, 1.3286, -0.727, 'Down', 0.36340000000000006)
Record inserted
(2003, -0.727, -0.216, 1.74, -0.709, 0.051, 1.5089, -0.181, 'Down', 0.027800000000000012)
Record inserted
(2003, -0.181, -0.727, -0.216, 1.74, -0.709, 1.3919, 0.286, 'Up', -0.01859999999999997)
Record inserted
(2003, 0.286, -0.181, -0.727, -0.216, 1.74, 1.608, -1.026, 'Down', 0.1804)
Record inserted
(2003, -1.026, 0.286, -0.181, -0.727, -0.216, 1.3906, 0.272, 'Up', -0.3728)
Record inserted
(2003, 0.272, -1.026, 0.286, -0.181, -0.727, 1.3187, -1.766, 'Down', -0.2752)
Record inserted
(2003, -1.766, 0.272, -1.026, 0.286, -0.181, 1.3517, 0.168, 'Up', -0.483)
Record inserted
(2003, 0.168, -1.766, 0.272, -1.026, 0.286, 1.491, 0.728, 'Up', -0.41320000000000007)
Record inserted
(2003, 0.728, 0.168, -1.766, 0.272, -1.026, 1.3893, 0.356, 'Up', -0.32480000000000003)
Record inserted
(2003, 0.356, 0.728, 0.168, -1.766, 0.272, 1.0866, 0.307, 'Up', -0.0484)
Record inserted
(2003, 0.307, 0.356, 0.728, 0.168, -1.766, 1.0222, 0.995, 'Up', -0.04140000000000001)
Record inserted
(2003, 0.995, 0.307, 0.356, 0.728, 0.168, 1.1323, -0.638, 'Down', 0.5108)
Record inserted
(2003, -0.638, 0.995, 0.307, 0.356, 0.728, 1.2088, 0.659, 'Up', 0.3496)
Record inserted
(2003, 0.659, -0.638, 0.995, 0.307, 0.356, 1.1868, 0.016, 'Up', 0.3358)
Record inserted
(2003, 0.016, 0.659, -0.638, 0.995, 0.307, 0.63637, 0.916, 'Up', 0.2678)
Record inserted
(2003, 0.916, 0.016, 0.659, -0.638, 0.995, 1.1276, 0.261, 'Up', 0.38960000000000006)
Record inserted
(2003, 0.261, 0.916, 0.016, 0.659, -0.638, 1.3006, -0.205, 'Down', 0.2428)
Record inserted
(2003, -0.205, 0.261, 0.916, 0.016, 0.659, 1.2108, 0.297, 'Up', 0.3294)
Record inserted
(2003, 0.297, -0.205, 0.261, 0.916, 0.016, 1.4071, -1.018, 'Down', 0.257)
Record inserted
(2003, -1.018, 0.297, -0.205, 0.261, 0.916, 1.3089, 0.065, 'Up', 0.0502)
Record inserted
(2003, 0.065, -1.018, 0.297, -0.205, 0.261, 0.9717, 0.304, 'Up', -0.12000000000000002)
Record inserted
(2003, 0.304, 0.065, -1.018, 0.297, -0.205, 1.1787, 0.006, 'Up', -0.11140000000000001)
Record inserted
(2003, 0.006, 0.304, 0.065, -1.018, 0.297, 1.0514, 0.607, 'Up', -0.06920000000000001)
Record inserted
(2003, 0.607, 0.006, 0.304, 0.065, -1.018, 1.1652, 0.516, 'Up', -0.007200000000000007)
Record inserted
(2003, 0.516, 0.607, 0.006, 0.304, 0.065, 0.9451, 1.387, 'Up', 0.2996)
Record inserted
(2003, 1.387, 0.516, 0.607, 0.006, 0.304, 1.4705, 0.419, 'Up', 0.5639999999999998)
Record inserted
(2003, 0.419, 1.387, 0.516, 0.607, 0.006, 1.6756, 0.166, 'Up', 0.587)
Record inserted
(2003, 0.166, 0.419, 1.387, 0.516, 0.607, 1.4539, -0.64, 'Down', 0.619)
Record inserted
(2003, -0.64, 0.166, 0.419, 1.387, 0.516, 1.4652, 1.004, 'Up', 0.36960000000000004)
Record inserted
(2003, 1.004, -0.64, 0.166, 0.419, 1.387, 1.2993, -0.821, 'Down', 0.46720000000000006)
Record inserted
(2003, -0.821, 1.004, -0.64, 0.166, 0.419, 1.4148, -1.197, 'Down', 0.02560000000000001)
Record inserted
(2003, -1.197, -0.821, 1.004, -0.64, 0.166, 1.5821, 0.544, 'Up', -0.2976)
Record inserted
(2003, 0.544, -1.197, -0.821, 1.004, -0.64, 1.3359, 0.217, 'Up', -0.22199999999999998)
Record inserted
(2003, 0.217, 0.544, -1.197, -0.821, 1.004, 1.2367, -0.375, 'Down', -0.05060000000000002)
Record inserted
(2003, -0.375, 0.217, 0.544, -1.197, -0.821, 1.1513, 1.43, 'Up', -0.3264)
Record inserted
(2003, 1.43, -0.375, 0.217, 0.544, -1.197, 1.4032, -0.325, 'Down', 0.1238)
Record inserted
(2003, -0.325, 1.43, -0.375, 0.217, 0.544, 1.33821, 1.327, 'Up', 0.2982)
Record inserted
(2003, 1.327, -0.325, 1.43, -0.375, 0.217, 1.4988, -0.316, 'Down', 0.4548)
Record inserted
(2003, -0.316, 1.327, -0.325, 1.43, -0.375, 1.5186, -1.301, 'Down', 0.34819999999999995)
Record inserted
(2003, -1.301, -0.316, 1.327, -0.325, 1.43, 1.2788, 0.607, 'Up', 0.16299999999999998)
Record inserted
(2003, 0.607, -1.301, -0.316, 1.327, -0.325, 1.3017, -1.91, 'Down', -0.0016000000000000124)
Record inserted
(2003, -1.91, 0.607, -1.301, -0.316, 1.327, 1.556, -0.605, 'Down', -0.3186)
Record inserted
(2003, -0.605, -1.91, 0.607, -1.301, -0.316, 1.53, -0.64, 'Down', -0.7049999999999998)
Record inserted
(2003, -0.64, -0.605, -1.91, 0.607, -1.301, 1.4725, 0.976, 'Up', -0.7698)
Record inserted
(2003, 0.976, -0.64, -0.605, -1.91, 0.607, 1.3665, -1.054, 'Down', -0.31439999999999996)
Record inserted
(2003, -1.054, 0.976, -0.64, -0.605, -1.91, 1.5905, 2.234, 'Up', -0.6466)
Record inserted
(2003, 2.234, -1.054, 0.976, -0.64, -0.605, 1.5663, 0.198, 'Up', 0.18219999999999992)
Record inserted
(2003, 0.198, 2.234, -1.054, 0.976, -0.64, 1.2693, 0.942, 'Up', 0.3428)
Record inserted
(2003, 0.942, 0.198, 2.234, -1.054, 0.976, 1.5705, 0.437, 'Up', 0.6591999999999999)
Record inserted
(2003, 0.437, 0.942, 0.198, 2.234, -1.054, 1.0258, 0.474, 'Up', 0.5513999999999999)
Record inserted
(2003, 0.474, 0.437, 0.942, 0.198, 2.234, 1.2795, -0.526, 'Down', 0.857)
Record inserted
(2003, -0.526, 0.474, 0.437, 0.942, 0.198, 1.2625, 0.479, 'Up', 0.305)
Record inserted
(2003, 0.479, -0.526, 0.474, 0.437, 0.942, 1.5787, -0.065, 'Down', 0.36119999999999997)
Record inserted
(2003, -0.065, 0.479, -0.526, 0.474, 0.437, 1.1081, 0.702, 'Up', 0.1598)
Record inserted
(2003, 0.702, -0.065, 0.479, -0.526, 0.474, 1.0405, 0.395, 'Up', 0.21280000000000002)
Record inserted
(2003, 0.395, 0.702, -0.065, 0.479, -0.526, 1.2719, -0.259, 'Down', 0.197)
Record inserted
(2003, -0.259, 0.395, 0.702, -0.065, 0.479, 1.5211, 0.316, 'Up', 0.25039999999999996)
Record inserted
(2003, 0.316, -0.259, 0.395, 0.702, -0.065, 1.4177, -1.024, 'Down', 0.2178)
Record inserted
(2003, -1.024, 0.316, -0.259, 0.395, 0.702, 1.352, 0.516, 'Up', 0.026000000000000002)
Record inserted

(2003, 0.516, -1.024, 0.316, -0.259, 0.395, 1.1726, 0.129, 'Up', -0.011199999999999998)
Record inserted
(2003, 0.129, 0.516, -1.024, 0.316, -0.259, 1.498, -1.498, 'Down', -0.0644)
Record inserted
(2003, -1.498, 0.129, 0.516, -1.024, 0.316, 1.6472, 0.331, 'Up', -0.3122)
Record inserted
(2003, 0.331, -1.498, 0.129, 0.516, -1.024, 1.6043, -0.47, 'Down', -0.30920000000000003)
Record inserted
(2003, -0.47, 0.331, -1.498, 0.129, 0.516, 1.4203, 0.216, 'Up', -0.1984)
Record inserted
(2003, 0.216, -0.47, 0.331, -1.498, 0.129, 1.3718, 1.519, 'Up', -0.2584)
Record inserted
(2003, 1.519, 0.216, -0.47, 0.331, -1.498, 1.6292, 0.126, 'Up', 0.01959999999999997)
Record inserted
(2003, 0.126, 1.519, 0.216, -0.47, 0.331, 1.5626, -0.112, 'Down', 0.3444)
Record inserted
(2003, -0.112, 0.126, 1.519, 0.216, -0.47, 1.6297, 0.36, 'Up', 0.25579999999999997)
Record inserted
(2003, 0.36, -0.112, 0.126, 1.519, 0.216, 1.4989, 0.791, 'Up', 0.4218)
Record inserted
(2003, 0.791, 0.36, -0.112, 0.126, 1.519, 1.3782, -0.545, 'Down', 0.5368)
Record inserted
(2003, -0.545, 0.791, 0.36, -0.112, 0.126, 1.4176, -0.137, 'Down', 0.124)
Record inserted
(2003, -0.137, -0.545, 0.791, 0.36, -0.112, 1.4018, 0.593, 'Up', 0.07139999999999999)
Record inserted
(2003, 0.593, -0.137, -0.545, 0.791, 0.36, 1.4539, -0.457, 'Down', 0.21239999999999998)
Record inserted
(2003, -0.457, 0.593, -0.137, -0.545, 0.791, 1.4405, -0.579, 'Down', 0.049)
Record inserted
(2003, -0.579, -0.457, 0.593, -0.137, -0.545, 1.2436, -0.052, 'Down', -0.225)
Record inserted
(2003, -0.052, -0.579, -0.457, 0.593, -0.137, 1.1625, 1.143, 'Up', -0.1264)
Record inserted
(2003, 1.143, -0.052, -0.579, -0.457, 0.593, 1.3493, -0.011, 'Down', 0.1296)
Record inserted
(2003, -0.011, 1.143, -0.052, -0.579, -0.457, 1.383, -0.762, 'Down', 0.00880000000000002)
Record inserted
(2003, -0.762, -0.011, 1.143, -0.052, -0.579, 1.3561, -0.64, 'Down', -0.05219999999999999)
Record inserted
(2003, -0.64, -0.762, -0.011, 1.143, -0.052, 1.3743, -0.908, 'Down', -0.0644)
Record inserted
(2003, -0.908, -0.64, -0.762, -0.011, 1.143, 1.3543, 0.802, 'Up', -0.23560000000000003)
Record inserted
(2003, 0.802, -0.908, -0.64, -0.762, -0.011, 1.3262, -0.843, 'Down', -0.30379999999999996)
Record inserted
(2003, -0.843, 0.802, -0.908, -0.64, -0.762, 1.3267, 0.158, 'Up', -0.4702)
Record inserted
(2003, 0.158, -0.843, 0.802, -0.908, -0.64, 1.2738, 1.623, 'Up', -0.2862)
Record inserted
(2003, 1.623, 0.158, -0.843, 0.802, -0.908, 1.3028, 0.172, 'Up', 0.1664)
Record inserted
(2003, 0.172, 1.623, 0.158, -0.843, 0.802, 1.3337, 0.433, 'Up', 0.38239999999999996)
Record inserted
(2003, 0.433, 0.172, 1.623, 0.158, -0.843, 1.0977, -0.024, 'Down', 0.30859999999999993)
Record inserted
(2003, -0.024, 0.433, 0.172, 1.623, 0.158, 0.48722, 1.126, 'Up', 0.47239999999999993)
Record inserted
(2003, 1.126, -0.024, 0.433, 0.172, 1.623, 1.375, -0.327, 'Down', 0.666)
Record inserted
(2003, -0.327, 1.126, -0.024, 0.433, 0.172, 1.3832, -0.177, 'Down', 0.27599999999999997)
Record inserted
(2003, -0.177, -0.327, 1.126, -0.024, 0.433, 1.4417, 0.469, 'Up', 0.2062)
Record inserted
(2003, 0.469, -0.177, -0.327, 1.126, -0.024, 1.4631, -0.768, 'Down', 0.21339999999999995)
Record inserted
(2003, -0.768, 0.469, -0.177, -0.327, 1.126, 1.2659, 0.735, 'Up', 0.06459999999999996)
Record inserted
(2003, 0.735, -0.768, 0.469, -0.177, -0.327, 1.2189, -0.853, 'Down', -0.013600000000000011)
Record inserted
(2003, -0.853, 0.735, -0.768, 0.469, -0.177, 1.4655, -0.107, 'Down', -0.11880000000000002)
Record inserted
(2003, -0.107, -0.853, 0.735, -0.768, 0.469, 1.444, 1.148, 'Up', -0.1048)
Record inserted
(2003, 1.148, -0.107, -0.853, 0.735, -0.768, 1.4411, 0.274, 'Up', 0.030999999999999982)
Record inserted
(2003, 0.274, 1.148, -0.107, -0.853, 0.735, 1.2231, -0.568, 'Down', 0.2394)
Record inserted
(2003, -0.568, 0.274, 1.148, -0.107, -0.853, 1.5208, 0.664, 'Up', -0.021199999999999997)
Record inserted
(2003, 0.664, -0.568, 0.274, 1.148, -0.107, 1.5479, 0.126, 'Up', 0.2822)
Record inserted
(2003, 0.126, 0.664, -0.568, 0.274, 1.148, 1.4417, 1.18, 'Up', 0.32880000000000004)
Record inserted
(2003, 1.18, 0.126, 0.664, -0.568, 0.274, 1.5799, -0.048, 'Down', 0.33520000000000005)
Record inserted
(2003, -0.048, 1.18, 0.126, 0.664, -0.568, 1.6573, 0.393, 'Up', 0.27080000000000004)
Record inserted
(2003, 0.393, -0.048, 1.18, 0.126, 0.664, 1.2517, 0.282, 'Up', 0.46299999999999997)
Record inserted
(2003, 0.282, 0.393, -0.048, 1.18, 0.126, 1.1453, -0.181, 'Down', 0.38659999999999994)
Record inserted
(2003, -0.181, 0.282, 0.393, -0.048, 1.18, 0.51806, 0.169, 'Up', 0.3252)
Record inserted
(2003, 0.169, -0.181, 0.282, 0.393, -0.048, 0.35607, 1.24, 'Up', 0.123)
Record inserted
(2003, 1.24, 0.169, -0.181, 0.282, 0.393, 1.0588, 0.014, 'Up', 0.3806)
Record inserted
(2003, 0.014, 1.24, 0.169, -0.181, 0.282, 1.0126, 0.205, 'Up', 0.3048)
Record inserted
(2004, 0.205, 0.014, 1.24, 0.169, -0.181, 1.0275, -0.309, 'Down', 0.2894)
Record inserted
(2004, -0.309, 0.205, 0.014, 1.24, 0.169, 1.1532, 1.24, 'Up', 0.2638)
Record inserted
(2004, 1.24, -0.309, 0.205, 0.014, 1.24, 1.5782, 0.129, 'Up', 0.47800000000000004)
Record inserted
(2004, 0.129, 1.24, -0.309, 0.205, 0.014, 1.4945, 0.237, 'Up', 0.2558)
Record inserted
(2004, 0.237, 0.129, 1.24, -0.309, 0.205, 1.7049, 0.496, 'Up', 0.3004)
Record inserted
(2004, 0.496, 0.237, 0.129, 1.24, -0.309, 1.8684, -0.889, 'Down', 0.3586)
Record inserted
(2004, -0.889, 0.496, 0.237, 0.129, 1.24, 1.7207, 0.479, 'Up', 0.2426)
Record inserted
(2004, 0.479, -0.889, 0.496, 0.237, 0.129, 1.5102, -0.533, 'Down', 0.0904)
Record inserted
(2004, -0.533, 0.479, -0.889, 0.496, 0.237, 1.5959, 0.829, 'Up', -0.042000000000000016)
Record inserted
(2004, 0.829, -0.533, 0.479, -0.889, 0.496, 1.5146, 0.135, 'Up', 0.07639999999999998)
Record inserted
(2004, 0.135, 0.829, -0.533, 0.479, -0.889, 1.695, 0.687, 'Up', 0.0041999999999999815)
Record inserted
(2004, 0.687, 0.135, 0.829, -0.533, 0.479, 1.7211, -0.093, 'Down', 0.3194)
Record inserted
(2004, -0.093, 0.687, 0.135, 0.829, -0.533, 1.6982, 0.777, 'Up', 0.205)
Record inserted
(2004, 0.777, -0.093, 0.687, 0.135, 0.829, 1.7576, -0.321, 'Down', 0.46699999999999997)
Record inserted
(2004, -0.321, 0.777, -0.093, 0.687, 0.135, 1.6937, -0.209, 'Down', 0.23700000000000002)
Record inserted
(2004, -0.209, -0.321, 0.777, -0.093, 0.687, 1.5612, 1.211, 'Up', 0.16820000000000002)
Record inserted
(2004, 1.211, -0.209, -0.321, 0.777, -0.093, 1.4806, -0.98, 'Down', 0.273)
Record inserted
(2004, -0.98, 1.211, -0.209, -0.321, 0.777, 1.6731, -1.361, 'Down', 0.09560000000000002)
Record inserted
(2004, -1.361, -0.98, 1.211, -0.209, -0.321, 1.842, 0.499, 'Up', -0.332)
Record inserted
(2004, 0.499, -1.361, -0.98, 1.211, -0.209, 1.9219, -0.263, 'Down', -0.16799999999999998)
Record inserted
(2004, -0.263, 0.499, -1.361, -0.98, 1.211, 1.635, 0.365, 'Up', -0.1788)
Record inserted
(2004, 0.365, -0.263, 0.499, -1.361, -0.98, 1.5992, 0.068, 'Up', -0.348)
Record inserted
(2004, 0.068, 0.365, -0.263, 0.499, -1.361, 1.4769, -0.837, 'Down', -0.1384)
Record inserted
(2004, -0.837, 0.068, 0.365, -0.263, 0.499, 1.6348, 0.184, 'Up', -0.033599999999999984)
Record inserted
(2004, 0.184, -0.837, 0.068, 0.365, -0.263, 1.5666, 1.256, 'Up', -0.09659999999999999)
Record inserted
(2004, 1.256, 0.184, -0.837, 0.068, 0.365, 1.4776, -0.258, 'Down', 0.2072)
Record inserted
(2004, -0.258, 1.256, 0.184, -0.837, 0.068, 1.3035, 0.503, 'Up', 0.08259999999999999)
Record inserted
(2004, 0.503, -0.258, 1.256, 0.184, -0.837, 1.4039, 1.067, 'Up', 0.16959999999999997)
Record inserted
(2004, 1.067, 0.503, -0.258, 1.256, 0.184, 1.6993, -0.488, 'Down', 0.5504)
Record inserted
(2004, -0.488, 1.067, 0.503, -0.258, 1.256, 1.4643, -0.547, 'Down', 0.41600000000000004)
Record inserted
(2004, -0.547, -0.488, 1.067, 0.503, -0.258, 1.3292, 0.976, 'Up', 0.05539999999999996)
Record inserted
(2004, 0.976, -0.547, -0.488, 1.067, 0.503, 1.3965, -0.447, 'Down', 0.3022)
Record inserted
(2004, -0.447, 0.976, -0.547, -0.488, 1.067, 1.3824, -0.413, 'Down', 0.11219999999999997)
Record inserted
(2004, -0.413, -0.447, 0.976, -0.547, -0.488, 1.5628, -0.257, 'Down', -0.18380000000000002)
Record inserted
(2004, -0.257, -0.413, -0.447, 0.976, -0.547, 1.4796, -0.273, 'Down', -0.1376)
Record inserted
(2004, -0.273, -0.257, -0.413, -0.447, 0.976, 1.3804, -0.167, 'Down', -0.08280000000000003)
Record inserted

(2004, -0.167, -0.273, -0.257, -0.413, -0.447, 1.5436, 0.402, 'Up', -0.3114)
Record inserted
(2004, 0.402, -0.167, -0.273, -0.257, -0.413, 1.3607, 0.108, 'Up', -0.1416)
Record inserted
(2004, 0.108, 0.402, -0.167, -0.273, -0.257, 1.3839, 0.003, 'Up', -0.03740000000000001)
Record inserted
(2004, 0.003, 0.108, 0.402, -0.167, -0.273, 1.5404, 0.963, 'Up', 0.014599999999999991)
Record inserted
(2004, 0.963, 0.003, 0.108, 0.402, -0.167, 1.4971, -0.594, 'Down', 0.2618)
Record inserted
(2004, -0.594, 0.963, 0.003, 0.108, 0.402, 1.476, 0.168, 'Up', 0.1764)
Record inserted
(2004, 0.168, -0.594, 0.963, 0.003, 0.108, 1.3345, 0.334, 'Up', 0.1296)
Record inserted
(2004, 0.334, 0.168, -0.594, 0.963, 0.003, 1.2658, 0.172, 'Up', 0.1748)
Record inserted
(2004, 0.172, 0.334, 0.168, -0.594, 0.963, 1.3982, -0.835, 'Down', 0.20860000000000004)
Record inserted
(2004, -0.835, 0.172, 0.334, 0.168, -0.594, 1.2544, -0.577, 'Down', -0.151)
Record inserted
(2004, -0.577, -0.835, 0.172, 0.334, 0.168, 1.4994, -1.463, 'Down', -0.14759999999999998)
Record inserted
(2004, -1.463, -0.577, -0.835, 0.172, 0.334, 1.6484, -1.522, 'Down', -0.47379999999999994)
Record inserted
(2004, -1.522, -1.463, -0.577, -0.835, 0.172, 1.8899, 1.246, 'Up', -0.8450000000000001)
Record inserted
(2004, 1.246, -1.522, -1.463, -0.577, -0.835, 1.3885, -1.435, 'Down', -0.6302)
Record inserted
(2004, -1.435, 1.246, -1.522, -1.463, -0.577, 1.6006, 0.562, 'Up', -0.7502000000000001)
Record inserted
(2004, 0.562, -1.435, 1.246, -1.522, -1.463, 1.5007, 1.175, 'Up', -0.5224)
Record inserted
(2004, 1.175, 0.562, -1.435, 1.246, -1.522, 1.4901, -0.127, 'Down', 0.005200000000000005)
Record inserted
(2004, -0.127, 1.175, 0.562, -1.435, 1.246, 1.3692, -1.117, 'Down', 0.2842)
Record inserted
(2004, -1.117, -0.127, 1.175, 0.562, -1.435, 1.4574, -1.296, 'Down', -0.18839999999999998)
Record inserted
(2004, -1.296, -1.117, -0.127, 1.175, 0.562, 1.4523, -0.132, 'Down', -0.1606)
Record inserted
(2004, -0.132, -1.296, -1.117, -0.127, 1.175, 1.4582, -0.239, 'Down', -0.29939999999999994)
Record inserted
(2004, -0.239, -0.132, -1.296, -1.117, -0.127, 1.5278, 1.637, 'Up', -0.5821999999999999)
Record inserted
(2004, 1.637, -0.239, -0.132, -1.296, -1.117, 1.4717, -0.102, 'Down', -0.2294)
Record inserted
(2004, -0.102, 1.637, -0.239, -0.132, -1.296, 1.3191, 1.3, 'Up', -0.02640000000000007)
Record inserted
(2004, 1.3, -0.102, 1.637, -0.239, -0.132, 1.4055, 0.404, 'Up', 0.4928)
Record inserted
(2004, 0.404, 1.3, -0.102, 1.637, -0.239, 1.3324, -0.07, 'Down', 0.6)
Record inserted
(2004, -0.07, 0.404, 1.3, -0.102, 1.637, 1.5607, 0.529, 'Up', 0.6338)
Record inserted
(2004, 0.529, -0.07, 0.404, 1.3, -0.102, 1.5607, 0.851, 'Up', 0.41220000000000007)
Record inserted
(2004, 0.851, 0.529, -0.07, 0.404, 1.3, 1.6292, 0.767, 'Up', 0.6028)
Record inserted
(2004, 0.767, 0.851, 0.529, -0.07, 0.404, 1.4137, -0.209, 'Down', 0.4962)
Record inserted
(2004, -0.209, 0.767, 0.851, 0.529, -0.07, 1.3977, -0.665, 'Down', 0.37360000000000004)
Record inserted
(2004, -0.665, -0.209, 0.767, 0.851, 0.529, 1.4588, -0.106, 'Down', 0.25460000000000005)
Record inserted
(2004, -0.106, -0.665, -0.209, 0.767, 0.851, 1.1998, 0.516, 'Up', 0.1276)
Record inserted
(2004, 0.516, -0.106, -0.665, -0.209, 0.767, 1.1024, -1.376, 'Down', 0.06060000000000001)
Record inserted
(2004, -1.376, 0.516, -0.106, -0.665, -0.209, 1.4232, -0.112, 'Down', -0.368)
Record inserted
(2004, -0.112, -1.376, 0.516, -0.106, -0.665, 1.5477, 0.059, 'Up', -0.3486)
Record inserted
(2004, 0.059, -0.112, -1.376, 0.516, -0.106, 1.5687, 0.511, 'Up', -0.20379999999999998)
Record inserted
(2004, 0.511, 0.059, -0.112, -1.376, 0.516, 1.4878, 0.107, 'Up', -0.08039999999999996)
Record inserted
(2004, 0.107, 0.511, 0.059, -0.112, -1.376, 1.1949, -1.556, 'Down', -0.16219999999999996)
Record inserted
(2004, -1.556, 0.107, 0.511, 0.059, -0.112, 1.5085, 0.531, 'Up', -0.1982)
Record inserted
(2004, 0.531, -1.556, 0.107, 0.511, 0.059, 1.7381, 1.409, 'Up', -0.06959999999999998)
Record inserted
(2004, 1.409, 0.531, -1.556, 0.107, 0.511, 1.8267, 0.059, 'Up', 0.20039999999999997)
Record inserted
(2004, 0.059, 1.409, 0.531, -1.556, 0.107, 1.3961, -0.445, 'Down', 0.11000000000000001)
Record inserted
(2004, -0.445, 0.059, 1.409, 0.531, -1.556, 1.2906, 0.227, 'Up', -0.00039999999999995595)
Record inserted
(2004, 0.227, -0.445, 0.059, 1.409, 0.531, 1.518, -1.379, 'Down', 0.3562)
Record inserted
(2004, -1.379, 0.227, -0.445, 0.059, 1.409, 1.8556, -0.759, 'Down', -0.0258)
Record inserted
(2004, -0.759, -1.379, 0.227, -0.445, 0.059, 1.859, -0.592, 'Down', -0.4593999999999999)
Record inserted
(2004, -0.592, -0.759, -1.379, 0.227, -0.445, 1.6347, 0.92, 'Up', -0.5896)
Record inserted
(2004, 0.92, -0.592, -0.759, -1.379, 0.227, 1.5716, 0.184, 'Up', -0.3166)
Record inserted
(2004, 0.184, 0.92, -0.592, -0.759, -1.379, 1.6621, 0.177, 'Up', -0.3252)
Record inserted
(2004, 0.177, 0.184, 0.92, -0.592, -0.759, 1.469, -0.672, 'Down', -0.013999999999999967)
Record inserted
(2004, -0.672, 0.177, 0.184, 0.92, -0.592, 1.5093, -1.373, 'Down', 0.003400000000000003)
Record inserted
(2004, -1.373, -0.672, 0.177, 0.184, 0.92, 1.6536, -1.054, 'Down', -0.1528)
Record inserted
(2004, -1.054, -1.373, -0.672, 0.177, 0.184, 1.9184, 0.766, 'Up', -0.5476)
Record inserted
(2004, 0.766, -1.054, -1.373, -0.672, 0.177, 1.5338, 0.167, 'Up', -0.4312)
Record inserted
(2004, 0.167, 0.766, -1.054, -1.373, -0.672, 1.6976, -0.077, 'Down', -0.4332)
Record inserted
(2004, -0.077, 0.167, 0.766, -1.054, -1.373, 1.4111, -0.067, 'Down', -0.31420000000000003)
Record inserted
(2004, -0.067, -0.077, 0.167, 0.766, -1.054, 1.3359, -1.059, 'Down', -0.053000000000000005)
Record inserted
(2004, -1.059, -0.067, -0.077, 0.167, 0.766, 1.4301, 0.682, 'Up', -0.05399999999999996)
Record inserted
(2004, 0.682, -1.059, -0.067, -0.077, 0.167, 1.353, -0.257, 'Down', -0.07079999999999997)
Record inserted
(2004, -0.257, 0.682, -1.059, -0.067, -0.077, 1.5486, 0.047, 'Up', -0.15559999999999996)
Record inserted
(2004, 0.047, -0.257, 0.682, -1.059, -0.067, 1.211, 0.401, 'Up', -0.13079999999999997)
Record inserted
(2004, 0.401, 0.047, -0.257, 0.682, -1.059, 1.2586, 0.169, 'Up', -0.03719999999999999)
Record inserted
(2004, 0.169, 0.401, 0.047, -0.257, 0.682, 1.2275, 1.61, 'Up', 0.20840000000000006)
Record inserted
(2004, 1.61, 0.169, 0.401, 0.047, -0.257, 1.5457, 0.17, 'Up', 0.394)
Record inserted
(2004, 0.17, 1.61, 0.169, 0.401, 0.047, 1.3694, 0.569, 'Up', 0.47940000000000005)
Record inserted
(2004, 0.569, 0.17, 1.61, 0.169, 0.401, 1.4475, -0.054, 'Down', 0.5838000000000001)
Record inserted
(2004, -0.054, 0.569, 0.17, 1.61, 0.169, 1.1726, 0.046, 'Up', 0.4928)
Record inserted
(2004, 0.046, -0.054, 0.569, 0.17, 1.61, 1.238, 0.338, 'Up', 0.46820000000000006)
Record inserted
(2004, 0.338, 0.046, -0.054, 0.569, 0.17, 1.2517, -0.742, 'Down', 0.2138)
Record inserted
(2004, -0.742, 0.338, 0.046, -0.054, 0.569, 1.2324, 0.525, 'Up', 0.0314)
Record inserted
(2004, 0.525, -0.742, 0.338, 0.046, -0.054, 1.1153, 1.596, 'Up', 0.02260000000000001)
Record inserted
(2004, 1.596, 0.525, -0.742, 0.338, 0.046, 1.2118, 0.154, 'Up', 0.3526)
Record inserted
(2004, 0.154, 1.596, 0.525, -0.742, 0.338, 1.1903, -0.95, 'Down', 0.3742)
Record inserted
(2004, -0.95, 0.154, 1.596, 0.525, -0.742, 1.2768, 0.454, 'Up', 0.11660000000000004)
Record inserted
(2004, 0.454, -0.95, 0.154, 1.596, 0.525, 1.1606, -0.984, 'Down', 0.3558)
Record inserted
(2004, -0.984, 0.454, -0.95, 0.154, 1.596, 1.1794, 0.597, 'Up', 0.054000000000000006)
Record inserted
(2004, 0.597, -0.984, 0.454, -0.95, 0.154, 1.3459, 0.137, 'Up', -0.14579999999999999)
Record inserted
(2004, 0.137, 0.597, -0.984, 0.454, -0.95, 1.1684, -0.133, 'Down', -0.1492)
Record inserted
(2004, -0.133, 0.137, 0.597, -0.984, 0.454, 1.2967, 0.262, 'Up', 0.0142)
Record inserted
(2004, 0.262, -0.133, 0.137, 0.597, -0.984, 1.5006, -0.416, 'Down', -0.0242)
Record inserted
(2004, -0.416, 0.262, -0.133, 0.137, 0.597, 1.1239, 0.364, 'Up', 0.08940000000000001)
Record inserted
(2004, 0.364, -0.416, 0.262, -0.133, 0.137, 1.3823, 0.851, 'Up', 0.042800000000000005)
Record inserted
(2004, 0.851, 0.364, -0.416, 0.262, -0.133, 1.4442, -0.298, 'Down', 0.1856)
Record inserted
(2004, -0.298, 0.851, 0.364, -0.416, 0.262, 1.3949, -0.545, 'Down', 0.15259999999999999)
Record inserted
(2004, -0.545, -0.298, 0.851, 0.364, -0.416, 1.8129, -0.095, 'Down', -0.008799999999999997)
Record inserted
(2004, -0.095, -0.545, -0.298, 0.851, 0.364, 1.3546, 0.251, 'Up', 0.055400000000000005)
Record inserted
(2004, 0.251, -0.095, -0.545, -0.298, 0.851, 1.375, 0.408, 'Up', 0.03279999999999998)
Record inserted
(2004, 0.408, 0.251, -0.095, -0.545, -0.298, 1.4738, -1.043, 'Down', -0.055799999999999995)
Record inserted
(2004, -1.043, 0.408, 0.251, -0.095, -0.545, 1.4957, -0.315, 'Down', -0.2048)
Record inserted
(2004, -0.315, -1.043, 0.408, 0.251, -0.095, 1.085, -0.815, 'Down', -0.1588)
Record inserted
(2004, -0.815, -0.315, -1.043, 0.408, 0.251, 1.2833, 0.19, 'Up', -0.30280000000000007)
Record inserted
(2004, 0.19, -0.815, -0.315, -1.043, 0.408, 1.3286, -0.824, 'Down', -0.315)
Record inserted
(2004, -0.824, 0.19, -0.815, -0.315, -1.043, 1.4011, 0.334, 'Up', -0.5613999999999999)
Record inserted
(2004, 0.334, -0.824, 0.19, -0.815, -0.315, 1.1863, 0.138, 'Up', -0.2859999999999999)
Record inserted
(2004, 0.138, 0.334, -0.824, 0.19, -0.815, 1.1146, 0.071, 'Up', -0.19539999999999996)
Record inserted
(2004, 0.071, 0.138, 0.334, -0.824, 0.19, 1.1997, -0.329, 'Down', -0.018199999999999984)
Record inserted
(2004, -0.329, 0.071, 0.138, 0.334, -0.824, 1.462, -0.43, 'Down', -0.12199999999999997)
Record inserted
(2004, -0.43, -0.329, 0.071, 0.138, 0.334, 1.4087, -0.479, 'Down', -0.0432)
Record inserted
(2004, -0.479, -0.43, -0.329, 0.071, 0.138, 1.4503, -0.044, 'Down', -0.20579999999999998)
Record inserted
(2004, -0.044, -0.479, -0.43, -0.329, 0.071, 1.3199, 0.706, 'Up', -0.24220000000000003)
Record inserted
(2004, 0.706, -0.044, -0.479, -0.43, -0.329, 1.4458, -1.334, 'Down', -0.11520000000000001)
Record inserted
(2004, -1.334, 0.706, -0.044, -0.479, -0.43, 1.6795, 0.271, 'Up', -0.31620000000000004)
Record inserted
(2004, 0.271, -1.334, 0.706, -0.044, -0.479, 1.6808, -0.97, 'Down', -0.17600000000000002)
Record inserted
(2004, -0.97, 0.271, -1.334, 0.706, -0.044, 1.3375, -0.196, 'Down', -0.2742)
Record inserted
(2004, -0.196, -0.97, 0.271, -1.334, 0.706, 1.4134, 0.993, 'Up', -0.30460000000000004)
Record inserted
(2004, 0.993, -0.196, -0.97, 0.271, -1.334, 1.6108, 0.054, 'Up', -0.24720000000000003)
Record inserted
(2004, 0.054, 0.993, -0.196, -0.97, 0.271, 1.5543, 0.457, 'Up', 0.030400000000000003)
Record inserted
(2004, 0.457, 0.054, 0.993, -0.196, -0.97, 1.5301, 0.117, 'Up', 0.06760000000000002)
Record inserted
(2004, 0.117, 0.457, 0.054, 0.993, -0.196, 1.2982, 0.445, 'Up', 0.28500000000000003)
Record inserted
(2004, 0.445, 0.117, 0.457, 0.054, 0.993, 1.276, -0.626, 'Down', 0.41320000000000007)
Record inserted
(2004, -0.626, 0.445, 0.117, 0.457, 0.054, 1.3383, -0.096, 'Down', 0.08940000000000001)
Record inserted
(2004, -0.096, -0.626, 0.445, 0.117, 0.457, 1.3692, -1.632, 'Down', 0.05940000000000001)
Record inserted
(2004, -1.632, -0.096, -0.626, 0.445, 0.117, 1.3974, -1.548, 'Down', -0.3584)
Record inserted
(2004, -1.548, -1.632, -0.096, -0.626, 0.445, 1.521, 0.117, 'Up', -0.6914)
Record inserted
(2004, 0.117, -1.548, -1.632, -0.096, -0.626, 1.086, 1.297, 'Up', -0.7569999999999999)

Record inserted
(2004, 1.297, 0.117, -1.548, -1.632, -0.096, 1.2456, -0.301, 'Down', -0.3724)
Record inserted
(2004, -0.301, 1.297, 0.117, -1.548, -1.632, 1.4104, -1.168, 'Down', -0.41340000000000005)
Record inserted
(2004, -1.168, -0.301, 1.297, 0.117, -1.548, 1.4051, 0.148, 'Up', -0.3206)
Record inserted
(2004, 0.148, -1.168, -0.301, 1.297, 0.117, 1.1751, 1.366, 'Up', 0.0186)
Record inserted
(2004, 1.366, 0.148, -1.168, -0.301, 1.297, 1.2062, 0.22, 'Up', 0.2684)
Record inserted
(2004, 0.22, 1.366, 0.148, -1.168, -0.301, 1.2678, 1.244, 'Up', 0.05300000000000001)
Record inserted
(2004, 1.244, 0.22, 1.366, 0.148, -1.168, 1.2825, -0.36, 'Down', 0.36200000000000004)
Record inserted
(2004, -0.36, 1.244, 0.22, 1.366, 0.148, 1.2494, 0.652, 'Up', 0.5236000000000001)
Record inserted
(2004, 0.652, -0.36, 1.244, 0.22, 1.366, 1.1999, -0.243, 'Down', 0.6244)
Record inserted
(2004, -0.243, 0.652, -0.36, 1.244, 0.22, 1.0219, 0.047, 'Up', 0.30260000000000004)
Record inserted
(2004, 0.047, -0.243, 0.652, -0.36, 1.244, 1.0925, 0.8, 'Up', 0.268)
Record inserted
(2004, 0.8, 0.047, -0.243, 0.652, -0.36, 1.1922, 0.012, 'Up', 0.17920000000000005)
Record inserted
(2004, 0.012, 0.8, 0.047, -0.243, 0.652, 1.0236, 0.243, 'Up', 0.25360000000000005)
Record inserted
(2004, 0.243, 0.012, 0.8, 0.047, -0.243, 0.8454, -0.778, 'Down', 0.1718)
Record inserted
(2004, -0.778, 0.243, 0.012, 0.8, 0.047, 0.8431, 0.463, 'Up', 0.0648)
Record inserted
(2004, 0.463, -0.778, 0.243, 0.012, 0.8, 1.1382, 0.151, 'Up', 0.148)
Record inserted
(2004, 0.151, 0.463, -0.778, 0.243, 0.012, 1.1421, 1.121, 'Up', 0.01819999999999999)
Record inserted
(2004, 1.121, 0.151, 0.463, -0.778, 0.243, 1.1184, -0.418, 'Down', 0.24000000000000005)
Record inserted
(2004, -0.418, 1.121, 0.151, 0.463, -0.778, 0.92417, 0.689, 'Up', 0.10780000000000003)
Record inserted
(2004, 0.689, -0.418, 1.121, 0.151, 0.463, 1.2144, -0.449, 'Down', 0.40119999999999995)
Record inserted
(2004, -0.449, 0.689, -0.418, 1.121, 0.151, 1.2463, 0.189, 'Up', 0.21879999999999997)
Record inserted
(2004, 0.189, -0.449, 0.689, -0.418, 1.121, 1.3713, 0.495, 'Up', 0.2264)
Record inserted
(2004, 0.495, 0.189, -0.449, 0.689, -0.418, 1.2612, 0.169, 'Up', 0.1012)
Record inserted
(2004, 0.169, 0.495, 0.189, -0.449, 0.689, 1.2998, 0.223, 'Up', 0.2186)
Record inserted
(2004, 0.223, 0.169, 0.495, 0.189, -0.449, 1.2045, -0.705, 'Down', 0.1254)
Record inserted
(2004, -0.705, 0.223, 0.169, 0.495, 0.189, 1.256, 0.279, 'Up', 0.07420000000000002)
Record inserted
(2004, 0.279, -0.705, 0.223, 0.169, 0.495, 1.1139, 0.449, 'Up', 0.09220000000000002)
Record inserted
(2004, 0.449, 0.279, -0.705, 0.223, 0.169, 1.4226, -0.563, 'Down', 0.083)
Record inserted
(2004, -0.563, 0.449, 0.279, -0.705, 0.223, 1.1976, 0.633, 'Up', -0.06339999999999997)
Record inserted
(2004, 0.633, -0.563, 0.449, 0.279, -0.705, 1.325, -1.394, 'Down', 0.01860000000000004)
Record inserted
(2004, -1.394, 0.633, -0.563, 0.449, 0.279, 1.3799, -0.467, 'Down', -0.11919999999999994)
Record inserted
(2004, -0.467, -1.394, 0.633, -0.563, 0.449, 1.2863, 0.158, 'Up', -0.26839999999999997)
Record inserted
(2004, 0.158, -0.467, -1.394, 0.633, -0.563, 1.2554, -0.594, 'Down', -0.32659999999999995)
Record inserted
(2004, -0.594, 0.158, -0.467, -1.394, 0.633, 1.2635, 0.593, 'Up', -0.33279999999999993)
Record inserted
(2004, 0.593, -0.594, 0.158, -0.467, -1.394, 1.3966, 0.427, 'Up', -0.3408)
Record inserted
(2004, 0.427, 0.593, -0.594, 0.158, -0.467, 1.4029, -0.02, 'Down', 0.02340000000000001)
Record inserted
(2004, -0.02, 0.427, 0.593, -0.594, 0.158, 1.748, 1.518, 'Up', 0.11280000000000001)
Record inserted
(2004, 1.518, -0.02, 0.427, 0.593, -0.594, 1.5822, 0.324, 'Up', 0.3848)
Record inserted
(2004, 0.324, 1.518, -0.02, 0.427, 0.593, 1.534, -0.061, 'Down', 0.5684)
Record inserted
(2004, -0.061, 0.324, 1.518, -0.02, 0.427, 1.4184, 0.667, 'Up', 0.43760000000000004)
Record inserted
(2004, 0.667, -0.061, 0.324, 1.518, -0.02, 1.4167, -0.998, 'Down', 0.4856000000000001)
Record inserted
(2004, -0.998, 0.667, -0.061, 0.324, 1.518, 1.4475, -0.753, 'Down', 0.29000000000000004)
Record inserted
(2004, -0.753, -0.998, 0.667, -0.061, 0.324, 1.2916, 0.201, 'Up', -0.16419999999999996)
Record inserted
(2004, 0.201, -0.753, -0.998, 0.667, -0.061, 0.9438, -0.227, 'Down', -0.1888)
Record inserted
(2004, -0.227, 0.201, -0.753, -0.998, 0.667, 1.3201, -0.73, 'Down', -0.22200000000000003)
Record inserted
(2004, -0.73, -0.227, 0.201, -0.753, -0.998, 1.5462, -0.93, 'Down', -0.5014)
Record inserted
(2004, -0.93, -0.73, -0.227, 0.201, -0.753, 1.4895, 0.445, 'Up', -0.4878)
Record inserted
(2004, 0.445, -0.93, -0.73, -0.227, 0.201, 1.6451, 0.525, 'Up', -0.24820000000000003)
Record inserted
(2004, 0.525, 0.445, -0.93, -0.73, -0.227, 1.3733, -0.969, 'Down', -0.1834)
Record inserted
(2004, -0.969, 0.525, 0.445, -0.93, -0.73, 1.7375, 0.039, 'Up', -0.3318)
Record inserted
(2004, 0.039, -0.969, 0.525, 0.445, -0.93, 1.6857, 0.256, 'Up', -0.178)
Record inserted
(2004, 0.256, 0.039, -0.969, 0.525, 0.445, 1.673, -0.972, 'Down', 0.059200000000000016)
Record inserted
(2004, -0.972, 0.256, 0.039, -0.969, 0.525, 1.4696, -0.086, 'Down', -0.2242)
Record inserted
(2004, -0.086, -0.972, 0.256, 0.039, -0.969, 1.3805, 1.488, 'Up', -0.3464)
Record inserted
(2004, 1.488, -0.086, -0.972, 0.256, 0.039, 1.6854, 1.288, 'Up', 0.145)
Record inserted
(2004, 1.288, 1.488, -0.086, -0.972, 0.256, 1.7419, 0.181, 'Up', 0.3948)
Record inserted
(2004, 0.181, 1.288, 1.488, -0.086, -0.972, 1.6282, 0.245, 'Up', 0.3798)
Record inserted
(2004, 0.245, 0.181, 1.288, 1.488, -0.086, 1.5008, 0.027, 'Up', 0.6232)
Record inserted
(2004, 0.027, 0.245, 0.181, 1.288, 1.488, 1.3959, 0.004, 'Up', 0.6458)
Record inserted
(2004, 0.004, 0.027, 0.245, 0.181, 1.288, 1.659, 1.118, 'Up', 0.34900000000000003)
Record inserted
(2004, 1.118, 0.004, 0.027, 0.245, 0.181, 1.7675, 1.616, 'Up', 0.31500000000000006)
Record inserted
(2004, 1.616, 1.118, 0.004, 0.027, 0.245, 1.7827, 0.387, 'Up', 0.6020000000000001)
Record inserted
(2004, 0.387, 1.616, 1.118, 0.004, 0.027, 1.7244, -0.11, 'Down', 0.6304000000000001)
Record inserted
(2004, -0.11, 0.387, 1.616, 1.118, 0.004, 1.3587, -0.07, 'Down', 0.603)
Record inserted
(2004, -0.07, -0.11, 0.387, 1.616, 1.118, 1.4508, -0.101, 'Down', 0.5882000000000001)
Record inserted
(2004, -0.101, -0.07, -0.11, 0.387, 1.616, 1.5043, 0.909, 'Up', 0.3444)
Record inserted
(2004, 0.909, -0.101, -0.07, -0.11, 0.387, 1.393, 0.911, 'Up', 0.203)
Record inserted
(2004, 0.911, 0.909, -0.101, -0.07, -0.11, 1.5316, -0.03, 'Down', 0.30779999999999996)
Record inserted
(2004, -0.03, 0.911, 0.909, -0.101, -0.07, 1.4533, -0.708, 'Down', 0.3238)
Record inserted
(2004, -0.708, -0.03, 0.911, 0.909, -0.101, 1.3644, 0.554, 'Up', 0.1962)
Record inserted
(2004, 0.554, -0.708, -0.03, 0.911, 0.909, 1.6842, 0.136, 'Up', 0.32720000000000005)
Record inserted
(2004, 0.136, 0.554, -0.708, -0.03, 0.911, 1.4567, -1.116, 'Down', 0.17260000000000003)
Record inserted
(2004, -1.116, 0.136, 0.554, -0.708, -0.03, 1.5266, 0.59, 'Up', -0.23279999999999998)
Record inserted
(2004, 0.59, -1.116, 0.136, 0.554, -0.708, 1.3927, -0.025, 'Down', -0.10880000000000001)
Record inserted
(2004, -0.025, 0.59, -1.116, 0.136, 0.554, 1.4283, 0.41, 'Up', 0.02779999999999998)
Record inserted
(2004, 0.41, -0.025, 0.59, -1.116, 0.136, 1.1496, 0.075, 'Up', -0.0010000000000000453)
Record inserted
(2004, 0.075, 0.41, -0.025, 0.59, -1.116, 0.50458, -0.345, 'Down', -0.013200000000000055)
Record inserted
(2004, -0.345, 0.075, 0.41, -0.025, 0.59, 1.3785, -0.403, 'Down', 0.141)
Record inserted
(2004, -0.403, -0.345, 0.075, 0.41, -0.025, 1.5535, 1.495, 'Up', -0.05760000000000002)
Record inserted
(2004, 1.495, -0.403, -0.345, 0.075, 0.41, 1.7728, -0.087, 'Down', 0.2464)
Record inserted
(2004, -0.087, 1.495, -0.403, -0.345, 0.075, 1.7749, 0.071, 'Up', 0.14700000000000002)
Record inserted
(2004, 0.071, -0.087, 1.495, -0.403, -0.345, 1.5667, -0.077, 'Down', 0.14620000000000002)
Record inserted
(2004, -0.077, 0.071, -0.087, 1.495, -0.403, 1.3544, -1.107, 'Down', 0.19980000000000003)
Record inserted
(2004, -1.107, -0.077, 0.071, -0.087, 1.495, 1.5339, 0.488, 'Up', 0.05900000000000003)
Record inserted
(2004, 0.488, -1.107, -0.077, 0.071, -0.087, 1.5252, 0.544, 'Up', -0.1424)
Record inserted
(2004, 0.544, 0.488, -1.107, -0.077, 0.071, 1.6247, -0.104, 'Down', -0.016199999999999996)
Record inserted
(2004, -0.104, 0.544, 0.488, -1.107, -0.077, 1.4437, 0.899, 'Up', -0.05119999999999999)
Record inserted
(2004, 0.899, -0.104, 0.544, 0.488, -1.107, 1.4361, 0.392, 'Up', 0.144)
Record inserted
(2004, 0.392, 0.899, -0.104, 0.544, 0.488, 1.5444, 0.194, 'Up', 0.4438)
Record inserted
(2004, 0.194, 0.392, 0.899, -0.104, 0.544, 1.6958, -0.208, 'Down', 0.385)
Record inserted
(2004, -0.208, 0.194, 0.392, 0.899, -0.104, 1.7939, -0.749, 'Down', 0.2346)
Record inserted
(2004, -0.749, -0.208, 0.194, 0.392, 0.899, 2.335, 0.038, 'Up', 0.10560000000000003)
Record inserted
(2004, 0.038, -0.749, -0.208, 0.194, 0.392, 1.4228, 0.904, 'Up', -0.06659999999999996)
Record inserted
(2004, 0.904, 0.038, -0.749, -0.208, 0.194, 1.4837, 0.342, 'Up', 0.03580000000000001)
Record inserted

(2004, 0.342, 0.904, 0.038, -0.749, -0.208, 1.3908, 0.046, 'Up', 0.06540000000000001)
Record inserted
(2004, 0.046, 0.342, 0.904, 0.038, -0.749, 0.9561, -0.431, 'Down', 0.11620000000000001)
Record inserted
(2004, -0.431, 0.046, 0.342, 0.904, 0.038, 0.922, 0.715, 'Up', 0.17980000000000002)
Record inserted
(2004, 0.715, -0.431, 0.046, 0.342, 0.904, 0.983, -0.007, 'Down', 0.31520000000000004)
Record inserted
(2004, -0.007, 0.715, -0.431, 0.046, 0.342, 0.9259, 0.008, 'Up', 0.133)
Record inserted
(2004, 0.008, -0.007, 0.715, -0.431, 0.046, 0.8298, -0.134, 'Down', 0.0662)
Record inserted
(2005, -0.134, 0.008, -0.007, 0.715, -0.431, 0.7869, -0.812, 'Down', 0.030199999999999994)
Record inserted
(2005, -0.812, -0.134, 0.008, -0.007, 0.715, 1.5108, -1.167, 'Down', -0.04600000000000002)
Record inserted
(2005, -1.167, -0.812, -0.134, 0.008, -0.007, 1.721, -0.363, 'Down', -0.4224)
Record inserted
(2005, -0.363, -1.167, -0.812, -0.134, 0.008, 1.7389, 0.351, 'Up', -0.4936)
Record inserted
(2005, 0.351, -0.363, -1.167, -0.812, -0.134, 1.5691, -0.143, 'Down', -0.425)
Record inserted
(2005, -0.143, 0.351, -0.363, -1.167, -0.812, 1.4779, 0.342, 'Up', -0.42680000000000007)
Record inserted
(2005, 0.342, -0.143, 0.351, -0.363, -1.167, 1.4904, -0.61, 'Down', -0.196)
Record inserted
(2005, -0.61, 0.342, -0.143, 0.351, -0.363, 1.4888, 0.398, 'Up', -0.08459999999999998)
Record inserted
(2005, 0.398, -0.61, 0.342, -0.143, 0.351, 1.5621, -0.863, 'Down', 0.06760000000000002)
Record inserted
(2005, -0.863, 0.398, -0.61, 0.342, -0.143, 1.5103, 0.6, 'Up', -0.17519999999999997)
Record inserted
(2005, 0.6, -0.863, 0.398, -0.61, 0.342, 1.3354, 0.967, 'Up', -0.02659999999999999)
Record inserted
(2005, 0.967, 0.6, -0.863, 0.398, -0.61, 1.5968, -0.949, 'Down', 0.09839999999999997)
Record inserted
(2005, -0.949, 0.967, 0.6, -0.863, 0.398, 1.4987, -0.778, 'Down', 0.030600000000000006)
Record inserted
(2005, -0.778, -0.949, 0.967, 0.6, -0.863, 1.692, -0.641, 'Down', -0.20459999999999998)
Record inserted
(2005, -0.641, -0.778, -0.949, 0.967, 0.6, 1.6435, -0.353, 'Down', -0.16019999999999995)
Record inserted
(2005, -0.353, -0.641, -0.778, -0.949, 0.967, 1.4946, 0.4, 'Up', -0.3508)
Record inserted
(2005, 0.4, -0.353, -0.641, -0.778, -0.949, 1.6104, 0.484, 'Up', -0.46419999999999995)
Record inserted
(2005, 0.484, 0.4, -0.353, -0.641, -0.778, 1.6359, 0.041, 'Up', -0.1776)
Record inserted
(2005, 0.041, 0.484, 0.4, -0.353, -0.641, 1.6006, -0.272, 'Down', -0.01379999999999999)
Record inserted
(2005, -0.272, 0.041, 0.484, 0.4, -0.353, 1.6418, 0.846, 'Up', 0.06000000000000001)
Record inserted
(2005, 0.846, -0.272, 0.041, 0.484, 0.4, 1.6798, 0.689, 'Up', 0.2998)
Record inserted
(2005, 0.689, 0.846, -0.272, 0.041, 0.484, 1.68198, 0.318, 'Up', 0.3576)
Record inserted
(2005, 0.318, 0.689, 0.846, -0.272, 0.041, 1.56174, -0.277, 'Down', 0.3243999999999999)
Record inserted
(2005, -0.277, 0.318, 0.689, 0.846, -0.272, 1.55446, 1.104, 'Up', 0.26080000000000003)
Record inserted
(2005, 1.104, -0.277, 0.318, 0.689, 0.846, 1.64816, -0.109, 'Down', 0.536)
Record inserted
(2005, -0.109, 1.104, -0.277, 0.318, 0.689, 1.34727, 0.048, 'Up', 0.34500000000000003)
Record inserted
(2005, 0.048, -0.109, 1.104, -0.277, 0.318, 1.41617, -0.858, 'Down', 0.21680000000000002)
Record inserted
(2005, -0.858, 0.048, -0.109, 1.104, -0.277, 1.51104, 0.421, 'Up', -0.018399999999999972)
Record inserted
(2005, 0.421, -0.858, 0.048, -0.109, 1.104, 1.49167, 0.693, 'Up', 0.12120000000000002)
Record inserted
(2005, 0.693, 0.421, -0.858, 0.048, -0.109, 1.5623, 0.07, 'Up', 0.03899999999999998)
Record inserted
(2005, 0.07, 0.693, 0.421, -0.858, 0.048, 1.29018, 0.33, 'Up', 0.07479999999999999)
Record inserted
(2005, 0.33, 0.07, 0.693, 0.421, -0.858, 1.52708, 0.018, 'Up', 0.1312)
Record inserted
(2005, 0.018, 0.33, 0.07, 0.693, 0.421, 1.4901, -0.792, 'Down', 0.3064)
Record inserted
(2005, -0.792, 0.018, 0.33, 0.07, 0.693, 1.58012, 0.07, 'Up', 0.0638)
Record inserted
(2005, 0.07, -0.792, 0.018, 0.33, 0.07, 1.5512, -1.451, 'Down', -0.060799999999999986)
Record inserted
(2005, -1.451, 0.07, -0.792, 0.018, 0.33, 1.74494, 0.561, 'Up', -0.36500000000000005)
Record inserted
(2005, 0.561, -1.451, 0.07, -0.792, 0.018, 1.50109, 0.789, 'Up', -0.31880000000000003)
Record inserted
(2005, 0.789, 0.561, -1.451, 0.07, -0.792, 1.51875, 0.931, 'Up', -0.1646)
Record inserted
(2005, 0.931, 0.789, 0.561, -1.451, 0.07, 1.52368, -0.641, 'Down', 0.18000000000000002)
Record inserted
(2005, -0.641, 0.931, 0.789, 0.561, -1.451, 1.79548, 0.566, 'Up', 0.037800000000000014)
Record inserted
(2005, 0.566, -0.641, 0.931, 0.789, 0.561, 1.70806, -0.027, 'Down', 0.4412)
Record inserted
(2005, -0.027, 0.566, -0.641, 0.931, 0.789, 1.56854, 0.032, 'Up', 0.3236)
Record inserted
(2005, 0.032, -0.027, 0.566, -0.641, 0.931, 1.61624, 0.962, 'Up', 0.1722)
Record inserted
(2005, 0.962, 0.032, -0.027, 0.566, -0.641, 1.63682, 0.261, 'Up', 0.17839999999999998)
Record inserted
(2005, 0.261, 0.962, 0.032, -0.027, 0.566, 1.48883, -0.48, 'Down', 0.3588)
Record inserted
(2005, -0.48, 0.261, 0.962, 0.032, -0.027, 1.52309, -1.019, 'Down', 0.1496)
Record inserted
(2005, -1.019, -0.48, 0.261, 0.962, 0.032, 1.70497, 0.186, 'Up', -0.0488)
Record inserted
(2005, 0.186, -1.019, -0.48, 0.261, 0.962, 1.60402, -0.758, 'Down', -0.018000000000000016)
Record inserted
(2005, -0.758, 0.186, -1.019, -0.48, 0.261, 1.44982, 0.562, 'Up', -0.36199999999999993)
Record inserted
(2005, 0.562, -0.758, 0.186, -1.019, -0.48, 1.43743, -0.752, 'Down', -0.30179999999999996)
Record inserted
(2005, -0.752, 0.562, -0.758, 0.186, -1.019, 1.51353, -0.808, 'Down', -0.35619999999999996)
Record inserted
(2005, -0.808, -0.752, 0.562, -0.758, 0.186, 1.65319, 0.18, 'Up', -0.314)
Record inserted
(2005, 0.18, -0.808, -0.752, 0.562, -0.758, 1.58193, -0.047, 'Down', -0.31520000000000004)
Record inserted
(2005, -0.047, 0.18, -0.808, -0.752, 0.562, 2.34437, -0.493, 'Down', -0.173)
Record inserted
(2005, -0.493, -0.047, 0.18, -0.808, -0.752, 1.81944, -1.02, 'Down', -0.384)
Record inserted
(2005, -1.02, -0.493, -0.047, 0.18, -0.808, 2.11447, 0.07, 'Up', -0.43759999999999993)
Record inserted
(2005, 0.07, -1.02, -0.493, -0.047, 0.18, 2.24687, -0.095, 'Down', -0.262)
Record inserted
(2005, -0.095, 0.07, -1.02, -0.493, -0.047, 1.72172, 0.244, 'Up', -0.31699999999999995)
Record inserted
(2005, 0.244, -0.095, 0.07, -1.02, -0.493, 1.74622, -0.76, 'Down', -0.25880000000000003)
Record inserted
(2005, -0.76, 0.244, -0.095, 0.07, -1.02, 2.22325, 1.377, 'Up', -0.3122)
Record inserted
(2005, 1.377, -0.76, 0.244, -0.095, 0.07, 2.09711, -0.069, 'Down', 0.16720000000000002)
Record inserted
(2005, -0.069, 1.377, -0.76, 0.244, -0.095, 2.21423, -0.65, 'Down', 0.13940000000000002)
Record inserted
(2005, -0.65, -0.069, 1.377, -0.76, 0.244, 2.16869, 0.273, 'Up', 0.02839999999999998)
Record inserted
(2005, 0.273, -0.65, -0.069, 1.377, -0.76, 2.07977, 0.448, 'Up', 0.03420000000000001)
Record inserted
(2005, 0.448, 0.273, -0.65, -0.069, 1.377, 1.8708, 0.227, 'Up', 0.2758)
Record inserted
(2005, 0.227, 0.448, 0.273, -0.65, -0.069, 1.7974, 0.597, 'Up', 0.04580000000000001)
Record inserted
(2005, 0.597, 0.227, 0.448, 0.273, -0.65, 1.90062, -0.834, 'Down', 0.179)
Record inserted
(2005, -0.834, 0.597, 0.227, 0.448, 0.273, 1.66133, 0.001, 'Up', 0.14220000000000002)
Record inserted
(2005, 0.001, -0.834, 0.597, 0.227, 0.448, 1.52531, 0.555, 'Up', 0.08780000000000002)
Record inserted
(2005, 0.555, 0.001, -0.834, 0.597, 0.227, 1.97983, -1.176, 'Down', 0.1092)
Record inserted
(2005, -1.176, 0.555, 0.001, -0.834, 0.597, 2.04974, -1.0, 'Down', -0.17139999999999994)
Record inserted
(2005, -1.0, -1.176, 0.555, 0.001, -0.834, 2.35504, -1.672, 'Down', -0.4908)
Record inserted
(2005, -1.672, -1.0, -1.176, 0.555, 0.001, 2.68996, 0.294, 'Up', -0.6584)
Record inserted
(2005, 0.294, -1.672, -1.0, -1.176, 0.555, 2.18067, 0.593, 'Up', -0.5998)
Record inserted
(2005, 0.593, 0.294, -1.672, -1.0, -1.176, 2.1427, -1.325, 'Down', -0.5922)
Record inserted
(2005, -1.325, 0.593, 0.294, -1.672, -1.0, 2.21705, 1.974, 'Up', -0.622)
Record inserted
(2005, 1.974, -1.325, 0.593, 0.294, -1.672, 2.30856, -0.675, 'Down', -0.02719999999999998)
Record inserted
(2005, -0.675, 1.974, -1.325, 0.593, 0.294, 2.04588, 0.866, 'Up', 0.1722)
Record inserted
(2005, 0.866, -0.675, 1.974, -1.325, 0.593, 1.79503, -0.884, 'Down', 0.2866)
Record inserted
(2005, -0.884, 0.866, -0.675, 1.974, -1.325, 1.95974, 0.395, 'Up', -0.008800000000000007)
Record inserted
(2005, 0.395, -0.884, 0.866, -0.675, 1.974, 2.15152, -1.138, 'Down', 0.3352)
Record inserted
(2005, -1.138, 0.395, -0.884, 0.866, -0.675, 2.18227, 1.192, 'Up', -0.2872)
Record inserted
(2005, 1.192, -1.138, 0.395, -0.884, 0.866, 2.36236, 0.459, 'Up', 0.08620000000000001)
Record inserted
(2005, 0.459, 1.192, -1.138, 0.395, -0.884, 1.98004, -0.085, 'Down', 0.0048000000000000265)
Record inserted
(2005, -0.085, 0.459, 1.192, -1.138, 0.395, 2.16702, 1.247, 'Up', 0.1646)
Record inserted
(2005, 1.247, -0.085, 0.459, 1.192, -1.138, 2.30648, -0.257, 'Down', 0.3350000000000001)
Record inserted
(2005, -0.257, 1.247, -0.085, 0.459, 1.192, 1.9971, -0.109, 'Down', 0.5112)
Record inserted
(2005, -0.109, -0.257, 1.247, -0.085, 0.459, 1.7072, 0.639, 'Up', 0.251)
Record inserted
(2005, 0.639, -0.109, -0.257, 1.247, -0.085, 1.85702, -1.071, 'Down', 0.28700000000000003)
Record inserted
(2005, -1.071, 0.639, -0.109, -0.257, 1.247, 1.88966, 0.419, 'Up', 0.08980000000000003)
Record inserted
(2005, 0.419, -1.071, 0.639, -0.109, -0.257, 1.83497, -1.003, 'Down', -0.07579999999999998)
Record inserted
(2005, -1.003, 0.419, -1.071, 0.639, -0.109, 1.99529, -0.458, 'Down', -0.22499999999999995)
Record inserted
(2005, -0.458, -1.003, 0.419, -1.071, 0.639, 2.18859, 1.009, 'Up', -0.2947999999999999)
Record inserted
(2005, 1.009, -0.458, -1.003, 0.419, -1.071, 1.85686, 0.696, 'Up', -0.22079999999999997)
Record inserted
(2005, 0.696, 1.009, -0.458, -1.003, 0.419, 1.88726, 1.002, 'Up', 0.1326)
Record inserted
(2005, 1.002, 0.696, 1.009, -0.458, -1.003, 2.26632, 0.466, 'Up', 0.24919999999999995)
Record inserted
(2005, 0.466, 1.002, 0.696, 1.009, -0.458, 1.77586, -0.151, 'Down', 0.5429999999999999)
Record inserted
(2005, -0.151, 0.466, 1.002, 0.696, 1.009, 1.63175, 0.385, 'Up', 0.6043999999999999)
Record inserted
(2005, 0.385, -0.151, 0.466, 1.002, 0.696, 1.68117, 0.018, 'Up', 0.4795999999999999)
Record inserted
(2005, 0.018, 0.385, -0.151, 0.466, 1.002, 1.681, -0.34, 'Down', 0.344)
Record inserted

(2005, -0.34, 0.018, 0.385, -0.151, 0.466, 1.74218, 0.639, 'Up', 0.0756)
Record inserted
(2005, 0.639, -0.34, 0.018, 0.385, -0.151, 1.65411, 0.097, 'Up', 0.11019999999999999)
Record inserted
(2005, 0.097, 0.639, -0.34, 0.018, 0.385, 1.38143, -0.607, 'Down', 0.1598)
Record inserted
(2005, -0.607, 0.097, 0.639, -0.34, 0.018, 1.84068, 0.9, 'Up', -0.03860000000000001)
Record inserted
(2005, 0.9, -0.607, 0.097, 0.639, -0.34, 1.8101, 0.172, 'Up', 0.13779999999999998)
Record inserted
(2005, 0.172, 0.9, -0.607, 0.097, 0.639, 1.81379, -0.687, 'Down', 0.24020000000000002)
Record inserted
(2005, -0.687, 0.172, 0.9, -0.607, 0.097, 1.62752, 0.125, 'Up', -0.025000000000000015)
Record inserted
(2005, 0.125, -0.687, 0.172, 0.9, -0.607, 1.54712, -0.021, 'Down', -0.019399999999999994)
Record inserted
(2005, -0.021, 0.125, -0.687, 0.172, 0.9, 1.85137, -0.216, 'Down', 0.09779999999999998)
Record inserted
(2005, -0.216, -0.021, 0.125, -0.687, 0.172, 1.71549, 0.524, 'Up', -0.1254)
Record inserted
(2005, 0.524, -0.216, -0.021, 0.125, -0.687, 1.82412, -0.235, 'Down', -0.05500000000000001)
Record inserted
(2005, -0.235, 0.524, -0.216, -0.021, 0.125, 1.66418, 0.226, 'Up', 0.03540000000000001)
Record inserted
(2005, 0.226, -0.235, 0.524, -0.216, -0.021, 1.66135, 0.257, 'Up', 0.055600000000000004)
Record inserted
(2005, 0.257, 0.226, -0.235, 0.524, -0.216, 1.69815, 0.222, 'Up', 0.11120000000000001)
Record inserted
(2005, 0.222, 0.257, 0.226, -0.235, 0.524, 1.84044, 0.363, 'Up', 0.1988)
Record inserted
(2005, 0.363, 0.222, 0.257, 0.226, -0.235, 1.77604, 0.495, 'Up', 0.16660000000000003)
Record inserted
(2005, 0.495, 0.363, 0.222, 0.257, 0.226, 2.40737, -0.071, 'Down', 0.31260000000000004)
Record inserted
(2005, -0.071, 0.495, 0.363, 0.222, 0.257, 1.71453, -0.205, 'Down', 0.2532)
Record inserted
(2005, -0.205, -0.071, 0.495, 0.363, 0.222, 1.7207, 0.022, 'Up', 0.1608)
Record inserted
(2005, 0.022, -0.205, -0.071, 0.495, 0.363, 1.82325, -1.083, 'Down', 0.12079999999999999)
Record inserted
(2005, -1.083, 0.022, -0.205, -0.071, 0.495, 2.02992, -0.763, 'Down', -0.1684)
Record inserted
(2005, -0.763, -1.083, 0.022, -0.205, -0.071, 2.4188, -0.074, 'Down', -0.42000000000000004)
Record inserted
(2005, -0.074, -0.763, -1.083, 0.022, -0.205, 1.73862, 0.914, 'Up', -0.4206)
Record inserted
(2005, 0.914, -0.074, -0.763, -1.083, 0.022, 1.77241, -0.143, 'Down', -0.19679999999999995)
Record inserted
(2005, -0.143, 0.914, -0.074, -0.763, -1.083, 1.76928, -0.71, 'Down', -0.2298)
Record inserted
(2005, -0.71, -0.143, 0.914, -0.074, -0.763, 2.10949, 0.261, 'Up', -0.15519999999999998)
Record inserted
(2005, 0.261, -0.71, -0.143, 0.914, -0.074, 1.59382, 0.883, 'Up', 0.04960000000000001)
Record inserted
(2005, 0.883, 0.261, -0.71, -0.143, 0.914, 1.80582, -0.834, 'Down', 0.24100000000000002)
Record inserted
(2005, -0.834, 0.883, 0.261, -0.71, -0.143, 1.88347, 0.245, 'Up', -0.10859999999999999)
Record inserted
(2005, 0.245, -0.834, 0.883, 0.261, -0.71, 1.95244, 1.168, 'Up', -0.030999999999999982)
Record inserted
(2005, 1.168, 0.245, -0.834, 0.883, 0.261, 1.90081, 0.625, 'Up', 0.34459999999999996)
Record inserted
(2005, 0.625, 1.168, 0.245, -0.834, 0.883, 1.8463, 0.227, 'Up', 0.41739999999999994)
Record inserted
(2005, 0.227, 0.625, 1.168, 0.245, -0.834, 1.93201, 0.088, 'Up', 0.2862)
Record inserted
(2005, 0.088, 0.227, 0.625, 1.168, 0.245, 1.8125, 0.262, 'Up', 0.47059999999999996)
Record inserted
(2005, 0.262, 0.088, 0.227, 0.625, 1.168, 2.04871, 0.116, 'Up', 0.47400000000000003)
Record inserted
(2005, 0.116, 0.262, 0.088, 0.227, 0.625, 1.7164, -0.553, 'Down', 0.2636)
Record inserted
(2005, -0.553, 0.116, 0.262, 0.088, 0.227, 1.5821, 0.673, 'Up', 0.02799999999999999)
Record inserted
(2005, 0.673, -0.553, 0.116, 0.262, 0.088, 2.04128, 0.476, 'Up', 0.1172)
Record inserted
(2005, 0.476, 0.673, -0.553, 0.116, 0.262, 2.06334, -0.661, 'Down', 0.1948)
Record inserted
(2005, -0.661, 0.476, 0.673, -0.553, 0.116, 2.12984, 0.541, 'Up', 0.01019999999999999)
Record inserted
(2005, 0.541, -0.661, 0.476, 0.673, -0.553, 1.76699, -0.377, 'Down', 0.09519999999999998)
Record inserted
(2005, -0.377, 0.541, -0.661, 0.476, 0.673, 1.71758, 0.173, 'Up', 0.13040000000000002)
Record inserted
(2005, 0.173, -0.377, 0.541, -0.661, 0.476, 1.93418, 0.457, 'Up', 0.030399999999999993)
Record inserted
(2005, 0.457, 0.173, -0.377, 0.541, -0.661, 1.9458, 0.56, 'Up', 0.026600000000000002)
Record inserted
(2005, 0.56, 0.457, 0.173, -0.377, 0.541, 2.00168, -0.767, 'Down', 0.27080000000000004)
Record inserted
(2005, -0.767, 0.56, 0.457, 0.173, -0.377, 1.7896, 0.095, 'Up', 0.009200000000000009)
Record inserted
(2005, 0.095, -0.767, 0.56, 0.457, 0.173, 1.71687, 0.71, 'Up', 0.1036)
Record inserted
(2005, 0.71, 0.095, -0.767, 0.56, 0.457, 2.04312, 0.074, 'Up', 0.211)
Record inserted
(2005, 0.074, 0.71, 0.095, -0.767, 0.56, 1.99998, -0.737, 'Down', 0.1344)
Record inserted
(2005, -0.737, 0.074, 0.71, 0.095, -0.767, 1.98122, -0.764, 'Down', -0.12500000000000003)
Record inserted
(2005, -0.764, -0.737, 0.074, 0.71, 0.095, 1.93028, -0.268, 'Down', -0.12439999999999998)
Record inserted
(2005, -0.268, -0.764, -0.737, 0.074, 0.71, 1.80414, 0.674, 'Up', -0.197)
Record inserted
(2005, 0.674, -0.268, -0.764, -0.737, 0.074, 1.89752, -0.183, 'Down', -0.2042)
Record inserted
(2005, -0.183, 0.674, -0.268, -0.764, -0.737, 2.17232, 0.706, 'Up', -0.2556)
Record inserted
(2005, 0.706, -0.183, 0.674, -0.268, -0.764, 1.94156, -0.599, 'Down', 0.03300000000000001)
Record inserted
(2005, -0.599, 0.706, -0.183, 0.674, -0.268, 1.7093, 0.283, 'Up', 0.06600000000000002)
Record inserted
(2005, 0.283, -0.599, 0.706, -0.183, 0.674, 1.56288, -1.178, 'Down', 0.1762)
Record inserted
(2005, -1.178, 0.283, -0.599, 0.706, -0.183, 1.82041, 0.074, 'Up', -0.1942)
Record inserted
(2005, 0.074, -1.178, 0.283, -0.599, 0.706, 1.85915, -0.1, 'Down', -0.14279999999999998)
Record inserted
(2005, -0.1, 0.074, -1.178, 0.283, -0.599, 1.80817, 0.057, 'Up', -0.304)
Record inserted
(2005, 0.057, -0.1, 0.074, -1.178, 0.283, 1.55879, 0.166, 'Up', -0.1728)
Record inserted
(2005, 0.166, 0.057, -0.1, 0.074, -1.178, 1.62133, -0.339, 'Down', -0.19619999999999999)
Record inserted
(2005, -0.339, 0.166, 0.057, -0.1, 0.074, 1.67862, -0.657, 'Down', -0.0284)
Record inserted
(2005, -0.657, -0.339, 0.166, 0.057, -0.1, 1.9308, 0.23, 'Up', -0.17459999999999998)
Record inserted
(2005, 0.23, -0.657, -0.339, 0.166, 0.057, 1.57111, -0.6, 'Down', -0.10859999999999999)
Record inserted
(2005, -0.6, 0.23, -0.657, -0.339, 0.166, 1.54109, 0.596, 'Up', -0.24000000000000005)
Record inserted
(2005, 0.596, -0.6, 0.23, -0.657, -0.339, 1.59945, -0.319, 'Down', -0.154)
Record inserted
(2005, -0.319, 0.596, -0.6, 0.23, -0.657, 1.91647, 0.986, 'Up', -0.15)
Record inserted
(2005, 0.986, -0.319, 0.596, -0.6, 0.23, 2.36551, 0.103, 'Up', 0.17859999999999998)
Record inserted
(2005, 0.103, 0.986, -0.319, 0.596, -0.6, 2.22986, -0.292, 'Down', 0.15320000000000003)
Record inserted
(2005, -0.292, 0.103, 0.986, -0.319, 0.596, 1.64016, 1.262, 'Up', 0.21479999999999996)
Record inserted
(2005, 1.262, -0.292, 0.103, 0.986, -0.319, 1.93209, 0.241, 'Up', 0.34800000000000003)
Record inserted
(2005, 0.241, 1.262, -0.292, 0.103, 0.986, 2.0677, -0.379, 'Down', 0.45999999999999996)
Record inserted
(2005, -0.379, 0.241, 1.262, -0.292, 0.103, 1.95538, 0.796, 'Up', 0.187)
Record inserted
(2005, 0.796, -0.379, 0.241, 1.262, -0.292, 1.99256, -0.074, 'Down', 0.3256)
Record inserted
(2005, -0.074, 0.796, -0.379, 0.241, 1.262, 1.93805, -0.754, 'Down', 0.36920000000000003)
Record inserted
(2005, -0.754, -0.074, 0.796, -0.379, 0.241, 2.08236, -0.328, 'Down', -0.03399999999999999)
Record inserted
(2005, -0.328, -0.754, -0.074, 0.796, -0.379, 1.98675, 0.046, 'Up', -0.14780000000000001)
Record inserted
(2005, 0.046, -0.328, -0.754, -0.074, 0.796, 2.07934, 0.829, 'Up', -0.06280000000000001)
Record inserted
(2005, 0.829, 0.046, -0.328, -0.754, -0.074, 3.15247, -0.557, 'Down', -0.056200000000000014)
Record inserted
(2005, -0.557, 0.829, 0.046, -0.328, -0.754, 2.07654, -0.786, 'Down', -0.15280000000000002)
Record inserted
(2005, -0.786, -0.557, 0.829, 0.046, -0.328, 2.31925, -0.912, 'Down', -0.1592)
Record inserted
(2005, -0.912, -0.786, -0.557, 0.829, 0.046, 2.54815, 0.365, 'Up', -0.27599999999999997)
Record inserted
(2005, 0.365, -0.912, -0.786, -0.557, 0.829, 2.42472, 0.055, 'Up', -0.21220000000000003)
Record inserted
(2005, 0.055, 0.365, -0.912, -0.786, -0.557, 1.97302, 0.028, 'Up', -0.367)
Record inserted
(2005, 0.028, 0.055, 0.365, -0.912, -0.786, 2.02222, 0.002, 'Up', -0.25)
Record inserted
(2005, 0.002, 0.028, 0.055, 0.365, -0.912, 1.97627, 0.101, 'Up', -0.09240000000000001)
Record inserted
(2005, 0.101, 0.002, 0.028, 0.055, 0.365, 2.10698, 0.887, 'Up', 0.11019999999999999)
Record inserted
(2005, 0.887, 0.101, 0.002, 0.028, 0.055, 2.17612, 0.092, 'Up', 0.21459999999999999)
Record inserted
(2005, 0.092, 0.887, 0.101, 0.002, 0.028, 2.09752, -0.172, 'Down', 0.22200000000000003)
Record inserted
(2005, -0.172, 0.092, 0.887, 0.101, 0.002, 2.09749, -0.997, 'Down', 0.182)
Record inserted
(2005, -0.997, -0.172, 0.092, 0.887, 0.101, 2.34142, -1.489, 'Down', -0.01779999999999999)
Record inserted
(2005, -1.489, -0.997, -0.172, 0.092, 0.887, 2.54678, -0.41, 'Down', -0.33580000000000004)
Record inserted
(2005, -0.41, -1.489, -0.997, -0.172, 0.092, 2.79203, 0.37, 'Up', -0.5952)
Record inserted
(2005, 0.37, -0.41, -1.489, -0.997, -0.172, 2.12608, -0.717, 'Down', -0.5396000000000001)
Record inserted
(2005, -0.717, 0.37, -0.41, -1.489, -0.997, 2.19599, -0.207, 'Down', -0.6486)
Record inserted
(2005, -0.207, -0.717, 0.37, -0.41, -1.489, 2.29904, -0.607, 'Down', -0.49060000000000004)
Record inserted
(2005, -0.607, -0.207, -0.717, 0.37, -0.41, 2.49128, -0.071, 'Down', -0.3142)
Record inserted

(2005, -0.071, -0.607, -0.207, -0.717, 0.37, 2.35115, 0.827, 'Up', -0.24639999999999995)
Record inserted
(2005, 0.827, -0.071, -0.607, -0.207, -0.717, 2.18894, 0.297, 'Up', -0.15499999999999997)
Record inserted
(2005, 0.297, 0.827, -0.071, -0.607, -0.207, 2.05457, -1.005, 'Down', 0.047799999999999995)
Record inserted
(2005, -1.005, 0.297, 0.827, -0.071, -0.607, 2.19701, 1.496, 'Up', -0.11179999999999998)
Record inserted
(2005, 1.496, -1.005, 0.297, 0.827, -0.071, 2.70359, -1.502, 'Down', 0.3088)
Record inserted
(2005, -1.502, 1.496, -1.005, 0.297, 0.827, 2.61725, 0.152, 'Up', 0.0226)
Record inserted
(2005, 0.152, -1.502, 1.496, -1.005, 0.297, 2.47092, 1.678, 'Up', -0.11240000000000001)
Record inserted
(2005, 1.678, 0.152, -1.502, 1.496, -1.005, 2.19779, -0.237, 'Down', 0.1638)
Record inserted
(2005, -0.237, 1.678, 0.152, -1.502, 1.496, 2.31247, -0.431, 'Down', 0.31739999999999996)
Record inserted
(2005, -0.431, -0.237, 1.678, 0.152, -1.502, 2.46775, -1.048, 'Down', -0.06800000000000002)
Record inserted
(2005, -1.048, -0.431, -0.237, 1.678, 0.152, 2.39537, 1.655, 'Up', 0.02279999999999995)
Record inserted
(2005, 1.655, -1.048, -0.431, -0.237, 1.678, 2.3794, 0.718, 'Up', 0.3234)
Record inserted
(2005, 0.718, 1.655, -1.048, -0.431, -0.237, 2.56747, -0.352, 'Down', 0.13140000000000002)
Record inserted
(2005, -0.352, 0.718, 1.655, -1.048, -0.431, 2.45785, 0.998, 'Up', 0.10839999999999997)
Record inserted
(2005, 0.998, -0.352, 0.718, 1.655, -1.048, 2.64809, 0.426, 'Up', 0.3942)
Record inserted
(2005, 0.426, 0.998, -0.352, 0.718, 1.655, 2.71663, 0.016, 'Up', 0.6890000000000001)
Record inserted
(2005, 0.016, 0.426, 0.998, -0.352, 0.718, 2.05051, 0.219, 'Up', 0.3612)
Record inserted
(2005, 0.219, 0.016, 0.426, 0.998, -0.352, 1.98758, -0.345, 'Down', 0.26139999999999997)
Record inserted
(2005, -0.345, 0.219, 0.016, 0.426, 0.998, 1.96505, 0.169, 'Up', 0.26280000000000003)
Record inserted
(2005, 0.169, -0.345, 0.219, 0.016, 0.426, 2.21446, 0.845, 'Up', 0.097)
Record inserted
(2005, 0.845, 0.169, -0.345, 0.219, 0.016, 2.37846, 0.305, 'Up', 0.18080000000000002)
Record inserted
(2005, 0.305, 0.845, 0.169, -0.345, 0.219, 1.77314, -0.078, 'Down', 0.2386)
Record inserted
(2005, -0.078, 0.305, 0.845, 0.169, -0.345, 1.89978, -0.385, 'Down', 0.17920000000000003)
Record inserted
(2005, -0.385, -0.078, 0.305, 0.845, 0.169, 2.35937, 0.179, 'Up', 0.1712)
Record inserted
(2005, 0.179, -0.385, -0.078, 0.305, 0.845, 2.12158, 0.941, 'Up', 0.17319999999999997)
Record inserted
(2005, 0.941, 0.179, -0.385, -0.078, 0.305, 2.29804, 0.44, 'Up', 0.1924)
Record inserted
(2005, 0.44, 0.941, 0.179, -0.385, -0.078, 2.45329, 0.527, 'Up', 0.21939999999999998)
Record inserted
(2005, 0.527, 0.44, 0.941, 0.179, -0.385, 2.11735, 0.508, 'Up', 0.3403999999999999)
Record inserted
(2005, 0.508, 0.527, 0.44, 0.941, 0.179, 2.29142, 0.347, 'Up', 0.5189999999999999)
Record inserted
(2005, 0.347, 0.508, 0.527, 0.44, 0.941, 1.9854, 0.209, 'Up', 0.5526)
Record inserted
(2005, 0.209, 0.347, 0.508, 0.527, 0.44, 0.72494, -0.851, 'Down', 0.4062)
Record inserted
(2005, -0.851, 0.209, 0.347, 0.508, 0.527, 2.0169, 0.002, 'Up', 0.148)
Record inserted
(2005, 0.002, -0.851, 0.209, 0.347, 0.508, 2.26834, -0.636, 'Down', 0.043)
Record inserted
(2005, -0.636, 0.002, -0.851, 0.209, 0.347, 2.37469, 1.216, 'Up', -0.18579999999999997)
Record inserted
(2005, 1.216, -0.636, 0.002, -0.851, 0.209, 2.61483, 0.032, 'Up', -0.012000000000000005)
Record inserted
(2005, 0.032, 1.216, -0.636, 0.002, -0.851, 2.12558, -0.236, 'Down', -0.0474)
Record inserted
(2005, -0.236, 0.032, 1.216, -0.636, 0.002, 2.32584, 0.128, 'Up', 0.0756)
Record inserted
(2005, 0.128, -0.236, 0.032, 1.216, -0.636, 2.11074, -0.501, 'Down', 0.10079999999999997)
Record inserted
(2005, -0.501, 0.128, -0.236, 0.032, 1.216, 2.09383, -0.122, 'Down', 0.1278)
Record inserted
(2005, -0.122, -0.501, 0.128, -0.236, 0.032, 2.1783, 0.281, 'Up', -0.13979999999999998)
Record inserted
(2005, 0.281, -0.122, -0.501, 0.128, -0.236, 1.89629, 0.084, 'Up', -0.09)
Record inserted
(2005, 0.084, 0.281, -0.122, -0.501, 0.128, 1.87655, 0.555, 'Up', -0.02599999999999999)
Record inserted
(2005, 0.555, 0.084, 0.281, -0.122, -0.501, 2.39002, 0.419, 'Up', 0.05940000000000001)
Record inserted
(2005, 0.419, 0.555, 0.084, 0.281, -0.122, 2.14552, -0.141, 'Down', 0.2434)
Record inserted
(2005, -0.141, 0.419, 0.555, 0.084, 0.281, 2.18059, -0.285, 'Down', 0.23959999999999998)
Record inserted
(2005, -0.285, -0.141, 0.419, 0.555, 0.084, 2.58419, -0.584, 'Down', 0.1264)
Record inserted
(2005, -0.584, -0.285, -0.141, 0.419, 0.555, 2.20881, -0.024, 'Down', -0.007199999999999984)
Record inserted
(2005, -0.024, -0.584, -0.285, -0.141, 0.419, 1.99669, 0.252, 'Up', -0.123)
Record inserted
(2005, 0.252, -0.024, -0.584, -0.285, -0.141, 2.06517, 0.422, 'Up', -0.1564)
Record inserted
(2005, 0.422, 0.252, -0.024, -0.584, -0.285, 1.8885, 0.043, 'Up', -0.043800000000000006)
Record inserted
(2005, 0.043, 0.422, 0.252, -0.024, -0.584, 1.28581, -0.955, 'Down', 0.021799999999999996)
Record inserted
(2005, -0.955, 0.043, 0.422, 0.252, -0.024, 1.54047, 0.13, 'Up', -0.05239999999999999)
Record inserted
(2005, 0.13, -0.955, 0.043, 0.422, 0.252, 1.42236, -0.298, 'Down', -0.021599999999999987)
Record inserted
(2005, -0.298, 0.13, -0.955, 0.043, 0.422, 1.38254, -0.489, 'Down', -0.13160000000000002)
Record inserted

In [128]:
df.shape

(1250, 10)

In [105]:
df1=pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BCF.csv')

In [106]:
df1.head()

         date  values.I2P  values.P2I  values.JPI
0  1996-04-01   -2.580556   -0.836444        63.3
1  1996-05-01   -2.882258   -1.972581        66.3
2  1996-06-01   -1.742778   -0.478778        59.7
3  1996-07-01   -0.397796   -1.574301        63.3
4  1996-08-01   -0.977151   -1.797312        63.8

In [107]:
df1.dtypes

date           object
values.I2P    float64
values.P2I    float64
values.JPI    float64
dtype: object

In [108]:
replacement={
    'object':'varchar(100)',
    'float64':'float(50)'
}

In [119]:
df1.columns

Index(['date', 'values_I2P', 'values_P2I', 'values_JPI'], dtype='object')

In [120]:
len(df1.columns)

4

In [115]:
df1.columns=[i.replace(".","_") for i in df1.columns]
df1.columns

Index(['date', 'values_I2P', 'values_P2I', 'values_JPI'], dtype='object')

In [116]:
columns = ", ".join("{} {}".format(a,b) for (a,b) in zip(df1.columns, df1.dtypes.replace(replacement)))
columns

'date varchar(100), values_I2P float(50), values_P2I float(50), values_JPI float(50)'

In [117]:
cursor.execute('create table Bcf ({})'.format(columns))

In [122]:
for (i,row) in df1.iterrows():
    statement='insert into Bcf values({},{},{},{})'.format(row[0],row[1],row[2],row[3])
    cursor.execute(statement)
    print("Record inserted")
    connection.commit()

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted

In [123]:
df1.shape

(117, 4)

In [124]:
cursor.execute('create table Bcf1 ({})'.format(columns))

In [126]:
for (i,row) in df1.iterrows():
    statement='insert into Bcf1 values(%s,%s,%s,%s)'
    cursor.execute(statement,list(row))
    print("Record inserted")
    connection.commit()

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted

In [137]:
df2=pd.read_csv('https://raw.githubusercontent.com/sudh9931/data/main/haberman.csv',header=None,names=['one','two','three','four'])

In [138]:
df2.head()

   one  two  three  four
0   30   64      1     1
1   30   62      3     1
2   30   65      0     1
3   31   59      2     1
4   31   65      4     1

In [139]:
df2.dtypes

one      int64
two      int64
three    int64
four     int64
dtype: object

In [148]:
replaced={
    'int64':'bigint(50)'
}

In [149]:
df2.columns

Index(['one', 'two', 'three', 'four'], dtype='object')

In [152]:
columns=",".join("{} {}".format(a,b) for (a,b) in zip(df2.columns,df2.dtypes.replace(replaced)))
columns

'one bigint(50),two bigint(50),three bigint(50),four bigint(50)'

In [153]:
cursor.execute('create table haberman ({})'.format(columns))

In [154]:
for (i,row) in df2.iterrows():
    statement='insert into haberman values(%s,%s,%s,%s)'
    cursor.execute(statement,list(row))
    print('Record inserted')
    connection.commit()
print

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted

In [155]:
df2.shape

(306, 4)

In [156]:
df3=pd.read_html('https://www.basketball-reference.com/leagues/NBA_2015_totals.html')

In [157]:
type(df3)

list

In [158]:
type(df3[0])

pandas.core.frame.DataFrame

In [159]:
df3[0].head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035

In [160]:
df3[0].columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [161]:
len(df3)

1

In [164]:
len(df3[0].columns)

30

In [175]:
df3[0].dtypes

Rk        object
Player    object
Pos       object
Age       object
Tm        object
G         object
GS        object
MP        object
FG        object
FGA       object
FG_       object
3P        object
3PA       object
3P_       object
2P        object
2PA       object
2P_       object
eFG_      object
FT        object
FTA       object
FT_       object
ORB       object
DRB       object
TRB       object
AST       object
STL       object
BLK       object
TOV       object
PF        object
PTS       object
dtype: object

In [176]:
df3[0].isnull().sum()

Rk         0
Player     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG_        2
3P         0
3PA        0
3P_       81
2P         0
2PA        0
2P_        4
eFG_       2
FT         0
FTA        0
FT_       25
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
dtype: int64

In [179]:
df3[0].fillna('<na>',inplace=True)

In [180]:
df3[0].isnull().sum()

Rk        0
Player    0
Pos       0
Age       0
Tm        0
G         0
GS        0
MP        0
FG        0
FGA       0
FG_       0
3P        0
3PA       0
3P_       0
2P        0
2PA       0
2P_       0
eFG_      0
FT        0
FTA       0
FT_       0
ORB       0
DRB       0
TRB       0
AST       0
STL       0
BLK       0
TOV       0
PF        0
PTS       0
dtype: int64

In [181]:
df3[0].columns=[i.replace('%','_') for i in df3[0].columns]
df3[0].columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG_',
       '3P', '3PA', '3P_', '2P', '2PA', '2P_', 'eFG_', 'FT', 'FTA', 'FT_',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [182]:
replacement={
    'object':'varchar(100)'
    
}

In [183]:
columns=",".join("{} {}".format(a,b) for (a,b) in zip(df3[0].columns,df3[0].dtypes.replace(replacement)))
columns

'Rk varchar(100),Player varchar(100),Pos varchar(100),Age varchar(100),Tm varchar(100),G varchar(100),GS varchar(100),MP varchar(100),FG varchar(100),FGA varchar(100),FG_ varchar(100),3P varchar(100),3PA varchar(100),3P_ varchar(100),2P varchar(100),2PA varchar(100),2P_ varchar(100),eFG_ varchar(100),FT varchar(100),FTA varchar(100),FT_ varchar(100),ORB varchar(100),DRB varchar(100),TRB varchar(100),AST varchar(100),STL varchar(100),BLK varchar(100),TOV varchar(100),PF varchar(100),PTS varchar(100)'

In [173]:
cursor.execute('create table basketball ({})'.format(columns))

In [184]:
for (i,row) in df3[0].iterrows():
    sql='insert into basketball values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)'
    cursor.execute(sql,list(row))
    print("Record Iserted")
    connection.commit()
print("All rcords Inserted")

Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted

Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
Record Iserted
All rcords Inserted

In [185]:
df3[0].shape

(675, 30)

In [187]:
data=pd.read_excel(r'C:\Users\ks\Desktop\Ineuron_pythonProject\24-07 Pandas day1\Dataset\data fsds\Attribute DataSet.xlsx')

In [188]:
data.head()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0

In [189]:
data.dtypes

Dress_ID            int64
Style              object
Price              object
Rating            float64
Size               object
Season             object
NeckLine           object
SleeveLength       object
waiseline          object
Material           object
FabricType         object
Decoration         object
Pattern Type       object
Recommendation      int64
dtype: object

In [190]:
data.isnull().sum()

Dress_ID            0
Style               0
Price               2
Rating              0
Size                0
Season              2
NeckLine            3
SleeveLength        2
waiseline          87
Material          128
FabricType        266
Decoration        236
Pattern Type      109
Recommendation      0
dtype: int64

In [191]:
data.describe()

           Dress_ID      Rating  Recommendation
count  5.000000e+02  500.000000      500.000000
mean   9.055417e+08    3.528600        0.420000
std    1.736190e+08    2.005364        0.494053
min    4.442820e+08    0.000000        0.000000
25%    7.673164e+08    3.700000        0.000000
50%    9.083296e+08    4.600000        0.000000
75%    1.039534e+09    4.800000        1.000000
max    1.253973e+09    5.000000        1.000000

In [196]:
sample=data[data.dtypes[data.dtypes=='object'].index]

In [197]:
sample

,Style,Price,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type
0,Sexy,Low,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal
1,Casual,Low,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal
2,vintage,High,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print
3,Brief,Average,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print
4,cute,Low,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot
...,...,...,...,...,...,...,...,...,...,...,...
495,Casual,Low,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid
496,Sexy,Low,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN
497,Casual,Average,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid
498,Casual,Average,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print
499,Casual,Low,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid

In [198]:
sample.describe()

,Style,Price,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type
count,500,498,500,498,497,498,413,372,234,264,391
unique,13,7,7,8,16,17,4,23,22,24,14
top,Casual,Average,M,Summer,o-neck,sleevless,natural,cotton,chiffon,lace,solid
freq,232,252,177,159,271,223,304,152,135,70,203

In [200]:
data.isnull().sum()

Dress_ID            0
Style               0
Price               2
Rating              0
Size                0
Season              2
NeckLine            3
SleeveLength        2
waiseline          87
Material          128
FabricType        266
Decoration        236
Pattern Type      109
Recommendation      0
dtype: int64

In [207]:
data[data['FabricType']=='chiffon']

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
9,985292672,bohemian,Low,0.0,free,Summer,v-neck,sleevless,natural,nylon,chiffon,NaN,NaN,1
12,957723897,sexy,Low,4.7,M,Winter,o-neck,threequarter,NaN,NaN,chiffon,lace,print,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,511503677,Casual,Low,4.4,M,Summer,o-neck,halfsleeve,empire,chiffonfabric,chiffon,bow,solid,0
490,641665398,Casual,Low,4.8,free,winter,bowneck,full,natural,polyster,chiffon,bow,solid,0
492,859922576,cute,Average,4.6,M,Spring,o-neck,halfsleeve,natural,acrylic,chiffon,NaN,NaN,0
493,817353671,bohemian,Low,4.6,free,Summer,o-neck,sleevless,natural,cotton,chiffon,none,solid,1
494,990559192,Brief,Average,4.7,M,winter,o-neck,halfsleeve,natural,acrylic,chiffon,NaN,striped,0

In [209]:
data['FabricType'].value_counts()

chiffon       135
broadcloth     31
worsted        19
jersey         12
shiffon         9
sattin          6
batik           2
wollen          2
Corduroy        2
poplin          2
dobby           2
tulle           2
organza         1
knitted         1
lace            1
knitting        1
flannel         1
woolen          1
flannael        1
satin           1
other           1
terry           1
Name: FabricType, dtype: int64

In [220]:
data.isnull().sum()

Dress_ID            0
Style               0
Price               2
Rating              0
Size                0
Season              2
NeckLine            3
SleeveLength        2
waiseline          87
Material            0
FabricType          0
Decoration          0
Pattern Type      109
Recommendation      0
dtype: int64

In [215]:
data['Material'].value_counts()

cotton           280
polyster          99
silk              26
chiffonfabric     25
mix               12
nylon             10
rayon             10
milksilk           5
spandex            5
cashmere           4
linen              3
lycra              3
microfiber         3
acrylic            3
viscos             2
shiffon            2
other              2
modal              1
knitting           1
sill               1
wool               1
model              1
lace               1
Name: Material, dtype: int64

In [218]:
data['Decoration'].value_counts()

lace          70
sashes        42
beading       22
hollowout     21
applique      21
ruffles       17
bow           15
sequined      14
button         6
pockets        5
embroidary     5
flowers        4
ruched         3
crystal        3
rivet          3
feathers       2
draped         2
plain          2
none           2
pearls         1
pleat          1
Tiered         1
tassel         1
cascading      1
Name: Decoration, dtype: int64

In [222]:
data['Pattern Type'].value_counts()

solid        203
print         71
patchwork     48
animal        21
striped       17
dot           14
geometric      5
plaid          3
leopard        3
floral         2
character      1
splice         1
leapord        1
none           1
Name: Pattern Type, dtype: int64

In [210]:
data['FabricType'].fillna('chiffon',inplace=True)

In [214]:
data['Material'].fillna('cotton',inplace=True)

In [219]:
data['Decoration'].fillna('lace',inplace=True)

In [223]:
data['Pattern Type'].fillna('solid',inplace=True)

In [228]:
data.isnull().sum()

Dress_ID          0
Style             0
Price             2
Rating            0
Size              0
Season            2
NeckLine          3
SleeveLength      2
waiseline         0
Material          0
FabricType        0
Decoration        0
Pattern Type      0
Recommendation    0
dtype: int64

In [229]:
data['waiseline'].value_counts()

natural     391
empire      104
dropped       4
princess      1
Name: waiseline, dtype: int64

In [230]:
data.shape

(500, 14)

In [227]:
data['waiseline'].fillna('natural',inplace=True)

In [231]:
data.dropna(axis=0,inplace=True)

In [232]:
data.shape

(493, 14)

In [233]:
data.isnull().sum()

Dress_ID          0
Style             0
Price             0
Rating            0
Size              0
Season            0
NeckLine          0
SleeveLength      0
waiseline         0
Material          0
FabricType        0
Decoration        0
Pattern Type      0
Recommendation    0
dtype: int64

In [234]:
data.columns

Index(['Dress_ID', 'Style', 'Price', 'Rating', 'Size', 'Season', 'NeckLine',
       'SleeveLength', 'waiseline', 'Material', 'FabricType', 'Decoration',
       'Pattern Type', 'Recommendation'],
      dtype='object')

In [235]:
data.columns=[i.replace(" ","_") for i in data.columns]
data.columns

Index(['Dress_ID', 'Style', 'Price', 'Rating', 'Size', 'Season', 'NeckLine',
       'SleeveLength', 'waiseline', 'Material', 'FabricType', 'Decoration',
       'Pattern_Type', 'Recommendation'],
      dtype='object')

In [236]:
data.dtypes

Dress_ID            int64
Style              object
Price              object
Rating            float64
Size               object
Season             object
NeckLine           object
SleeveLength       object
waiseline          object
Material           object
FabricType         object
Decoration         object
Pattern_Type       object
Recommendation      int64
dtype: object

In [244]:
replacement={
    "int64":"int(50)",
    "float64":"float(50)",
    "object":"varchar(100)"
}

In [245]:
len(data.columns)

14

In [240]:
columns=",".join("{} {}".format(a,b) for (a,b) in zip(data.columns,data.dtypes.replace(replacement)))
columns

'Dress_ID int(50),Style varchar(100),Price varchar(100),Rating float(50),Size varchar(100),Season varchar(100),NeckLine varchar(100),SleeveLength varchar(100),waiseline varchar(100),Material varchar(100),FabricType varchar(100),Decoration varchar(100),Pattern_Type varchar(100),Recommendation int(50)'

In [241]:
cursor.execute('create table Attribute({})'.format(columns))

In [246]:
for (i,row) in data.iterrows():
    sql='insert into Attribute values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)'
    cursor.execute(sql,list(row))
    print("Record inserted")
    connection.commit()
print("All records inserted successfully!!")

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
All records inserted successfully!!

In [248]:
dress=pd.read_excel(r'C:\Users\ks\Desktop\Ineuron_pythonProject\24-07 Pandas day1\Dataset\data fsds\Dress Sales.xlsx')

In [249]:
dress.head()

,Dress_ID,29/8/2013,31/8/2013,2013-02-09 00:00:00,2013-04-09 00:00:00,2013-06-09 00:00:00,2013-08-09 00:00:00,2013-10-09 00:00:00,2013-12-09 00:00:00,14/9/2013,...,24/9/2013,26/9/2013,28/9/2013,30/9/2013,2013-02-10 00:00:00,2013-04-10 00:00:00,2013-06-10 00:00:00,2010-08-10 00:00:00,2013-10-10 00:00:00,2013-12-10 00:00:00
0,1006032852,2114,2274,2491,2660,2727,2887,2930,3119,3204,...,3554,3624.0,3706,3746.0,3795.0,3832.0,3897,3923.0,3985.0,4048
1,1212192089,151,275,570,750,813,1066,1164,1558,1756,...,2710,2942.0,3258,3354.0,3475.0,3654.0,3911,4024.0,4125.0,4277
2,1190380701,6,7,7,7,8,8,9,10,10,...,11,11.0,11,11.0,11.0,11.0,11,11.0,11.0,11
3,966005983,1005,1128,1326,1455,1507,1621,1637,1723,1746,...,1878,1892.0,1914,1924.0,1929.0,1941.0,1952,1955.0,1959.0,1963
4,876339541,996,1175,1304,1396,1432,1559,1570,1638,1655,...,2032,2156.0,2252,2312.0,2387.0,2459.0,2544,2614.0,2693.0,2736

In [251]:
dress.shape

(500, 24)

In [252]:
dress.dtypes

Dress_ID                 int64
29/8/2013                int64
31/8/2013                int64
2013-02-09 00:00:00      int64
2013-04-09 00:00:00      int64
2013-06-09 00:00:00      int64
2013-08-09 00:00:00      int64
2013-10-09 00:00:00      int64
2013-12-09 00:00:00     object
14/9/2013               object
16/9/2013               object
18/9/2013               object
20/9/2013               object
22/9/2013               object
24/9/2013                int64
26/9/2013              float64
28/9/2013                int64
30/9/2013              float64
2013-02-10 00:00:00    float64
2013-04-10 00:00:00    float64
2013-06-10 00:00:00      int64
2010-08-10 00:00:00    float64
2013-10-10 00:00:00    float64
2013-12-10 00:00:00      int64
dtype: object

In [253]:
dress.isnull().sum()

Dress_ID                 0
29/8/2013                0
31/8/2013                0
2013-02-09 00:00:00      0
2013-04-09 00:00:00      0
2013-06-09 00:00:00      0
2013-08-09 00:00:00      0
2013-10-09 00:00:00      0
2013-12-09 00:00:00      0
14/9/2013                0
16/9/2013                0
18/9/2013                0
20/9/2013                0
22/9/2013                0
24/9/2013                0
26/9/2013              237
28/9/2013                0
30/9/2013              273
2013-02-10 00:00:00    275
2013-04-10 00:00:00    274
2013-06-10 00:00:00      0
2010-08-10 00:00:00    271
2013-10-10 00:00:00    271
2013-12-10 00:00:00      0
dtype: int64

In [254]:
dress.describe()

,Dress_ID,29/8/2013,31/8/2013,2013-02-09 00:00:00,2013-04-09 00:00:00,2013-06-09 00:00:00,2013-08-09 00:00:00,2013-10-09 00:00:00,24/9/2013,26/9/2013,28/9/2013,30/9/2013,2013-02-10 00:00:00,2013-04-10 00:00:00,2013-06-10 00:00:00,2010-08-10 00:00:00,2013-10-10 00:00:00,2013-12-10 00:00:00
count,5.000000e+02,500.00000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,263.000000,500.000000,227.000000,225.000000,226.000000,500.000000,229.000000,229.000000,500.000000
mean,9.055417e+08,189.76600,200.966000,214.162000,298.672000,303.658000,315.294000,318.782000,371.232000,296.326996,387.468000,244.105727,250.644444,254.004425,412.668000,261.205240,265.314410,431.066000
std,1.736190e+08,568.26459,579.802126,591.975613,593.140026,595.178184,600.208193,601.436695,621.755471,690.560310,636.531597,691.372495,701.867298,707.526486,655.084359,717.910654,726.557201,671.642137
min,4.442820e+08,0.00000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7.673164e+08,0.00000,0.000000,0.000000,30.750000,33.000000,38.000000,39.750000,55.000000,20.500000,58.000000,14.000000,15.000000,15.000000,65.750000,17.000000,17.000000,70.750000
50%,9.083296e+08,1.00000,1.000000,2.000000,113.000000,118.500000,130.000000,134.000000,185.000000,61.000000,193.000000,54.000000,55.000000,56.000000,212.000000,61.000000,62.000000,222.000000
75%,1.039534e+09,124.25000,145.250000,179.750000,305.750000,315.000000,328.000000,331.750000,428.750000,227.500000,440.000000,134.500000,135.000000,136.000000,475.500000,169.000000,171.000000,520.500000
max,1.253973e+09,7455.00000,7467.000000,7479.000000,7374.000000,7351.000000,7255.000000,7240.000000,6644.000000,6528.000000,6476.000000,6327.000000,6285.000000,6142.000000,6049.000000,5912.000000,5862.000000,5753.000000

In [255]:
dress.columns

Index([         'Dress_ID',         '29/8/2013',         '31/8/2013',
       2013-02-09 00:00:00, 2013-04-09 00:00:00, 2013-06-09 00:00:00,
       2013-08-09 00:00:00, 2013-10-09 00:00:00, 2013-12-09 00:00:00,
               '14/9/2013',         '16/9/2013',         '18/9/2013',
               '20/9/2013',         '22/9/2013',         '24/9/2013',
               '26/9/2013',         '28/9/2013',         '30/9/2013',
       2013-02-10 00:00:00, 2013-04-10 00:00:00, 2013-06-10 00:00:00,
       2010-08-10 00:00:00, 2013-10-10 00:00:00, 2013-12-10 00:00:00],
      dtype='object')

In [258]:
len(dress.columns)

24

In [259]:
dress.isnull().sum()

Dress_ID                 0
29/8/2013                0
31/8/2013                0
2013-02-09 00:00:00      0
2013-04-09 00:00:00      0
2013-06-09 00:00:00      0
2013-08-09 00:00:00      0
2013-10-09 00:00:00      0
2013-12-09 00:00:00      0
14/9/2013                0
16/9/2013                0
18/9/2013                0
20/9/2013                0
22/9/2013                0
24/9/2013                0
26/9/2013              237
28/9/2013                0
30/9/2013              273
2013-02-10 00:00:00    275
2013-04-10 00:00:00    274
2013-06-10 00:00:00      0
2010-08-10 00:00:00    271
2013-10-10 00:00:00    271
2013-12-10 00:00:00      0
dtype: int64

In [260]:
dress.columns = ['`'+str(str(x).split(' ')[0])+'`' for x in dress.columns]
dress.columns

Index(['`Dress_ID`', '`29/8/2013`', '`31/8/2013`', '`2013-02-09`',
       '`2013-04-09`', '`2013-06-09`', '`2013-08-09`', '`2013-10-09`',
       '`2013-12-09`', '`14/9/2013`', '`16/9/2013`', '`18/9/2013`',
       '`20/9/2013`', '`22/9/2013`', '`24/9/2013`', '`26/9/2013`',
       '`28/9/2013`', '`30/9/2013`', '`2013-02-10`', '`2013-04-10`',
       '`2013-06-10`', '`2010-08-10`', '`2013-10-10`', '`2013-12-10`'],
      dtype='object')

In [261]:
dress.dtypes

`Dress_ID`        int64
`29/8/2013`       int64
`31/8/2013`       int64
`2013-02-09`      int64
`2013-04-09`      int64
`2013-06-09`      int64
`2013-08-09`      int64
`2013-10-09`      int64
`2013-12-09`     object
`14/9/2013`      object
`16/9/2013`      object
`18/9/2013`      object
`20/9/2013`      object
`22/9/2013`      object
`24/9/2013`       int64
`26/9/2013`     float64
`28/9/2013`       int64
`30/9/2013`     float64
`2013-02-10`    float64
`2013-04-10`    float64
`2013-06-10`      int64
`2010-08-10`    float64
`2013-10-10`    float64
`2013-12-10`      int64
dtype: object

In [263]:
dress.fillna('<na>',inplace=True)

In [264]:
dress.isnull().sum()

`Dress_ID`      0
`29/8/2013`     0
`31/8/2013`     0
`2013-02-09`    0
`2013-04-09`    0
`2013-06-09`    0
`2013-08-09`    0
`2013-10-09`    0
`2013-12-09`    0
`14/9/2013`     0
`16/9/2013`     0
`18/9/2013`     0
`20/9/2013`     0
`22/9/2013`     0
`24/9/2013`     0
`26/9/2013`     0
`28/9/2013`     0
`30/9/2013`     0
`2013-02-10`    0
`2013-04-10`    0
`2013-06-10`    0
`2010-08-10`    0
`2013-10-10`    0
`2013-12-10`    0
dtype: int64

In [268]:
replacement

{'int64': 'int(50)', 'float64': 'float(50)', 'object': 'varchar(100)'}

In [272]:
len(dress.columns)

24

In [270]:
columns=",".join('{} {}'.format(a,b) for (a,b) in zip(dress.columns,dress.dtypes.replace(replacement)))
columns

'`Dress_ID` int(50),`29/8/2013` int(50),`31/8/2013` int(50),`2013-02-09` int(50),`2013-04-09` int(50),`2013-06-09` int(50),`2013-08-09` int(50),`2013-10-09` int(50),`2013-12-09` varchar(100),`14/9/2013` varchar(100),`16/9/2013` varchar(100),`18/9/2013` varchar(100),`20/9/2013` varchar(100),`22/9/2013` varchar(100),`24/9/2013` int(50),`26/9/2013` varchar(100),`28/9/2013` int(50),`30/9/2013` varchar(100),`2013-02-10` varchar(100),`2013-04-10` varchar(100),`2013-06-10` int(50),`2010-08-10` varchar(100),`2013-10-10` varchar(100),`2013-12-10` int(50)'

In [271]:
cursor.execute('create table dress({})'.format(columns))

In [274]:
for (i,row) in dress.iterrows():
    sql='insert into dress values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)'
    cursor.execute(sql,list(row))
    print('Record Inserted')
    connection.commit()
print("All records inserted successfully!!!")

Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
Record Inserted
All records inserted successfully!!!

In [275]:
dress.shape

(500, 24)

In [276]:
data.head()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern_Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,cotton,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,chiffon,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,chiffon,lace,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0

In [277]:
data.to_json('Attributejson.json')

In [278]:
temp=pd.read_json('Attributejson.json')

In [279]:
temp.head()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern_Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,cotton,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,chiffon,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,chiffon,lace,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0

In [280]:
import pymongo

In [281]:
client = pymongo.MongoClient(
    "mongodb+srv://prasathkkps:Luci1108@cluster0.ldqcx.mongodb.net/?retryWrites=true&w=majority")
db = client.test
print(db)

Database(MongoClient(host=['cluster0-shard-00-00.ldqcx.mongodb.net:27017', 'cluster0-shard-00-01.ldqcx.mongodb.net:27017', 'cluster0-shard-00-02.ldqcx.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', authsource='admin', replicaset='atlas-2mebps-shard-0', tls=True), 'test')

In [282]:
database=client['AttributeData']
collection=database['Attribute']

In [286]:
data.reset_index(inplace=True)
data_dict = df.to_dict("records")
collection.insert_many(data_dict)

## SQL COMMANDS

In [ ]:
show databases;
use smarket_data;
show tables;
desc smarket;
select * from bcf1;
select count(*) from bcf1;
select * from smarket;
select count(*) from smarket;
select * from haberman;
select count(*) from haberman;
select * from basketball;
select count(*) from basketball;
select * from attribute;
select count(*) from attribute;
select * from dress;
select count(*) from dress;
desc dress;
desc attribute;
select * from dress;
select * from attribute;
select attribute.Dress_ID,Price,Rating,Size,Recommendation,'29/8/2013','31/8/2013' from attribute left join dress on attribute.Dress_ID=dress.Dress_ID;

select distinct count(Dress_ID) from dress;
select count(*) from attribute where recommendation=0;